import BrandLogo from '@/components/brand-logo';
import {DOC_FIELDS,estimateTotals,lineAmount,type Proposal,type Requirement} from '@/lib/hq-sales';
import type {AgreementSignature} from '@/lib/hq-estimating';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export default function AgreementDocument({proposal:p,requirements=p.requirements_snapshot,signatures=[]}:{proposal:Proposal;requirements?:Requirement[];signatures?:AgreementSignature[]}){
 const t=estimateTotals(p.lines);
 return <article className="agreement-document"><header><BrandLogo plate/><div><p>ESTIMATE & PROJECT AGREEMENT</p><h1>{p.title}</h1><p>{p.number} · Revision {p.revision} · {p.status.toUpperCase()}</p><p>Valid through {p.valid_until}</p></div></header>
 {p.status==='draft'&&<p className="agreement-draft">DRAFT — pricing and terms are still being prepared.</p>}{p.document.previous_offer&&<p>Revises offer: {p.document.previous_offer}</p>}
 {DOC_FIELDS.slice(0,8).map(([k,label])=><section key={k}><h2>{label}</h2><p className="hq-preserve">{p.document[k]||'To be completed'}</p></section>)}
 <section><h2>Fees · USD</h2><div className="agreement-table-scroll"><table><thead><tr><th>Service / description</th><th>Quantity</th><th>Unit price</th><th>Discount</th><th>Amount</th><th>Basis</th></tr></thead><tbody>{p.lines.map((l,i)=><tr key={i}><td>{l.description}</td><td>{l.quantity_units/100}</td><td>{l.unit_cents?money(l.unit_cents):'Price needed'}</td><td>{money(l.discount_cents)}</td><td>{money(lineAmount(l))}</td><td>{l.cadence.replaceAll('_',' ')}</td></tr>)}</tbody></table></div><div className="agreement-totals"><p>One-time subtotal <strong>{money(t.one_time)}</strong></p><p>One-time tax <strong>{money(p.tax_cents)}</strong></p><p>One-time total <strong>{money(t.one_time+p.tax_cents)}</strong></p><p>Initial payment toward total <strong>{money(p.deposit_cents)}</strong></p><p>Monthly charges <strong>{money(t.monthly)} / month</strong></p><p>Annual charges <strong>{money(t.annual)} / year</strong></p></div>{p.lines.some(l=>l.cadence==='usage')&&<p>Usage charges depend on consumption and the terms below. They are excluded from fixed totals.</p>}</section>
 <section><h2>Deliverables and acceptance criteria</h2>{requirements.map((r,i)=><div className="agreement-requirement" key={r.id}><h3>{i+1}. {r.title}</h3><p>{r.priority==='must'?'Required':'Included'} · {r.actor}</p><p className="hq-preserve"><strong>Workflow: </strong>{r.steps}</p><p className="hq-preserve"><strong>Acceptance: </strong>{r.expected}</p></div>)}</section>
 {DOC_FIELDS.slice(8).map(([k,label])=><section key={k}><h2>{label}</h2><p className="hq-preserve">{p.document[k]||'To be completed'}</p></section>)}
 <section><h2>Agreement signatures</h2><div className="agreement-signatures">{(['client','provider'] as const).map(party=>{const s=signatures.find(s=>s.party===party);return <div key={party}><h3>{party==='client'?'Client':'WorkForge'}</h3>{s?<><p className="signature-name">{s.name}</p>{s.signature_image&&<img className="signature-image" src={s.signature_image} alt={party+' drawn signature'}/>}<p>{s.title} · {s.email}</p><p>Signed {new Date(s.signed_at).toISOString().replace('T',' ').replace('Z',' UTC')}</p><p className="signature-consent">{s.consent}</p></>:<p>Awaiting signature</p>}</div>;})}</div>{signatures[0]&&<p className="signature-hash">Agreement fingerprint (SHA-256): {signatures[0].document_hash}</p>}{p.status==='accepted'&&!signatures.length&&<p>External acceptance recorded for {p.accepted_name} on {p.accepted_on}. The signed source document is retained separately.</p>}</section><footer>WorkForge · {p.number} · Revision {p.revision}</footer>
 </article>;
}
