'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { configureRelay } from '@/app/hq/admin/actions';
import type { LeadRelay } from '@/lib/hq-admin';
import { dateLabel } from '@/lib/core';

export default function LeadRelaySetup({relay,admin}:{relay:LeadRelay;admin:boolean}){
 const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [key,setKey]=useState('');const [message,setMessage]=useState('');
 const url=`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/hq-ad-intake?provider=${relay.provider}&transport=relay`;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await configureRelay(new FormData(e.currentTarget));if(!r.ok)setError(r.error||'Unable to save.');else{if(r.key)setKey(r.key);setMessage('Settings saved. Finish the GHL workflow and send a test.');router.refresh();}}catch{setError('Unable to save. Please retry.');}finally{setBusy(false);}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('Copied.');}catch{setError('Select the field and copy it manually.');}}
 return <details className="hq-relay-setup"><summary>Connect through GoHighLevel</summary><p className="hq-relay-status">{!relay.enabled?'Not configured':relay.last_received_at?`Last lead received ${dateLabel(relay.last_received_at)}`:relay.last_test_at?`Test received ${dateLabel(relay.last_test_at)}`:'Ready for setup — no delivery verified yet'}</p><p className="hq-hint">Use your existing GHL lead workflow to deliver inquiries to WorkForge. Choose this route or the native connection above for each form.</p>
 {admin&&<form className="hq-form hq-connection-form" onSubmit={save}><fieldset disabled={busy}><input type="hidden" name="provider" value={relay.provider}/><div className="hq-relay-fields"><label>Connection<select name="enabled" defaultValue="true"><option value="true">Enable</option><option value="false">Disable</option></select></label><label>Assign leads to<select name="default_owner" defaultValue={relay.default_owner}><option>Shawn</option><option>Neil</option></select></label><label>Allowed form IDs<input name="form_ids" defaultValue={relay.form_ids.join(', ')} required placeholder="Form IDs, separated by commas"/></label>{relay.provider==='meta'?<label>Facebook Page ID<input name="page_id" defaultValue={relay.page_id} required/></label>:<input type="hidden" name="page_id" value=""/>}<label>Connection key<select name="rotate" defaultValue={relay.enabled?'false':'true'}><option value="false">Keep current key</option><option value="true">Generate a new key</option></select></label></div><button className="primary" disabled={busy}>{busy?'Saving…':'Save GHL connection'}</button><p className="hq-hint">A new key replaces the old one. Update GHL immediately if you rotate it.</p></fieldset></form>}
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status" className="hq-hint">{message}</p>}
 {admin&&<><label className="hq-connection-url">GHL webhook URL<input readOnly value={url} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={()=>copy(url)}>Copy URL</button>{key&&<div className="hq-relay-fields"><label>Connection key — copy before leaving<input readOnly type="password" value={key} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={()=>copy(key)}>Copy connection key</button></div>}
 <ol className="hq-hint"><li>In GHL, use a workflow limited to the matching WorkForge {relay.provider==='meta'?'Facebook Page and lead form':'Google lead source and form'}.</li><li>Add an outbound Webhook action, choose POST, and paste the URL above.</li><li>Add the custom data fields below. Use GHL’s field picker for contact values.</li><li>Send a test with <code>is_test</code> set to <code>true</code>. Check the delivery receipt in HQ. Then remove that flag and publish the workflow.</li></ol>
 <div className="hq-table-wrap"><table className="hq-table"><thead><tr><th>Custom data key</th><th>Value</th></tr></thead><tbody><tr><td>workforge_key</td><td>The copied connection key</td></tr><tr><td>form_id</td><td>The matching allowed form ID</td></tr>{relay.provider==='meta'&&<tr><td>page_id</td><td>{relay.page_id||'WorkForge Facebook Page ID'}</td></tr>}<tr><td>contact_id</td><td>Contact ID from the GHL field picker</td></tr><tr><td>lead_id (optional)</td><td>Original Facebook or Google submission ID</td></tr><tr><td>submitted_at (optional)</td><td>Original submission time, ISO 8601 with timezone</td></tr><tr><td>is_test (test only)</td><td>true</td></tr></tbody></table></div><p className="hq-hint">Standard name, email, phone, and company fields are read automatically. Include campaign/ad names and an <code>answers</code> object for custom form responses. If the original lead ID is unavailable, HQ creates one inquiry per GHL contact and form; repeat deliveries reuse that inquiry. Test receipts never create sales records.</p></>}
 </details>;
}
