'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { configureAdIntake, retryAdIntake } from '@/app/hq/actions';
import { canWrite, dateLabel } from '@/lib/core';
import { hqDay, subscriptionMRR, workflowIssues, type HQData } from '@/lib/hq';
import type { HQForm } from './forms';

const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
type Props={data:HQData;today:string;show:(form:HQForm)=>void;openAccount:(id:string)=>void};

export function SupportView({data:d,today,show,openAccount}:Props) {
  const [filter,setFilter]=useState('open');
  const writable=canWrite(d.role);
  const name=(id:string)=>d.accounts.find(a=>a.id===id)?.company??'Account';
  const rows=d.tickets.filter(t=>filter==='all'||(filter==='resolved'?t.status==='resolved':t.status!=='resolved'));
  return <>
    <section className="hq-panel"><header><h2>Support tickets</h2><select aria-label="Support ticket status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open tickets</option><option value="resolved">Resolved</option><option value="all">All tickets</option></select></header>
      <div className="hq-table-wrap"><table className="hq-table"><thead><tr><th>Customer / issue</th><th>Priority / status</th><th>Owner</th><th>First response due</th><th/></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><button className="hq-link" onClick={()=>openAccount(t.account_id)}>{name(t.account_id)}</button><small>{t.title}</small></td><td><span className={`hq-badge ${t.priority==='urgent'?'lost':''}`}>{t.priority}</span><small>{t.status.replaceAll('_',' ')}</small></td><td>{t.owner}</td><td><span className={!t.first_response_at&&t.status!=='resolved'&&Date.parse(t.response_due_at)<Date.now()?'hq-overdue':''}>{dateLabel(t.response_due_at)}</span><small>{t.first_response_at?`Responded ${dateLabel(t.first_response_at)}`:'No response recorded'}</small></td><td>{writable&&<button className="hq-link" onClick={()=>show({kind:'ticket',record:t})}>Open ticket</button>}</td></tr>)}</tbody></table></div>
      {!rows.length&&<div className="hq-empty"><h3>No tickets in this view</h3><p>Record issues from customer calls or emails. Assign an owner and response deadline, then record the resolution.</p></div>}
    </section>
    <section className="hq-panel hq-spaced"><header><h2>Customer support handoffs</h2></header>{d.supportPlans.map(p=><div className="hq-attention" key={p.id}><div><button className="hq-link" onClick={()=>openAccount(p.account_id)}>{name(p.account_id)}</button><span>{p.owner} · {p.launched_at?'Launched':'Preparing for launch'}</span><p className="hq-preserve">{p.terms}</p><span className={p.next_review_on<today?'hq-overdue':''}>Next review {hqDay(p.next_review_on)}</span></div>{writable&&<button className="secondary" onClick={()=>show({kind:'support_plan',record:p})}>Edit handoff</button>}</div>)}{!d.supportPlans.length&&<div className="hq-empty"><p>Set the customer’s support owner, agreed terms, and next review date from their account before launch.</p></div>}</section>
  </>;
}

export function SubscriptionsView({data:d,today,show,openAccount}:Props) {
  return <><section className="hq-metrics hq-three"><div><span>Software MRR</span><strong>{money(subscriptionMRR(d.subscriptions.filter(s=>s.service==='software'),today))}</strong><small>Active recorded subscriptions</small></div><div><span>Managed support MRR</span><strong>{money(subscriptionMRR(d.subscriptions.filter(s=>s.service==='support'),today))}</strong><small>Annual amounts divided by 12</small></div><div><span>Payment follow-ups</span><strong>{d.subscriptions.filter(s=>s.status==='active'&&s.payment_status==='past_due').length}</strong><small>Manually recorded as past due</small></div></section><section className="hq-panel"><div className="hq-table-wrap"><table className="hq-table"><thead><tr><th>Customer / plan</th><th>Recurring fee</th><th>Status</th><th>Renewal / end</th><th/></tr></thead><tbody>{d.subscriptions.map(s=><tr key={s.id}><td><button className="hq-link" onClick={()=>openAccount(s.account_id)}>{d.accounts.find(a=>a.id===s.account_id)?.company}</button><small>{s.plan} · {s.service}</small></td><td>{money(s.amount_cents)}<small>{s.cadence}</small></td><td><span className="hq-badge">{s.status}</span><small>Payment: {s.payment_status.replace('_',' ')}</small></td><td>{hqDay(s.renews_on)}{s.ends_on&&<small>Ends {hqDay(s.ends_on)}</small>}</td><td>{canWrite(d.role)&&<button className="hq-link" onClick={()=>show({kind:'subscription',record:s})}>Edit</button>}</td></tr>)}</tbody></table></div>{!d.subscriptions.length&&<div className="hq-empty"><h3>No subscriptions recorded</h3><p>Add the agreed plan, activation date, renewal date and payment status for each won customer.</p></div>}<p className="hq-panel-note">These are internal subscription records. Saving or activating a record does not charge a customer, provision a workspace, or send an invoice. MRR excludes trials, pending, paused, cancelled, future and ended subscriptions.</p></section></>;
}

export function WorkflowAttention({data:d,today,show,openAccount}:Props) {
  const issues=workflowIssues(d,today);
  const cutoff=new Date(`${today}T12:00:00Z`); cutoff.setUTCDate(cutoff.getUTCDate()+30);
  const renewals=d.subscriptions.filter(s=>s.status==='active'&&s.renews_on<=cutoff.toISOString().slice(0,10)&&(!s.ends_on||s.ends_on>today));
  const tickets=d.tickets.filter(t=>t.status!=='resolved'&&(t.priority==='urgent'||(!t.first_response_at&&Date.parse(t.response_due_at)<Date.now())));
  const reviews=d.supportPlans.filter(p=>p.launched_at&&p.next_review_on<=today);
  return <section className="hq-panel hq-spaced"><header><h2>Delivery and customer follow-ups</h2></header>{issues.map((issue,index)=><button className="hq-attention" key={`${issue.accountId}-${index}`} onClick={()=>openAccount(issue.accountId)}><div><strong>{d.accounts.find(a=>a.id===issue.accountId)?.company}</strong><span>{issue.message}</span></div></button>)}{tickets.map(t=><button className="hq-attention" key={t.id} onClick={()=>canWrite(d.role)?show({kind:'ticket',record:t}):openAccount(t.account_id)}><div><strong>{t.title}</strong><span>{t.owner} · {t.priority==='urgent'?'Urgent support issue':'First response overdue'}</span></div></button>)}{reviews.map(p=><button className="hq-attention" key={p.id} onClick={()=>openAccount(p.account_id)}><div><strong>{d.accounts.find(a=>a.id===p.account_id)?.company}</strong><span>Customer review due {hqDay(p.next_review_on)} · {p.owner}</span></div></button>)}{renewals.map(s=><button className="hq-attention" key={s.id} onClick={()=>openAccount(s.account_id)}><div><strong>{s.plan}</strong><span>Renewal {s.renews_on<today?'overdue':'due'} {hqDay(s.renews_on)} · {d.accounts.find(a=>a.id===s.account_id)?.company}</span></div></button>)}{!issues.length&&!tickets.length&&!reviews.length&&!renewals.length&&<p className="hq-panel-note">No delivery gaps, overdue responses, customer reviews or renewals due in the next 30 days.</p>}</section>;
}

export function IntegrationsView({data:d,openAccount}:Pick<Props,'data'|'openAccount'>) {
  const router=useRouter(); const [editing,setEditing]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [key,setKey]=useState('');
  const admin=['owner','administrator'].includes(d.role);
  const base=`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/hq-ad-intake`;
  async function save(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true);setError('');setKey('');
    try {const r=await configureAdIntake(new FormData(e.currentTarget));if(!r.ok)setError(r.error||'Unable to save.');else{setKey(r.key||'');router.refresh();}}catch{setError('Unable to save. Please retry.');}finally{setBusy(false);}
  }
  async function retry(id:string) {setBusy(true);setError('');try{const r=await retryAdIntake(id);if(!r.ok)setError(r.error||'Retry failed.');router.refresh();}catch{setError('Retry failed.');}finally{setBusy(false);}}
  return <><p className="hq-panel-note">Website inquiries already arrive through the website form connection, including the submitted source and campaign fields. These connections add forms submitted directly inside Google Ads and Meta.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="hq-delivery-grid hq-spaced">{d.adIntegrations.map(i=><section className="hq-panel" key={i.provider}><header><h2>{i.provider==='meta'?'Meta lead forms':'Google Ads lead forms'}</h2><span className="hq-badge">{!i.enabled?'Setup needed':i.last_received_at?'Receiving leads':i.last_test_at?'Test received':'Awaiting provider test'}</span></header><div className="hq-delivery-body"><p className="hq-muted">New inquiries assigned to {i.default_owner} with a follow-up due today.</p><p className="hq-preserve hq-spaced">{i.last_received_at?`Last lead: ${dateLabel(i.last_received_at)}`:'No live lead received on this configuration.'}</p>{i.last_test_at&&<p className="hq-muted">Last test: {dateLabel(i.last_test_at)}</p>}{i.last_error&&<p className="error">{i.last_error}</p>}<label className="hq-connection-url">Webhook URL<input readOnly value={`${base}?provider=${i.provider}`} onFocus={e=>e.target.select()}/></label>{admin&&<button className="secondary" onClick={()=>{setEditing(editing===i.provider?null:i.provider);setKey('');setError('');}}>{i.enabled?'Update connection':'Set up connection'}</button>}
      {editing===i.provider&&<form className="hq-form hq-connection-form" onSubmit={save}><fieldset disabled={busy}><input type="hidden" name="provider" value={i.provider}/><label>Connection<select name="enabled" defaultValue="true"><option value="true">Enable / replace credentials</option><option value="false">Disable</option></select></label><label>Assign new leads to<select name="default_owner" defaultValue={i.default_owner}><option>Shawn</option><option>Neil</option></select></label><label>Allowed lead form IDs<input name="form_ids" defaultValue={i.form_ids.join(', ')} placeholder="Numeric IDs, separated by commas"/></label>{i.provider==='meta'?<><label>WorkForge Facebook Page ID<input name="page_id" defaultValue={i.page_id}/></label><label>Meta app secret<input type="password" name="app_secret" autoComplete="new-password"/></label><label>Page access token<input type="password" name="page_token" autoComplete="new-password"/></label><label>Graph API version<input name="graph_version" placeholder="Version shown in your Meta app, e.g. v25.0"/></label><p className="hq-hint">Use a token authorized to retrieve leads from this page. In your Meta app, subscribe the Page webhook to leadgen, verify this callback, and subscribe the WorkForge Page to the app. Keep credentials out of chat.</p></>:<>{['page_id','app_secret','page_token','graph_version'].map(n=><input key={n} type="hidden" name={n} value=""/>)}<p className="hq-hint">After saving, paste the URL and generated key into each Google Ads lead form’s lead delivery settings, then send its test. Google Ads test submissions do not enter the sales pipeline.</p></>}<p className="hq-hint">Enabling generates a new key. If updating a connection, replace the provider’s existing key immediately.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save connection'}</button></fieldset>{key&&<div className="hq-spaced"><label>Copy this {i.provider==='meta'?'verification token':'Google key'} now<input readOnly type="password" value={key} onFocus={e=>e.target.select()}/></label><button type="button" className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(key);}catch{setError('Select the key field and copy it manually.');}}}>Copy key</button><p className="hq-hint">Shown only in this session. Finish the provider setup before closing this panel.</p></div>}</form>}
    </div></section>)}</div><section className="hq-panel hq-spaced"><header><h2>Recent ad lead deliveries</h2></header><div className="hq-table-wrap"><table className="hq-table"><thead><tr><th>Source / form</th><th>Status</th><th>Last update</th><th>Account / action</th></tr></thead><tbody>{d.adReceipts.map(r=><tr key={`${r.provider}-${r.external_id}`}><td>{r.provider==='meta'?'Meta':'Google Ads'}<small>Form {r.form_id}</small><small>Lead {r.external_id}</small></td><td>{r.status}<small>{r.error_code}</small></td><td>{dateLabel(r.updated_at)}</td><td>{r.account_id&&<button className="hq-link" onClick={()=>openAccount(r.account_id!)}>Open inquiry</button>}{r.provider==='meta'&&['pending','failed'].includes(r.status)&&canWrite(d.role)&&<button className="secondary" disabled={busy} onClick={()=>retry(r.external_id)}>Retry delivery</button>}</td></tr>)}</tbody></table></div>{!d.adReceipts.length&&<div className="hq-empty"><p>No ad form deliveries yet. Configure a connection and send a test from the provider.</p></div>}<p className="hq-panel-note">Shows the latest 1,000 receipts. Duplicate provider deliveries reuse the same receipt and inquiry.</p></section></>;
}
