'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,CheckCircle2,FileText,Plus} from 'lucide-react';
import BrandLogo from '@/components/brand-logo';
import {canWrite} from '@/lib/core';
import type {HQData} from '@/lib/hq';
import {DISCOVERY,DOC_FIELDS,CATEGORIES,CADENCES,DEFAULT_TERMS,estimateTotals,lineAmount,decimalUnits,latestRun,betaReadiness,type Proposal,type EstimateLine,type Opportunity,type DeliveryProject} from '@/lib/hq-sales';
import type {SalesData} from '@/lib/hq-sales-data';
import {saveSales} from '@/app/hq/sales-actions';
import {HQDialog} from './forms';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
type Editor={kind:string;record?:Record<string,any>;parent?:string}; // Records are validated again by the server and database.
function Field({name,label,value='',rows=0,required=false,type='text'}:{name:string;label:string;value?:string|number|null;rows?:number;required?:boolean;type?:string}){return <label>{label}{rows?<textarea name={name} rows={rows} defaultValue={value??''} required={required} maxLength={20000}/>:<input name={name} type={type} step={type==='number'?'0.01':undefined} defaultValue={value??''} required={required} maxLength={500}/>}</label>;}
function Owner({value='Shawn'}:{value?:string}){return <label>WorkForge owner<select name="owner" defaultValue={value}><option>Shawn</option><option>Neil</option></select></label>;}
function Pick({name,label,value,options}:{name:string;label:string;value?:string;options:readonly string[]}){return <label>{label}<select name={name} defaultValue={value}>{options.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label>;}

export default function SalesWorkbench({data:d,sales:s,initialAccount}:{data:HQData;sales:SalesData;initialAccount?:string}){
 const router=useRouter();const writable=canWrite(d.role);
 const [accountId,setAccountId]=useState(initialAccount&&d.accounts.some(a=>a.id===initialAccount)?initialAccount:d.accounts[0]?.id??'');
 const [opportunityId,setOpportunityId]=useState('');const [tab,setTab]=useState('discovery');
 const [editor,setEditor]=useState<Editor|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [dirty,setDirty]=useState(false);
 const opportunities=s.opportunities.filter(o=>o.account_id===accountId);
 const o=opportunities.find(o=>o.id===opportunityId)??opportunities[0];
 const account=d.accounts.find(a=>a.id===accountId);
 const requirements=s.requirements.filter(r=>r.opportunity_id===o?.id);
 const proposals=s.proposals.filter(p=>p.opportunity_id===o?.id);
 const project=s.projects.find(p=>p.opportunity_id===o?.id);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 function leave(){if(!dirty||window.confirm('Discard unsaved discovery changes?')){setDirty(false);return true;}return false;}
 function edit(e:Editor){setError('');setEditor(e);}
 async function run(kind:string,payload:Record<string,unknown>,record?:Record<string,any>){
  if(busy)return;setBusy(true);setError('');setMessage('');
  const fd=new FormData();fd.set('payload',JSON.stringify(payload));if(record){fd.set('id',record.id);fd.set('updated_at',record.updated_at??'');}
  try{const r=await saveSales(kind,fd);if(!r.ok){setError(r.error??'Unable to save.');return false;}setEditor(null);setDirty(false);if(kind==='opportunity'&&r.id)setOpportunityId(r.id);setMessage(kind==='proposal_status'&&payload.status==='accepted'?'Acceptance recorded. Fees, project checklist and tests are linked to this agreement.':'Saved successfully.');router.refresh();return true;}catch{setError('Unable to save. Please retry.');return false;}finally{setBusy(false);}
 }
 async function discoverySubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!o)return;const f=new FormData(e.currentTarget);const answers=Object.fromEntries(DISCOVERY.map(([key])=>[key,{status:f.get(key+'_status'),notes:f.get(key+'_notes')}]));await run('discovery',{answers,open_questions:f.get('open_questions')},o);}
 const resolved=o?DISCOVERY.filter(([k])=>o.discovery.answers?.[k]?.status!=='unknown'&&o.discovery.answers?.[k]?.notes?.trim()).length:0;
 return <div className="hq-shell sales-shell"><aside className="hq-sidebar"><BrandLogo/><div className="hq-workspace"><span>INTERNAL OPERATIONS</span><strong>WorkForge HQ</strong><small>Sales & delivery</small></div><a className="sales-back" href="/hq"><ArrowLeft size={18}/>Back to HQ</a><nav aria-label="Sales and delivery">{[['discovery','Discovery'],['agreements','Estimates & agreements'],['delivery','Implementation & beta']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{if(leave()){setTab(id);setError('');}}}>{label}</button>)}</nav><p className="sales-sidebar-note">One customer history. Every agreement keeps its own scope, delivery and acceptance.</p></aside>
 <div className="hq-main-shell"><main className="hq-main"><div className="hq-heading"><div><p className="hq-eyebrow">WORKFORGE HQ</p><h1>Sales & delivery</h1><p>From the first discovery call to a confident customer launch.</p></div><a className="secondary" href="/hq">Open HQ</a></div>
 <div className="sales-selectors"><label>Customer<select value={accountId} onChange={e=>{if(leave()){setAccountId(e.target.value);setOpportunityId('');}}}><option value="">Choose a customer</option>{d.accounts.map(a=><option key={a.id} value={a.id}>{a.company}</option>)}</select></label><label>Engagement<select value={o?.id??''} onChange={e=>{if(leave())setOpportunityId(e.target.value);}}><option value="">Choose an engagement</option>{opportunities.map(o=><option key={o.id} value={o.id}>{o.title} · {o.kind}</option>)}</select></label>{writable&&<button className="primary" disabled={!accountId} onClick={()=>edit({kind:'opportunity'})}><Plus size={17}/>New engagement</button>}</div>
 {message&&<p className="hq-toast" role="status"><CheckCircle2 size={18}/>{message}</p>}{error&&!editor&&<p className="error" role="alert">{error}</p>}
 {!account?<div className="hq-empty"><h2>Start with a customer inquiry</h2><p>Website inquiries appear in the HQ sales pipeline. Add a customer there, then create their engagement here.</p><a href="/hq" className="primary">Open sales pipeline</a></div>:!o?<div className="hq-empty"><h2>Define the next piece of work</h2><p>Create a Blueprint, implementation or change engagement for {account.company}.</p></div>:<>
 <section className="sales-context"><div><strong>{o.title}</strong><p>{account.contact_name} · {account.phone||account.email}</p></div><div><span className="hq-badge">{o.kind} · {o.stage}</span><p>{o.owner} · {o.next_action} · Due {o.due_on}</p></div>{writable&&<button className="secondary" onClick={()=>edit({kind:'opportunity',record:o})}>Edit engagement</button>}</section>
 {tab==='discovery'&&<><div className="hq-section-heading"><h2>Discovery record</h2><span>{resolved} / {DISCOVERY.length} sections resolved{dirty?' · Unsaved changes':''}</span></div><p className="hq-muted">Walk through a real customer workflow. Record the exceptions and measurable outcomes before estimating. Unknowns can be the contracted deliverables of a paid Blueprint.</p>
 <form key={o.id+o.updated_at} className="sales-discovery" onChange={()=>setDirty(true)} onSubmit={discoverySubmit}><fieldset disabled={!writable||busy}>{DISCOVERY.map(([key,label,hint])=><details key={key} open={undefined}><summary>{label}<span>{o.discovery.answers?.[key]?.status?.replaceAll('_',' ')??'unknown'}</span></summary><p className="hq-muted">{hint}</p><Pick name={key+'_status'} label="Finding status" value={o.discovery.answers?.[key]?.status??'unknown'} options={['unknown','confirmed','not_applicable']}/><Field name={key+'_notes'} label="Findings, evidence or reason not applicable" rows={4} value={o.discovery.answers?.[key]?.notes}/></details>)}<Field name="open_questions" label="Unresolved questions / customer requests" rows={3} value={o.discovery.open_questions}/><p className="hq-hint">Include an owner and due date for each request. Clear this list when resolved. Store account owners and secure access methods here; keep passwords and API secrets out of notes.</p>{writable&&<button className="primary" disabled={busy}>{busy?'Saving…':'Save discovery'}</button>}</fieldset></form>
 <section className="hq-panel hq-spaced"><header><div><h2>Deliverables & acceptance criteria</h2><p className="hq-muted">These become the issued scope's tests. Put future ideas under Later.</p></div>{writable&&<button className="secondary" onClick={()=>edit({kind:'requirement'})}><Plus size={16}/>Add deliverable</button>}</header>{requirements.map(r=><div key={r.id} className="sales-record"><div><strong>{r.title}</strong><p className="hq-muted">{r.priority} · {r.actor}</p><p className="hq-preserve">{r.expected}</p></div>{writable&&<button className="secondary" onClick={()=>edit({kind:'requirement',record:r})}>Edit</button>}</div>)}{!requirements.length&&<div className="hq-empty"><p>Add at least one must-have deliverable with a concrete expected outcome.</p></div>}</section></>}
 {tab==='agreements'&&<><div className="hq-section-heading"><h2>Estimates & agreements</h2>{writable&&<button className="primary" onClick={()=>edit({kind:'proposal'})}><Plus size={16}/>New estimate</button>}</div><p className="hq-muted">Prepare a customer PDF, issue its frozen version, then record the signed agreement reference. Saving or issuing here does not email a customer or charge a payment.</p>{proposals.map(p=>{const t=estimateTotals(p.lines);return <section className="hq-panel sales-proposal" key={p.id}><header><div><h3>{p.title}</h3><p>{p.number} · Revision {p.revision}</p></div><span className="hq-badge">{p.status==='issued'&&p.valid_until<today()?'expired':p.status}</span></header><div className="sales-record"><div><strong>{money(t.one_time+p.tax_cents)} one-time</strong><p>{money(t.monthly)} / month · {money(t.annual)} / year</p><small>Deposit {money(p.deposit_cents)} · Valid through {p.valid_until}</small>{p.status==='accepted'&&<p>Accepted by {p.accepted_name} · {p.accepted_on}</p>}</div><div className="sales-buttons"><a href={'/hq/agreements/'+p.id} target="_blank" rel="noreferrer" className="secondary"><FileText size={16}/>Preview / PDF</a>{writable&&p.status==='draft'&&<><button className="secondary" onClick={()=>edit({kind:'proposal',record:p})}>Edit draft</button><button className="primary" disabled={busy} onClick={()=>run('proposal_status',{status:'issued',accepted_name:'',accepted_on:'',evidence:''},p)}>Issue version</button></>}{writable&&p.status==='issued'&&<><button className="primary" onClick={()=>edit({kind:'accept',record:p})}>Record acceptance</button><button className="secondary" disabled={busy} onClick={()=>run('proposal_status',{status:'declined',accepted_name:'',accepted_on:'',evidence:''},p)}>Record declined</button></>}{writable&&['issued','declined'].includes(p.status)&&<button className="secondary" disabled={busy} onClick={()=>run('revise',{},p)}>Create revision</button>}</div></div></section>;})}{!proposals.length&&<div className="hq-empty"><h3>Turn discovery into a clear offer</h3><p>Separate setup, recurring charges and usage rates. Complete commercial and agreement terms before issuing.</p></div>}</>}
 {tab==='delivery'&&(!project?<div className="hq-empty"><h2>Delivery starts with an accepted agreement</h2><p>Acceptance creates this engagement's project, checklist and requirement tests automatically.</p><button className="secondary" onClick={()=>setTab('agreements')}>Open agreements <ArrowRight size={16}/></button></div>:<DeliveryView project={project} sales={s} writable={writable} edit={edit}/>)}</>}
 </main></div>
 {editor&&o&&<SalesEditor key={editor.kind+(editor.record?.id??'new')} editor={editor} opportunity={o} account={account!} project={project} busy={busy} error={error} close={()=>{setEditor(null);setError('');}} run={run}/>}
 {editor?.kind==='opportunity'&&!o&&account&&<SalesEditor key="new-opportunity" editor={editor} account={account} busy={busy} error={error} close={()=>setEditor(null)} run={run}/>}
 </div>;
}
function DeliveryView({project:p,sales:s,writable,edit}:{project:DeliveryProject;sales:SalesData;writable:boolean;edit:(e:Editor)=>void}){
 const tasks=s.tasks.filter(t=>t.implementation_id===p.id);const cases=s.cases.filter(c=>c.implementation_id===p.id);const defects=s.defects.filter(d=>d.implementation_id===p.id);const readiness=betaReadiness(p,cases,s.runs,defects);
 return <><div className="hq-section-heading"><h2>{p.project_kind==='blueprint'?'Blueprint delivery':'Implementation & beta'}</h2>{writable&&<button className="primary" onClick={()=>edit({kind:'project',record:p})}>Update project / acceptance</button>}</div><section className="hq-metrics hq-three"><div><span>Project status</span><strong>{p.status==='live'&&p.project_kind==='blueprint'?'Delivered':p.status.replaceAll('_',' ')}</strong><small>{p.owner} · Target {p.target_on??'not set'}</small></div><div><span>Checklist complete</span><strong>{tasks.filter(t=>t.completed).length} / {tasks.length}</strong><small>Evidence required for each item</small></div><div><span>Required tests passed</span><strong>{readiness.passed} / {readiness.total}</strong><small>Release {p.release||'not set'} · {readiness.blockers} blocking issues</small></div></section>
 {p.blocker&&<p className="error">{p.blocker}</p>}<details className="sales-scope"><summary>Agreed scope & customer approval</summary><p className="hq-preserve">{p.scope_snapshot}</p><p>{p.approval_name?`${p.approval_name} approved ${p.approval_release} on ${p.approval_on}`:'Customer acceptance has not been recorded for this release.'}</p><p className="hq-preserve">{p.approval_evidence}</p>{p.proposal_id&&<a className="hq-link" href={'/hq/agreements/'+p.proposal_id}>Open accepted agreement</a>}</details>
 <section className="hq-panel hq-spaced"><header><h2>Milestone checklist</h2></header>{tasks.map(t=><div className="sales-record" key={t.id}><div><strong>{t.completed?'✓ ':''}{t.title}</strong><p className="hq-muted">{t.phase} · {t.owner} · Due {t.due_on}</p>{t.evidence&&<p className="hq-preserve">{t.evidence}</p>}</div>{writable&&<button className="secondary" onClick={()=>edit({kind:'delivery_task',record:t})}>Update</button>}</div>)}</section>
 <section className="hq-panel hq-spaced"><header><div><h2>Customer acceptance tests</h2><p className="hq-muted">Record actual results against the identified release. Keep each retest as a separate run.</p></div>{writable&&<button className="secondary" onClick={()=>edit({kind:'beta_case'})}>Add test</button>}</header>{cases.map(c=>{const latest=latestRun(s.runs,c.id,p.release);return <div className="sales-test" key={c.id}><div className="hq-section-heading"><h3>{c.title}</h3><span className="hq-badge">{latest?.result??'not run'}</span></div><p className="hq-muted">{c.actor} · {c.mandatory?'Required':'Supplementary'}</p><p className="hq-preserve"><strong>Steps: </strong>{c.steps}</p><p className="hq-preserve"><strong>Expected: </strong>{c.expected}</p>{writable&&<button className="secondary" onClick={()=>edit({kind:'beta_run',record:undefined,parent:c.id})}>Record test result</button>}<details><summary>Test history</summary>{s.runs.filter(r=>r.test_id===c.id).map(r=><div className="sales-run" key={r.id}><strong>{r.result} · {r.release}</strong><p>{r.tester} · {new Date(r.created_at).toLocaleString()}</p><p className="hq-preserve">{r.actual}</p><p className="hq-preserve">{r.evidence}</p></div>)}</details></div>;})}</section>
 <section className="hq-panel hq-spaced"><header><h2>Defects & beta exceptions</h2>{writable&&<button className="secondary" onClick={()=>edit({kind:'defect'})}>Add issue</button>}</header>{defects.map(d=><div className="sales-record" key={d.id}><div><strong>{d.title}</strong><p>{d.severity} · {d.status} · {d.owner} · Due {d.due_on}</p><p className="hq-preserve">{d.detail}</p>{d.resolution&&<p className="hq-preserve">{d.resolution}</p>}</div>{writable&&<button className="secondary" onClick={()=>edit({kind:'defect',record:d})}>Update</button>}</div>)}{!defects.length&&<p className="sales-padding hq-muted">No issues recorded. Launch still requires passing tests and customer approval.</p>}</section><p className="hq-hint">Record the support owner, service terms and next review in the HQ customer account before a software launch. Subscription activation and payment recording remain separate actions.</p>
 </>;
}

function SalesEditor({editor:e,opportunity:o,account:a,project:p,busy,error,close,run}:{editor:Editor;opportunity?:Opportunity;account:HQData['accounts'][number];project?:DeliveryProject;busy:boolean;error:string;close:()=>void;run:(kind:string,payload:Record<string,unknown>,record?:Record<string,any>)=>Promise<boolean|undefined>}){
 const r=e.record;const title=({opportunity:'Engagement',requirement:'Deliverable & acceptance criterion',proposal:'Estimate & agreement',accept:'Record customer acceptance',project:'Project & launch acceptance',delivery_task:'Checklist evidence',beta_case:'Acceptance test',beta_run:'Test result',defect:'Defect / exception'} as Record<string,string>)[e.kind];
 const [lines,setLines]=useState<EstimateLine[]>((r?.lines as EstimateLine[])??[{description:'',service:o?.kind==='blueprint'?'blueprint':'implementation',cadence:'one_time',quantity_units:100,unit_cents:0,discount_cents:0}]);
 const [localError,setLocalError]=useState('');
 const document=r?.document??{customer:a.company+'\n'+a.contact_name+'\n'+a.email,scope:a.scope,legal:DEFAULT_TERMS};
 async function submit(ev:React.FormEvent<HTMLFormElement>){ev.preventDefault();setLocalError('');const f=new FormData(ev.currentTarget);const v=Object.fromEntries(f) as Record<string,string>;try{
  let payload:Record<string,unknown>={...v};let action=e.kind;
  if(e.kind==='opportunity')payload={...v,account_id:a.id};
  if(e.kind==='requirement')payload={...v,opportunity_id:o!.id};
  if(e.kind==='proposal')payload={opportunity_id:o!.id,title:v.title,valid_until:v.valid_until,document:Object.fromEntries(DOC_FIELDS.map(([k])=>[k,v['doc_'+k]])),lines:lines.map((l,i)=>({...l,quantity_units:decimalUnits(v['line_'+i+'_quantity']),unit_cents:decimalUnits(v['line_'+i+'_unit']),discount_cents:decimalUnits(v['line_'+i+'_discount'])})),deposit_cents:decimalUnits(v.deposit),tax_cents:decimalUnits(v.tax_amount),terms_reviewed:f.get('terms_reviewed')==='on'};
  if(e.kind==='accept'){action='proposal_status';payload={status:'accepted',accepted_name:v.accepted_name,accepted_on:v.accepted_on,evidence:v.evidence};}
  if(e.kind==='delivery_task')payload={...v,completed:f.get('completed')==='on'};
  if(e.kind==='beta_case')payload={...v,implementation_id:p!.id,mandatory:f.get('mandatory')==='on'};
  if(e.kind==='beta_run')payload={...v,test_id:e.parent,implementation_id:p!.id,release:p!.release};
  if(e.kind==='defect')payload={...v,implementation_id:p!.id};
  await run(action,payload,r);
 }catch(err){setLocalError(err instanceof Error?err.message:'Check these fields.');}}
 const editLine=(i:number,key:string,value:string)=>{try{setLines(ls=>ls.map((l,j)=>i!==j?l:{...l,[key]:['quantity_units','unit_cents','discount_cents'].includes(key)?decimalUnits(value||'0'):value}));setLocalError('');}catch(err){setLocalError(err instanceof Error?err.message:'Check the amount.');}};
 return <HQDialog title={title} busy={busy} onClose={close}><form className="hq-form sales-form" onSubmit={submit}><fieldset disabled={busy}>
 {e.kind==='opportunity'&&<><Field name="title" label="Engagement name" value={r?.title??a.company+' — implementation'} required/><div className="hq-form-grid">{r?<><input type="hidden" name="kind" value={r.kind}/><p>Engagement type: {r.kind}</p></>:<Pick name="kind" label="Engagement type" value="implementation" options={['blueprint','implementation','change']}/>}<Owner value={r?.owner??'Shawn'}/><Field name="due_on" label="Next action due" type="date" value={r?.due_on??today()} required/></div><Field name="next_action" label="Next action" value={r?.next_action??'Schedule discovery and confirm the decision-maker'} required/></>}
 {e.kind==='requirement'&&<><Field name="title" label="Deliverable / workflow" value={r?.title} required/><div className="hq-form-grid"><Pick name="priority" label="Priority" value={r?.priority??'must'} options={['must','should','later']}/><Field name="actor" label="User role / business owner" value={r?.actor} required/></div><Field name="steps" label="Trigger, steps, business rules and exceptions" value={r?.steps} rows={4} required/><Field name="expected" label="Expected result / measurable acceptance criterion" value={r?.expected} rows={4} required/></>}
 {e.kind==='proposal'&&<><div className="hq-form-grid"><Field name="title" label="Estimate title" value={r?.title??o!.title} required/><Field name="valid_until" label="Valid through" type="date" value={r?.valid_until??today()} required/></div><p className="hq-hint">Complete the legal seller, commercial terms and reviewed agreement text before issuing. Drafts can be saved while terms are being prepared. Customer signing is recorded from your signed document.</p>{DOC_FIELDS.map(([k,label])=><Field key={k} name={'doc_'+k} label={label} value={document[k]} rows={k==='legal'?6:3}/>)}
 <h3>Line items · USD</h3>{lines.map((l,i)=><div className="sales-line-editor" key={i+'-'+lines.length}><label>Description<input value={l.description} required onChange={ev=>editLine(i,'description',ev.target.value)}/></label><div className="hq-form-grid"><label>Service<select value={l.service} onChange={ev=>editLine(i,'service',ev.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Billing basis<select value={l.cadence} onChange={ev=>editLine(i,'cadence',ev.target.value)}>{CADENCES.map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></label><label>Quantity<input type="number" step="0.01" min="0.01" name={'line_'+i+'_quantity'} defaultValue={l.quantity_units/100} onBlur={ev=>editLine(i,'quantity_units',ev.target.value)} required/></label><label>Unit price / rate ($)<input type="number" step="0.01" min="0.01" name={'line_'+i+'_unit'} defaultValue={l.unit_cents/100} onBlur={ev=>editLine(i,'unit_cents',ev.target.value)} required/></label><label>Line discount ($)<input type="number" step="0.01" min="0" name={'line_'+i+'_discount'} defaultValue={l.discount_cents/100} onBlur={ev=>editLine(i,'discount_cents',ev.target.value)} required/></label></div><p>{money(lineAmount(l))}{l.cadence==='usage'?' per stated usage quantity':' · '+l.cadence.replaceAll('_',' ')}</p><button type="button" className="hq-link" disabled={lines.length===1} onClick={()=>setLines(ls=>ls.filter((_,j)=>j!==i))}>Remove line</button></div>)}<button type="button" className="secondary" disabled={lines.length>=50} onClick={()=>setLines(ls=>[...ls,{description:'',service:'software',cadence:'monthly',quantity_units:100,unit_cents:0,discount_cents:0}])}>Add line</button><div className="hq-form-grid"><Field name="tax_amount" label="One-time tax amount ($)" type="number" value={(r?.tax_cents??0)/100}/><Field name="deposit" label="Initial payment toward one-time total ($)" type="number" value={(r?.deposit_cents??0)/100}/></div><p className="hq-hint">The initial payment is part of the project total. Describe recurring taxes, usage allowances, caps and rates in the agreement terms.</p><label className="sales-checkbox"><input name="terms_reviewed" type="checkbox" defaultChecked={r?.terms_reviewed??false}/>I have reviewed the completed commercial and agreement terms for customer use.</label></>}
 {e.kind==='accept'&&<><p>Record approval of {r?.number}. Retain the signed copy in your controlled document system and enter its reference below. This action records acceptance; it does not sign on the customer's behalf.</p><Field name="accepted_name" label="Authorized signer name & title" required/><Field name="accepted_on" label="Customer acceptance date" type="date" value={today()} required/><Field name="evidence" label="Signed agreement reference / location" rows={3} required/></>}
 {e.kind==='project'&&<><div className="hq-form-grid"><Pick name="status" label={p?.project_kind==='blueprint'?'Delivery status (Live = delivered)':'Project status'} value={r?.status} options={['onboarding','building','testing','ready','live','on_hold']}/><Owner value={r?.owner}/><Field name="target_on" label="Target completion / launch" type="date" value={r?.target_on}/><Field name="release" label="Release / build being tested" value={r?.release}/></div><Field name="funding_note" label="Funding condition satisfied: payment reference or approved exception" value={r?.funding_note} rows={3}/><Field name="blocker" label="Blocker / customer dependency, owner and next review" rows={3} value={r?.blocker}/><h3>Customer acceptance</h3><p className="hq-hint">Complete after required tests pass. Changing the release clears earlier approval. Keep the actual customer approval with the project records.</p><Field name="approval_name" label="Customer approver name & title" value={r?.approval_name}/><Field name="approval_on" label="Approval date" type="date" value={r?.approval_on}/><Field name="approval_release" label="Release approved by customer" value={r?.approval_release}/><Field name="approval_evidence" label="Approval reference and accepted minor exceptions" value={r?.approval_evidence} rows={3}/></>}
 {e.kind==='delivery_task'&&<><h3>{r?.title}</h3><div className="hq-form-grid"><Owner value={r?.owner}/><Field name="due_on" label="Due date" type="date" value={r?.due_on} required/></div><Field name="evidence" label="Completion evidence / result / reason not applicable" value={r?.evidence} rows={4}/><label className="sales-checkbox"><input name="completed" type="checkbox" defaultChecked={r?.completed}/>Completed and reviewed</label></>}
 {e.kind==='beta_case'&&<><Field name="title" label="Test name" required/><Field name="actor" label="User role / device" required/><Field name="steps" label="Preconditions, data and test steps" rows={4} required/><Field name="expected" label="Expected result" rows={3} required/><label className="sales-checkbox"><input name="mandatory" type="checkbox" defaultChecked/>Required for launch</label></>}
 {e.kind==='beta_run'&&<><p>Testing release: <strong>{p?.release||'Set a project release before recording results.'}</strong></p><Pick name="result" label="Result" options={['passed','failed','blocked']}/><Field name="tester" label="Tester name and role" required/><Field name="actual" label="Actual result" rows={4} required/><Field name="evidence" label="Evidence, test data and device/browser" rows={4} required/></>}
 {e.kind==='defect'&&<><Field name="title" label="Issue title" value={r?.title} required/><Field name="detail" label="Reproduction steps, expected/actual behavior and customer impact" value={r?.detail} rows={4} required/><div className="hq-form-grid"><Pick name="severity" label="Severity" value={r?.severity??'medium'} options={['critical','high','medium','low']}/><Pick name="status" label="Status" value={r?.status??'open'} options={['open','in_progress','resolved','accepted']}/><Owner value={r?.owner??p?.owner}/><Field name="due_on" label="Correction due" type="date" value={r?.due_on??today()} required/></div><Field name="resolution" label="Fix or accepted workaround" value={r?.resolution} rows={3}/><Field name="retest" label="Retest evidence; for minor exceptions, customer acknowledgement and correction date" value={r?.retest} rows={3}/><p className="hq-hint">Critical/high issues must be fixed and retested. Only medium/low issues may be accepted with customer acknowledgement.</p></>}
 {(error||localError)&&<p className="error" role="alert">{localError||error}</p>}<div className="sales-form-footer"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':e.kind==='accept'?'Record acceptance':'Save'}</button></div></fieldset></form></HQDialog>;
}
