'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Users } from 'lucide-react';
import { manageUser } from '@/app/hq/admin/actions';
import type { HQTeam } from '@/lib/hq-admin';
import type { Role } from '@/lib/core';

export default function TeamAdmin({team,role,currentUserId}:{team:HQTeam;role:Role;currentUserId:string}){
 const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const choices=<><option value="member">Member — manage daily work</option><option value="read_only">Read only — view records</option>{role==='owner'&&<option value="administrator">Administrator — manage users and connections</option>}</>;
 async function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setMessage('');try{const r=await manageUser(action,new FormData(form));if(!r.ok)setError(r.error||'Unable to save.');else{setMessage(r.message||'Saved.');if(action==='add')form.reset();router.refresh();}}catch{setError('Unable to save. Please retry.');}finally{setBusy(false);}}
 return <div className="hq-shell"><main className="hq-admin-main"><a href="/hq" className="hq-link"><ArrowLeft size={17}/>Back to WorkForge HQ</a><div className="hq-heading hq-spaced"><div><p className="hq-eyebrow">WORKFORGE HQ</p><h1>User administration</h1><p>Add your team and control access to internal operations.</p></div><Users size={32}/></div>
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="hq-toast" role="status">{message}</p>}
 <section className="hq-panel"><header><h2>Add a user</h2></header><form className="hq-form" onSubmit={e=>submit(e,'add')}><fieldset disabled={busy}><div className="hq-form-grid"><label>Email address<input name="email" type="email" required maxLength={254} placeholder="name@yourcompany.com"/></label><label>Role<select name="role" defaultValue="member">{choices}</select></label></div><p className="hq-hint">Use their exact Google sign-in email. Access is ready immediately for existing users; new users have 30 days to sign in and activate it.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Add user'}</button></fieldset></form><div className="hq-panel-note"><p>After adding access, share the HQ sign-in link with your teammate. Adding a user does not send an email.</p><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(new URL('/hq',window.location.origin).href);setMessage('HQ sign-in link copied.');}catch{setError('Copy the WorkForge HQ address from your browser.');}}}>Copy sign-in link</button></div></section>
 <section className="hq-panel hq-spaced"><header><h2>Team members</h2><span>{team.members.filter(m=>m.is_active).length} active</span></header>{team.members.map(m=>{const protectedUser=m.user_id===currentUserId||m.role==='owner'||(m.role==='administrator'&&role!=='owner');return <form key={`${m.user_id}-${m.role}-${m.is_active}`} className="hq-admin-row" onSubmit={e=>submit(e,'update')}><div><strong>{m.email}</strong><small>{m.user_id===currentUserId?'You · ':''}{m.role.replace('_',' ')} · {m.is_active?'Active':'Inactive'}</small></div><input type="hidden" name="user_id" value={m.user_id}/>{protectedUser?<span className="hq-badge">Protected account</span>:<fieldset disabled={busy}><label>Role<select name="role" defaultValue={m.role}>{choices}</select></label><label>Access<select name="is_active" defaultValue={String(m.is_active)}><option value="true">Active</option><option value="false">Inactive</option></select></label><button className="secondary" disabled={busy}>Save access</button></fieldset>}</form>;})}<p className="hq-panel-note">Deactivation removes HQ access on the next request. The owner account and your own access are protected. Field OS access is managed separately.</p></section>
 <section className="hq-panel hq-spaced"><header><h2>Pending access</h2></header>{team.invitations.map(i=><form key={i.id} className="hq-admin-row" onSubmit={e=>submit(e,'revoke_invitation')}><input type="hidden" name="id" value={i.id}/><div><strong>{i.email}</strong><small>{i.role.replace('_',' ')} · {Date.parse(i.expires_at)<Date.now()?'Expired':'Expires'} {new Date(i.expires_at).toLocaleDateString('en-US',{timeZone:'America/Denver'})}</small></div>{(role==='owner'||!['owner','administrator'].includes(i.role))&&<button className="secondary" disabled={busy}>Revoke access</button>}</form>)}{!team.invitations.length&&<p className="hq-panel-note">No pending users. Add someone above to reserve access.</p>}</section>
 </main></div>;
}
