-- Synthetic identities and AI responses; no provider call or real customer mutation.
begin;
create temporary table ai_results(check_name text,passed boolean);
do $test$
declare u uuid:=gen_random_uuid();r uuid:=gen_random_uuid();w uuid:=gen_random_uuid();w2 uuid:=gen_random_uuid();o uuid;other_o uuid;product uuid;run jsonb;did uuid;secret uuid;review jsonb;stamp timestamptz;blocked boolean;n integer;initial_count integer;old_scope text;
begin
 insert into auth.users(id,email,email_confirmed_at) values(u,'ai-qa-owner@example.com',now()),(r,'ai-qa-reader@example.com',now());
 insert into public.workspaces(id,name,model,is_demo) values(w,'AI QA','field',true),(w2,'Other AI QA','field',true);
 insert into public.workspace_memberships(workspace_id,user_id,role) values(w,u,'owner'),(w,r,'read_only');
 perform set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 o:=public.create_field_lead(w,'AI QA customer','ai-qa@example.com','','QA address','QA AI workflow','Mulch beds');
 insert into public.field_profiles(workspace_id,work_order_id,goals,measurements,operations_notes) values(w,o,'Refresh mulch','3 cubic yards','Keep the side gate closed.');
 insert into public.pricebook_items(workspace_id,name,unit,material_cents,labor_cents,taxable) values(w,'Mulch','cubic yard',4000,2000,true) returning id into product;
 -- Old deployments must retain Astra accounting even after the table defaults change.
 run:=public.reserve_field_ai(w,o,'consultation');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 if run->>'model'<>'openai/gpt-6-astra' then raise exception 'FAIL: legacy model changed';end if;
 perform public.finish_field_ai(did,secret,'{"summary":"Legacy draft"}',null,3000,1000,null);
 if not exists(select 1 from public.ai_drafts where id=did and model='openai/gpt-6-astra' and estimated_cost_cents=8 and input_rate_usd_per_million=10 and output_rate_usd_per_million=50) then raise exception 'FAIL: legacy rates changed';end if;
 blocked:=false;begin perform public.reserve_field_ai(w,o,'consultation','unknown/model');exception when others then blocked:=sqlerrm='Unsupported AI model.';end;
 if not blocked then raise exception 'FAIL: unsupported model was not rejected';end if;
 reset role;insert into ai_results values('Legacy deployments retain Astra rates; unsupported models are rejected',true);set local role authenticated;
 run:=public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 if run->>'model'<>'openai/gpt-5.6-luna' then raise exception 'FAIL: wrong generation model reserved';end if;
 if not exists(select 1 from public.ai_drafts where id=did and status='pending' and budget_cost_cents=100) then raise exception 'FAIL: no reservation before generation';end if;
 blocked:=false;begin perform public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: concurrent workspace run allowed';end if;
 blocked:=false;begin perform public.finish_field_ai(did,gen_random_uuid(),'{}',null,100,50,null);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: forged execution token accepted';end if;
 blocked:=false;begin update public.ai_drafts set status='ready' where id=did;exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'FAIL: direct draft mutation allowed';end if;
 perform public.finish_field_ai(did,secret,'{"summary":"Refresh three cubic yards of mulch."}',null,100,50,null);
 if not exists(select 1 from public.ai_drafts where id=did and status='ready' and input_tokens=100 and output_tokens=50 and estimated_cost_cents=0.008 and model='openai/gpt-5.6-luna' and input_rate_usd_per_million=0.20 and output_rate_usd_per_million=1.20 and budget_cost_cents=1) then raise exception 'FAIL: response and usage did not persist';end if;
 perform public.apply_field_ai(did,'{"summary":"Reviewed: refresh three cubic yards of mulch."}');
 perform public.apply_field_ai(did,'{"summary":"Duplicate must not overwrite."}');
 if not exists(select 1 from public.field_profiles where work_order_id=o and goals='Refresh mulch' and measurements='3 cubic yards' and consultation_summary='Reviewed: refresh three cubic yards of mulch.' and not consultation_complete) then raise exception 'FAIL: summary replaced source notes or review status';end if;
 reset role;insert into ai_results values('Generation reservation, concurrency limit, execution token and stored usage',true),('Reviewed summary preserves site notes; repeated apply is idempotent',true);set local role authenticated;
 run:=public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 perform public.finish_field_ai(did,secret,'{"summary":"A stale summary."}',null,100,50,null);
 update public.field_profiles set goals='Keep existing shrubs' where work_order_id=o;
 blocked:=false;begin perform public.apply_field_ai(did,'{"summary":"Stale summary must not save."}');exception when others then blocked:=true;end;
 if not blocked or exists(select 1 from public.field_profiles where work_order_id=o and consultation_summary='Stale summary must not save.') then raise exception 'FAIL: stale profile draft applied';end if;
 run:=public.reserve_field_ai(w,o,'estimate','openai/gpt-5.6-luna');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 perform public.finish_field_ai(did,secret,'{"scope":"Install mulch","items":[]}',null,100,50,null);
 review:=jsonb_build_object('scope','Install mulch','items',jsonb_build_array(jsonb_build_object('product_id',product,'quantity',3,'description','Mulch installation','unit_price_cents',1,'material_cents',1)));
 perform public.apply_field_ai(did,review);
 if not exists(select 1 from public.work_orders where id=o and stage='lead' and estimate_lines->0->>'unit_price_cents'='10000' and material_cost_cents=12000 and labor_cost_cents=6000) then raise exception 'FAIL: AI prices bypassed pricebook or advanced stage';end if;
 run:=public.reserve_field_ai(w,o,'estimate','openai/gpt-5.6-luna');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 perform public.finish_field_ai(did,secret,'{"scope":"Install mulch","items":[]}',null,100,50,null);
 update public.pricebook_items set material_cents=5000 where id=product;
 blocked:=false;begin perform public.apply_field_ai(did,review);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: changed pricebook was accepted';end if;
 reset role;insert into ai_results values('Stale consultation and changed pricebook reject apply',true),('Estimate pricing uses database pricebook costs and margin; no automatic approval',true);set local role authenticated;
 -- Take the actual saved estimate through the existing approval workflow.
 insert into public.appointments(workspace_id,work_order_id,title,starts_at,ends_at) values(w,o,'QA consultation',now(),now()+interval '1 hour');
 perform public.advance_field_order(w,o,'lead','appointment');update public.field_profiles set consultation_complete=true where work_order_id=o;
 select updated_at into stamp from public.work_orders where id=o;
 perform public.save_and_prepare_field_estimate(w,o,stamp,(select estimate_lines from public.work_orders where id=o),'Install mulch',40,0,0,25,'QA terms',null);
 perform public.advance_field_order(w,o,'estimated','approved','AI QA customer');
 blocked:=false;begin perform public.reserve_field_ai(w,o,'estimate','openai/gpt-5.6-luna');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: approved estimate allowed drafting';end if;
 insert into public.tasks(workspace_id,work_order_id,title) values(w,o,'Check side gate');
 run:=public.reserve_field_ai(w,o,'handoff','openai/gpt-5.6-luna');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 perform public.finish_field_ai(did,secret,'{"notes":"Use approved mulch scope","tasks":[]}',null,100,50,null);
 select count(*) into initial_count from public.tasks where work_order_id=o;
 blocked:=false;begin perform public.apply_field_ai(did,'{"notes":"Must roll back","tasks":[""]}');exception when others then blocked:=true;end;
 if not blocked or exists(select 1 from public.field_profiles where work_order_id=o and operations_notes like '%Must roll back%') then raise exception 'FAIL: invalid handoff partially applied';end if;
 review:='{"notes":"Use approved mulch scope. Confirm the delivery before mobilizing.","tasks":["Check side gate","Verify mulch delivery","Final customer walkthrough"]}';
 perform public.apply_field_ai(did,review);perform public.apply_field_ai(did,review);
 if (select count(*) from public.tasks where work_order_id=o)<>initial_count+2 then raise exception 'FAIL: handoff duplicated tasks';end if;
 if not exists(select 1 from public.field_profiles where work_order_id=o and operations_notes like 'Keep the side gate closed.%Reviewed production handoff:%') or not exists(select 1 from public.work_orders where id=o and stage='approved' and assigned_partner_id is null) or exists(select 1 from public.purchase_orders where work_order_id=o) then raise exception 'FAIL: handoff changed scope, scheduling or purchasing';end if;
 if (select count(*) from public.audit_events where work_order_id=o and action='Reviewed AI handoff draft applied')<>1 then raise exception 'FAIL: handoff audit count';end if;
 reset role;insert into ai_results values('Approved estimate lock and production handoff prerequisites',true),('Handoff applies atomically, appends notes and adds unique tasks exactly once',true);set local role authenticated;
 -- Requesters outside the workspace and read-only accounts cannot run or apply drafts.
 blocked:=false;begin perform public.reserve_field_ai(w2,o,'consultation','openai/gpt-5.6-luna');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: cross-workspace generation';end if;
 perform set_config('request.jwt.claims',json_build_object('sub',r,'role','authenticated')::text,true);
 if not exists(select 1 from public.ai_drafts where id=did) then raise exception 'FAIL: reader cannot view a permitted draft';end if;
 blocked:=false;begin perform public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: reader generated a draft';end if;
 blocked:=false;begin perform public.apply_field_ai(did,review);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: reader applied a draft';end if;
 perform set_config('request.jwt.claims',json_build_object('sub',gen_random_uuid(),'role','authenticated')::text,true);
 if exists(select 1 from public.ai_drafts where id=did) then raise exception 'FAIL: unauthorized draft visible';end if;
 reset role;insert into ai_results values('Workspace isolation and read-only viewing with no generation/apply access',true);
 -- Unknown usage stays reserved; both daily and monthly limits are enforced.
 perform set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 run:=public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');did:=(run->>'id')::uuid;secret:=(run->>'execution_token')::uuid;
 perform public.finish_field_ai(did,secret,null,null,null,null,'Provider unavailable');
 if not exists(select 1 from public.ai_drafts where id=did and status='failed' and budget_cost_cents=100 and result is null) then raise exception 'FAIL: failure did not retain conservative reservation';end if;
 reset role;
 update public.ai_drafts set budget_cost_cents=1000 where id=did;
 set local role authenticated;blocked:=false;begin perform public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: monthly budget not enforced';end if;
 reset role;update public.ai_drafts set budget_cost_cents=1 where id=did;
 insert into public.ai_drafts(workspace_id,work_order_id,requested_by,kind,status,input_snapshot,budget_cost_cents) select w,o,u,'consultation','failed','{}',0 from generate_series(1,20);
 set local role authenticated;blocked:=false;begin perform public.reserve_field_ai(w,o,'consultation','openai/gpt-5.6-luna');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: daily limit not enforced';end if;
 reset role;insert into ai_results values('Failed generation persistence, conservative cost reservation and budget/rate limits',true);
end $test$;
select * from ai_results;
rollback;
