begin;
create temporary table wf_test_results(check_name text,passed boolean);
do $test$
declare
 u1 uuid:=gen_random_uuid(); u2 uuid:=gen_random_uuid(); reader uuid:=gen_random_uuid();
 w1 uuid:=gen_random_uuid(); w2 uuid:=gen_random_uuid(); oid uuid; crew uuid; n integer; blocked boolean;
begin
 insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data)
 values(u1,'qa-owner@workforge.example',now(),'{}','{}'),(u2,'qa-other@workforge.example',now(),'{}','{}'),(reader,'qa-reader@workforge.example',now(),'{}','{"role":"owner"}');
 insert into public.workspaces(id,name,model,is_demo) values(w1,'QA workspace one','field',true),(w2,'QA workspace two','field',true);
 insert into public.workspace_memberships(workspace_id,user_id,role) values(w1,u1,'owner'),(w2,u2,'owner'),(w1,reader,'read_only');
 perform set_config('request.jwt.claims',json_build_object('sub',u1,'role','authenticated')::text,true);
 set local role authenticated;
 select count(*) into n from public.workspaces;
 if n<>1 then raise exception 'FAIL: workspace isolation'; end if;
 oid:=public.create_field_lead(w1,'QA customer','qa@example.com','','QA address','QA job','QA scope');
 blocked:=false;
 begin perform public.create_field_lead(w2,'QA customer','','','','Forbidden',''); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: cross-workspace write allowed'; end if;
 blocked:=false;
 begin update public.work_orders set stage='invoice_ready' where id=oid; exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'FAIL: direct stage update'; end if;
 blocked:=false;
 begin perform public.advance_field_order(w1,oid,'lead','appointment',''); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: consultation requirement'; end if;
 insert into public.appointments(workspace_id,work_order_id,title,starts_at,ends_at) values(w1,oid,'QA',now()+interval '1 day',now()+interval '1 day 1 hour');
 perform public.advance_field_order(w1,oid,'lead','appointment','');
 perform public.save_field_budget(w1,oid,60000,30000,40,'QA scope');
 perform public.advance_field_order(w1,oid,'appointment','estimated','');
 if not exists(select 1 from public.estimate_versions where work_order_id=oid and price_cents=150000) then raise exception 'FAIL: margin calculation'; end if;
 perform public.save_field_budget(w1,oid,60000,60000,40,'QA revised scope');
 select count(*) into n from public.estimate_versions where work_order_id=oid;
 if n<>2 then raise exception 'FAIL: revision history'; end if;
 perform public.advance_field_order(w1,oid,'estimated','approved','QA customer');
 blocked:=false;
 begin perform public.save_field_budget(w1,oid,1,1,40,'tampered'); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: accepted estimate mutation'; end if;
 insert into public.partners(workspace_id,name,kind) values(w1,'QA crew','crew') returning id into crew;
 perform public.schedule_field_order(w1,oid,now()+interval '1 day',crew);
 perform public.advance_field_order(w1,oid,'approved','scheduled','');
 perform public.advance_field_order(w1,oid,'scheduled','in_progress','');
 insert into public.tasks(workspace_id,work_order_id,title) values(w1,oid,'QA final check');
 blocked:=false;
 begin perform public.advance_field_order(w1,oid,'in_progress','completed',''); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: open completion task'; end if;
 update public.tasks set completed=true where work_order_id=oid;
 blocked:=false;
 begin perform public.advance_field_order(w1,oid,'in_progress','completed',''); exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: walkthrough requirement';end if;
 insert into public.field_profiles(workspace_id,work_order_id,walkthrough_complete) values(w1,oid,true);
 perform public.advance_field_order(w1,oid,'in_progress','completed','');
 perform public.advance_field_order(w1,oid,'completed','invoice_ready','');
 perform public.advance_field_order(w1,oid,'completed','invoice_ready','');
 select count(*) into n from public.invoice_handoffs where work_order_id=oid;
 if n<>1 then raise exception 'FAIL: duplicate handoff'; end if;
 if not exists(select 1 from public.invoice_handoffs where work_order_id=oid and status='prepared' and amount_cents=200000) then raise exception 'FAIL: handoff value'; end if;
 reset role;
 insert into wf_test_results values('Owner access, tenant isolation, protected stages, consultation, margin, revisions, approval lock, schedule, task completion and idempotent invoice handoff',true);
 perform set_config('request.jwt.claims',json_build_object('sub',reader,'role','authenticated','user_metadata',json_build_object('role','owner'))::text,true);
 set local role authenticated;
 if not exists(select 1 from public.work_orders where id=oid) then raise exception 'FAIL: reader cannot read'; end if;
 blocked:=false;
 begin perform public.create_field_lead(w1,'No','','','','Forbidden',''); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: reader permission or metadata privilege escalation'; end if;
 reset role;
 insert into wf_test_results values('Read-only access and user-metadata privilege escalation denial',true);
 update public.workspace_memberships set is_active=false where user_id=u1;
 perform set_config('request.jwt.claims',json_build_object('sub',u1,'role','authenticated')::text,true);
 set local role authenticated;
 select count(*) into n from public.work_orders;
 if n<>0 then raise exception 'FAIL: revoked membership retained access'; end if;
 reset role;
 insert into wf_test_results values('Revoked membership immediately loses workspace access',true);
end $test$;
select * from wf_test_results;
rollback;
