-- Fictional users and records exist only inside this rolled-back transaction.
begin;
create temporary table demo_results(check_name text,passed boolean);
do $test$
declare u uuid:=gen_random_uuid(); r uuid:=gen_random_uuid(); w uuid:=gen_random_uuid(); w2 uuid:=gen_random_uuid(); live_w uuid:=gen_random_uuid(); o uuid; copy_id uuid; stamp timestamptz; crew uuid; vendor uuid; sub uuid; assignment uuid; lines jsonb; blocked boolean; original_revision uuid;
begin
 insert into auth.users(id,email,email_confirmed_at) values(u,'demo-qa-owner@example.com',now()),(r,'demo-qa-reader@example.com',now());
 insert into public.workspaces(id,name,model,is_demo) values(w,'Demo workflow QA','field',true),(w2,'Other tenant QA','field',true),(live_w,'Non-demo QA','field',false);
 insert into public.workspace_memberships(workspace_id,user_id,role) values(w,u,'owner'),(w,r,'read_only'),(live_w,u,'owner');
 perform set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true);set local role authenticated;
 o:=public.create_field_lead(w,'Fictional QA customer','demo-qa@example.com','','QA address','QA full workflow','Initial scope');
 insert into public.field_profiles(workspace_id,work_order_id,source,operations_owner) values(w,o,'LSAs','Neil');
 select updated_at into stamp from public.work_orders where id=o;
 lines:='[{"id":"item-1","product_id":null,"name":"QA landscape installation","description":"Demo scope","quantity":2,"unit":"each","material_cents":10000,"labor_cents":20000,"unit_price_cents":50000,"taxable":false}]';
 perform public.save_and_prepare_field_estimate(w,o,stamp,lines,'Draft scope',40,0,0,25,'Demo terms',null);
 if not exists(select 1 from public.work_orders where id=o and stage='lead' and jsonb_array_length(estimate_lines)=1) or exists(select 1 from public.estimate_versions where work_order_id=o) then raise exception 'FAIL: intake draft did not remain editable';end if;
 insert into public.appointments(workspace_id,work_order_id,title,starts_at,ends_at) values(w,o,'QA consultation',now(),now()+interval '1 hour');
 perform public.advance_field_order(w,o,'lead','appointment');
 select updated_at into stamp from public.work_orders where id=o;
 blocked:=false;begin perform public.save_and_prepare_field_estimate(w,o,stamp,lines,'Must roll back',40,0,0,25,'Demo terms',null);exception when others then blocked:=true;end;
 if not blocked or exists(select 1 from public.work_orders where id=o and description='Must roll back') then raise exception 'FAIL: unfinished consultation saved a proposal or partial changes';end if;
 update public.field_profiles set consultation_complete=true where work_order_id=o;
 blocked:=false;begin perform public.save_and_prepare_field_estimate(w,o,stamp-interval '1 second',lines,'Stale proposal',40,0,0,25,'Demo terms',null);exception when others then blocked:=true;end;
 if not blocked or exists(select 1 from public.estimate_versions where work_order_id=o) then raise exception 'FAIL: stale proposal accepted';end if;
 perform public.save_and_prepare_field_estimate(w,o,stamp,lines,'Proposal scope',40,0,0,25,'Demo terms',null);
 if not exists(select 1 from public.work_orders where id=o and stage='estimated') or (select count(*) from public.estimate_versions where work_order_id=o)<>1 then raise exception 'FAIL: save and prepare did not create proposal';end if;
 select id into original_revision from public.estimate_versions where work_order_id=o;
 select updated_at into stamp from public.work_orders where id=o;
 perform public.save_and_prepare_field_estimate(w,o,stamp,lines,'Revised proposal scope',40,0,0,25,'Demo terms',null);
 if (select count(*) from public.estimate_versions where work_order_id=o)<>2 or not exists(select 1 from public.estimate_versions where id=original_revision and scope='Proposal scope') then raise exception 'FAIL: revision history changed';end if;
 insert into public.partners(workspace_id,name,kind) values(w,'QA internal crew','crew') returning id into crew;
 insert into public.partners(workspace_id,name,kind) values(w,'QA supplier','vendor') returning id into vendor;
 insert into public.partners(workspace_id,name,kind) values(w,'QA subcontractor','subcontractor') returning id into sub;
 insert into public.purchase_orders(workspace_id,work_order_id,partner_id,order_kind,description,cost_cents) values(w,o,crew,'internal','Internal production',40000) returning id into assignment;
 insert into public.purchase_orders(workspace_id,work_order_id,partner_id,order_kind,description,cost_cents) values(w,o,vendor,'materials','Materials',20000),(w,o,sub,'subcontract','Specialist work',10000);
 blocked:=false;begin insert into public.purchase_orders(workspace_id,work_order_id,partner_id,order_kind,description,cost_cents) values(w,o,crew,'subcontract','Wrong category',100);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: internal crew accepted as subcontractor';end if;
 blocked:=false;begin update public.purchase_orders set status='ordered' where id=assignment;exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: internal work assigned before approval';end if;
 perform public.advance_field_order(w,o,'estimated','approved','Fictional QA customer');
 update public.purchase_orders set status='ordered' where work_order_id=o;
 copy_id:=public.copy_demo_field_job(w,o);
 if not exists(select 1 from public.work_orders a join public.work_orders b on a.contact_id=b.contact_id where a.id=o and a.stage='approved' and b.id=copy_id and b.stage='lead' and b.estimate_lines=a.estimate_lines and b.assigned_partner_id is null) then raise exception 'FAIL: editable demo copy';end if;
 if exists(select 1 from public.estimate_versions where work_order_id=copy_id) or exists(select 1 from public.purchase_orders where work_order_id=copy_id) or not exists(select 1 from public.field_profiles where work_order_id=copy_id and source='LSAs' and not consultation_complete and not walkthrough_complete and not costs_reviewed and operations_owner='') then raise exception 'FAIL: copy inherited workflow completion or commitments';end if;
 blocked:=false;begin perform public.save_and_prepare_field_estimate(w,o,stamp,lines,'Tamper approved scope',40,0,0,25,'Demo terms',null);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: approved source unlocked';end if;
 blocked:=false;begin perform public.copy_demo_field_job(w2,o);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: cross-tenant copy';end if;
 blocked:=false;begin perform public.copy_demo_field_job(live_w,o);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: non-demo copy';end if;
 perform public.schedule_field_order(w,o,now()+interval '1 day',crew);
 perform public.advance_field_order(w,o,'approved','scheduled');perform public.advance_field_order(w,o,'scheduled','in_progress');
 insert into public.tasks(workspace_id,work_order_id,title) values(w,o,'QA final punch list');
 update public.field_profiles set walkthrough_complete=true where work_order_id=o;
 blocked:=false;begin perform public.advance_field_order(w,o,'in_progress','completed');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: unfinished punch list';end if;
 update public.tasks set completed=true where work_order_id=o;
 update public.purchase_orders set status='received' where work_order_id=o;
 insert into public.financial_records(workspace_id,work_order_id,kind,category,amount_cents,reference,occurred_on) values(w,o,'expense','labor',70000,'DEMO-COST',current_date),(w,o,'receipt','deposit',25000,'DEMO-DEPOSIT',current_date),(w,o,'receipt','final',75000,'DEMO-FINAL',current_date);
 update public.field_profiles set costs_reviewed=true where work_order_id=o;
 perform public.advance_field_order(w,o,'in_progress','completed');perform public.advance_field_order(w,o,'completed','invoice_ready');
 if not exists(select 1 from public.invoice_handoffs where work_order_id=o and amount_cents=100000) or (select sum(amount_cents) from public.financial_records where work_order_id=o and kind='receipt' and not voided)<>100000 then raise exception 'FAIL: final handoff or recorded settlement';end if;
 reset role;insert into demo_results values('Intake draft, atomic proposal, consultation and stale-save gates, revision history',true),('Three assignment types, category enforcement and approval gate',true),('Editable copy preserves approved source and starts a fresh workflow',true),('Scheduling, punch list, assignments, expenses, receipts and invoice handoff',true);
 perform set_config('request.jwt.claims',json_build_object('sub',r,'role','authenticated')::text,true);set local role authenticated;
 blocked:=false;begin perform public.copy_demo_field_job(w,o);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: read-only copy';end if;
 blocked:=false;begin perform public.save_and_prepare_field_estimate(w,copy_id,stamp,lines,'Reader edit',40,0,0,25,'Terms',null);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: read-only proposal save';end if;
 reset role;insert into demo_results values('Read-only, non-demo and cross-workspace controls',true);
end $test$;
select * from demo_results;
rollback;
