import test from 'node:test';
import assert from 'node:assert/strict';
import {quoteTotals,jobFinancials,lineAmount} from '../lib/field.ts';
const item={id:'one',product_id:null,name:'Service',description:'',unit:'sq ft',quantity:1.5,material_cents:125,labor_cents:75,unit_price_cents:335,taxable:true};
test('fractional quantities, discount, tax and deposit use exact cent rounding',()=>{const q=quoteTotals([item],5,8.25,50);assert.equal(q.subtotal_cents,503);assert.equal(q.labor_cost_cents,113);assert.equal(q.material_cost_cents,188);assert.equal(q.discount_cents,25);assert.equal(q.tax_cents,39);assert.equal(q.price_cents,517);assert.equal(q.deposit_cents,259);assert.equal(lineAmount(1.5,335),503);});
test('only taxable lines attract tax, and profit excludes sales tax',()=>{const q=quoteTotals([item,{...item,id:'two',quantity:1,unit_price_cents:10000,taxable:false}],0,10,0);assert.equal(q.tax_cents,50);assert.equal(q.profit_cents,q.subtotal_cents-q.labor_cost_cents-q.material_cost_cents);});
test('discounts reduce actual gross margin instead of changing the cost',()=>{const q=quoteTotals([{...item,quantity:1,material_cents:30000,labor_cents:30000,unit_price_cents:100000}],10,0,25);assert.ok(Math.abs(q.margin_percent-100/3)<1e-10);assert.equal(q.profit_cents,30000);assert.equal(q.deposit_cents,22500);});
test('invalid percentages, quantity precision and duplicate line IDs are rejected',()=>{assert.throws(()=>quoteTotals([item],100));assert.throws(()=>quoteTotals([item],0,31));assert.throws(()=>quoteTotals([{...item,quantity:1.0001}]));assert.throws(()=>quoteTotals([item,item]));assert.throws(()=>quoteTotals([{...item,unit_price_cents:-1}]));});
test('missing costs stay incomplete, drafts are not committed, and voids are excluded',()=>{const o={id:'job',contact_id:'c'};const d={workspace:{id:'w'},contacts:[],profiles:[],estimates:[{work_order_id:'job',status:'approved',price_cents:11000,tax_cents:1000}],purchases:[{work_order_id:'job',cost_cents:5000,status:'planned'},{work_order_id:'job',cost_cents:3000,status:'ordered'}],financials:[{work_order_id:'job',kind:'expense',amount_cents:2000,voided:false},{work_order_id:'job',kind:'expense',amount_cents:9000,voided:true},{work_order_id:'job',kind:'receipt',category:'deposit',amount_cents:3000,voided:false}]};const f=jobFinancials(d,o);assert.equal(f.profit,null);assert.equal(f.committed,3000);assert.equal(f.expenses,2000);assert.equal(f.balance,8000);d.profiles=[{work_order_id:'job',costs_reviewed:true}];assert.equal(jobFinancials(d,o).profit,8000);});
