begin;
create temporary table field_results(check_name text,passed boolean);
do $test$
declare u uuid:=gen_random_uuid(); r uuid:=gen_random_uuid(); w uuid:=gen_random_uuid(); w2 uuid:=gen_random_uuid(); o uuid; other_item uuid:=gen_random_uuid(); cid uuid; old_stamp timestamptz; lines jsonb; q public.estimate_versions; supplier uuid; crew uuid; fid uuid; blocked boolean;
begin
 insert into auth.users(id,email,email_confirmed_at) values(u,'field-owner@example.com',now()),(r,'field-reader@example.com',now());
 insert into public.workspaces(id,name,model,is_demo) values(w,'Field QA transaction','field',true),(w2,'Isolated QA transaction','field',true);
 insert into public.workspace_memberships(workspace_id,user_id,role) values(w,u,'owner'),(w,r,'read_only');
 insert into public.pricebook_items(id,workspace_id,name) values(other_item,w2,'Private item');
 perform set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true);
 set local role authenticated;
 o:=public.create_field_lead(w,'QA customer','qa@example.com','','QA property','QA field job','Original scope');
 select contact_id into cid from public.work_orders where id=o;
 perform public.create_customer_job(w,cid,'Second property job','Second scope');
 if (select count(*) from public.contacts where workspace_id=w)<>1 then raise exception 'FAIL: duplicate customer';end if;
 insert into public.field_profiles(workspace_id,work_order_id,service,job_address,sales_status,lost_reason) values(w,o,'Test service','Job-specific address','lost','QA reason');
 insert into public.appointments(workspace_id,work_order_id,title,starts_at,ends_at) values(w,o,'Consultation',now(),now()+interval '1 hour');
 blocked:=false;begin perform public.advance_field_order(w,o,'lead','appointment');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: lost lead advanced';end if;
 update public.field_profiles set sales_status='open' where work_order_id=o;
 perform public.advance_field_order(w,o,'lead','appointment');
 select updated_at into old_stamp from public.work_orders where id=o;
 lines:='[{"id":"line1","product_id":null,"name":"Test service","description":"Scope detail","quantity":1.5,"unit":"sq ft","material_cents":125,"labor_cents":75,"unit_price_cents":335,"taxable":true}]'::jsonb;
 blocked:=false;begin perform public.save_field_estimate(w,o,old_stamp-interval '1 second',lines,'Scope',40,5,8.25,50,'Terms',null);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: stale revision accepted';end if;
 blocked:=false;begin perform public.save_field_estimate(w,o,old_stamp,jsonb_set(lines,'{0,product_id}',to_jsonb(other_item::text)),'Scope',40,5,8.25,50,'Terms',null);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: foreign pricebook reference';end if;
 perform public.save_field_estimate(w,o,old_stamp,lines,'Scope',40,5,8.25,50,'Terms',null);
 perform public.advance_field_order(w,o,'appointment','estimated');
 select * into q from public.estimate_versions where work_order_id=o order by version desc limit 1;
 if (q.price_cents,q.deposit_cents,q.tax_cents,q.labor_cost_cents,q.material_cost_cents) is distinct from (517::bigint,259::bigint,39::bigint,113::bigint,188::bigint) then raise exception 'FAIL: itemized totals %',row_to_json(q);end if;
 if q.customer_snapshot->>'address'<>'Job-specific address' then raise exception 'FAIL: property snapshot';end if;
 select updated_at into old_stamp from public.work_orders where id=o;
 perform public.save_field_estimate(w,o,old_stamp,lines,'Revised scope',40,0,0,20,'Revised terms',null);
 if (select count(*) from public.estimate_versions where work_order_id=o)<>2 then raise exception 'FAIL: revision retention';end if;
 if not exists(select 1 from public.estimate_versions where id=q.id and price_cents=517 and terms='Terms') then raise exception 'FAIL: original revision overwritten';end if;
 blocked:=false;begin perform public.save_field_budget(w,o,0,100,40,'Invalid legacy edit');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: itemized budget overwritten by legacy RPC';end if;
 insert into public.partners(workspace_id,name,kind) values(w,'QA supplier','vendor') returning id into supplier;
 insert into public.purchase_orders(workspace_id,work_order_id,partner_id,description,cost_cents) values(w,o,supplier,'QA materials',188);
 blocked:=false;begin update public.purchase_orders set status='ordered' where work_order_id=o;exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: order issued without approval';end if;
 perform public.advance_field_order(w,o,'estimated','approved','Fictional QA customer');
 -- Issuance is permitted before deposit collection.
 update public.purchase_orders set status='ordered' where work_order_id=o;
 blocked:=false;begin perform public.save_field_estimate(w,o,old_stamp,lines,'Tamper',40,0,0,0,'',null);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: accepted estimate changed';end if;
 update public.contacts set name='Updated customer name' where id=cid;
 if exists(select 1 from public.estimate_versions where work_order_id=o and customer_snapshot->>'name'='Updated customer name') then raise exception 'FAIL: historical customer snapshot changed';end if;
 insert into public.partners(workspace_id,name,kind,status) values(w,'QA crew','crew','hold') returning id into crew;
 blocked:=false;begin perform public.schedule_field_order(w,o,now()+interval '1 day',crew);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: held crew scheduled';end if;
 update public.partners set status='active' where id=crew;
 perform public.schedule_field_order(w,o,now()+interval '1 day',crew);
 perform public.advance_field_order(w,o,'approved','scheduled');perform public.advance_field_order(w,o,'scheduled','in_progress');
 blocked:=false;begin perform public.advance_field_order(w,o,'in_progress','completed');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: missing walkthrough';end if;
 update public.field_profiles set walkthrough_complete=true,costs_reviewed=true where work_order_id=o;
 insert into public.financial_records(workspace_id,work_order_id,kind,category,amount_cents,reference,occurred_on) values(w,o,'expense','materials',188,'BILL-1',current_date) returning id into fid;
 if exists(select 1 from public.field_profiles where work_order_id=o and costs_reviewed) then raise exception 'FAIL: added expense did not reopen review';end if;
 blocked:=false;begin insert into public.financial_records(workspace_id,work_order_id,kind,category,amount_cents,reference,occurred_on) values(w,o,'expense','materials',188,'BILL-1',current_date);exception when unique_violation then blocked:=true;end;
 if not blocked then raise exception 'FAIL: duplicate expense reference';end if;
 update public.field_profiles set costs_reviewed=true where work_order_id=o;
 update public.financial_records set voided=true where id=fid;
 if exists(select 1 from public.field_profiles where work_order_id=o and costs_reviewed) then raise exception 'FAIL: void did not reopen cost review';end if;
 perform public.advance_field_order(w,o,'in_progress','completed');perform public.advance_field_order(w,o,'completed','invoice_ready');
 if not exists(select 1 from public.invoice_handoffs where work_order_id=o and amount_cents=503) then raise exception 'FAIL: revised invoice handoff total';end if;
 reset role;
 insert into field_results values('Customer reuse, lost opportunities, stale saves, pricebook isolation, itemized arithmetic, revision snapshots, purchasing and crew gates, walkthrough, expense review, duplicate prevention, invoice total',true);
 perform set_config('request.jwt.claims',json_build_object('sub',r,'role','authenticated')::text,true);set local role authenticated;
 if not exists(select 1 from public.financial_records where id=fid) then raise exception 'FAIL: authorized reader cannot read';end if;
 blocked:=false;begin update public.pricebook_items set name='Tampered' where workspace_id=w;insert into public.pricebook_items(workspace_id,name) values(w,'Reader tamper');exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: read-only pricebook write';end if;
 blocked:=false;begin insert into public.financial_records(workspace_id,work_order_id,kind,category,amount_cents,reference,occurred_on) values(w,o,'receipt','final',503,'READER',current_date);exception when others then blocked:=true;end;
 if not blocked then raise exception 'FAIL: read-only ledger write';end if;
 if exists(select 1 from public.pricebook_items where workspace_id=w2) then raise exception 'FAIL: other workspace catalog leaked';end if;
 reset role;insert into field_results values('Read-only ledger/catalog enforcement and cross-workspace catalog isolation',true);
end $test$;
select * from field_results;
rollback;
