begin;
insert into auth.users(id,email,email_confirmed_at) values('50000000-0000-4000-8000-000000000001','solo-owner@example.invalid',now());
insert into public.workspace_memberships(workspace_id,user_id,role) values('8ac08858-038c-41df-90a8-4a84f25cb400','50000000-0000-4000-8000-000000000001','owner');
set local role authenticated;
select set_config('request.jwt.claim.sub','50000000-0000-4000-8000-000000000001',true);
do $$declare a uuid;o uuid;p uuid;doc jsonb:='{}';discovery jsonb:='{}';k text;fees jsonb;original jsonb;begin
 insert into public.hq_accounts(workspace_id,company,contact_name,email,owner,next_action,due_on) values('8ac08858-038c-41df-90a8-4a84f25cb400','Solo verification fixture','QA','qa@example.invalid','Shawn','Review',current_date) returning id into a;
 foreach k in array array['outcomes','people','workflow','roles','systems','migration','rules','automation','security','commercial'] loop discovery:=discovery||jsonb_build_object(k,jsonb_build_object('status','confirmed','notes','Reviewed synthetic requirement'));end loop;
 insert into public.hq_opportunities(workspace_id,account_id,title,kind,owner,next_action,due_on,discovery) values('8ac08858-038c-41df-90a8-4a84f25cb400',a,'Solo test','implementation','Shawn','Review',current_date,jsonb_build_object('answers',discovery,'open_questions','')) returning id into o;
 insert into public.hq_requirements(workspace_id,opportunity_id,title,priority,actor,steps,expected) values('8ac08858-038c-41df-90a8-4a84f25cb400',o,'Estimate to job','must','Owner','Approve estimate and open job','One linked job with exact agreed scope');
 foreach k in array array['seller','customer','objective','scope','exclusions','assumptions','timeline','payment','tax','subscription','support','rights','termination','legal'] loop doc:=doc||jsonb_build_object(k,'Nonbinding verification fixture: '||k);end loop;
 if (select unit_cents from public.hq_pricebook where sku='WF-FIELD-SOLO') is distinct from 149500 or (select unit_cents from public.hq_pricebook where sku='WF-SOLO-CARE') is distinct from 9900 then raise exception 'TEST FAILED: Solo rates';end if;
 select jsonb_agg(jsonb_build_object('catalog_sku',sku,'description',name,'service',service,'cadence',cadence,'quantity_units',100,'unit_cents',unit_cents,'discount_cents',0) order by sku) into fees from public.hq_pricebook where sku in ('WF-FIELD-SOLO','WF-SOLO-CARE');
 original:=fees;
 insert into public.hq_proposals(workspace_id,opportunity_id,account_id,title,valid_until,document,lines,terms_reviewed,deposit_cents) values('8ac08858-038c-41df-90a8-4a84f25cb400',o,a,'Solo fixture',current_date+30,doc,fees,true,74750) returning id into p;
 begin update public.hq_proposals set lines=fees||jsonb_build_object('catalog_sku','WF-MANAGED','description','Managed','service','support','cadence','monthly','quantity_units',100,'unit_cents',14900,'discount_cents',0) where id=p;raise exception 'TEST FAILED: duplicate care accepted';exception when raise_exception then if sqlerrm not like 'WorkForge Managed replaces Solo Care%' then raise;end if;end;
 begin update public.hq_proposals set lines=replace(fees::text,'WF-FIELD-SOLO','WF-FIELD-FOUNDATION')::jsonb where id=p;raise exception 'TEST FAILED: Solo Care on Foundation';exception when raise_exception then if sqlerrm not like 'Solo Care is available for Field Solo%' then raise;end if;end;
 begin update public.hq_proposals set lines=fees||jsonb_build_object('catalog_sku','WF-AI-ASSISTANT','description','AI','service','software','cadence','monthly','quantity_units',100,'unit_cents',9900,'discount_cents',0) where id=p;raise exception 'TEST FAILED: AI without Managed';exception when raise_exception then if sqlerrm not like 'Monthly add-ons require%' then raise;end if;end;
 begin update public.hq_proposals set lines=fees||jsonb_build_object('catalog_sku','WF-FIELD-FOUNDATION','description','Foundation','service','implementation','cadence','one_time','quantity_units',100,'unit_cents',295000,'discount_cents',0) where id=p;raise exception 'TEST FAILED: two packages';exception when raise_exception then if sqlerrm not like 'Choose one Field implementation%' then raise;end if;end;
 update public.hq_proposals set lines=(select jsonb_agg(value) from jsonb_array_elements(fees) where value->>'catalog_sku'='WF-FIELD-SOLO') where id=p;
 if jsonb_array_length((select lines from public.hq_proposals where id=p))<>1 then raise exception 'TEST FAILED: no-monthly option';end if;
 select jsonb_agg(jsonb_build_object('catalog_sku',sku,'description',name,'service',service,'cadence',cadence,'quantity_units',100,'unit_cents',unit_cents,'discount_cents',0) order by sku) into fees from public.hq_pricebook where sku in ('WF-FIELD-SOLO','WF-MANAGED','WF-AI-ASSISTANT','WF-AI-ASSISTANT-SETUP');
 update public.hq_proposals set lines=fees where id=p;
 if (select sum((value->>'unit_cents')::bigint) from jsonb_array_elements(fees) where value->>'cadence'='monthly')<>24800 then raise exception 'TEST FAILED: upgraded care totals';end if;
 update public.hq_proposals set lines=original,status='issued' where id=p;
 update public.hq_pricebook set unit_cents=159500 where sku='WF-FIELD-SOLO';
 if (select lines from public.hq_proposals where id=p) is distinct from original then raise exception 'TEST FAILED: catalog update repriced issued Solo offer';end if;
 update public.hq_proposals set status='accepted',accepted_name='Synthetic QA approver',accepted_on=(now() at time zone 'America/Denver')::date,evidence='Rollback-only nonbinding Solo verification' where id=p;
 if (select sum(amount_cents) from public.hq_engagements where proposal_id=p and cadence='one_time')<>149500 or (select sum(amount_cents) from public.hq_engagements where proposal_id=p and cadence='monthly')<>9900 then raise exception 'TEST FAILED: Solo fixed and recurring handoff';end if;
 if (select count(*) from public.hq_implementations where proposal_id=p)<>1 then raise exception 'TEST FAILED: Solo implementation handoff';end if;
 if exists(select 1 from public.hq_subscriptions where account_id=a) then raise exception 'TEST FAILED: subscription activated';end if;
end $$;
rollback;
