begin;
do $test$
declare
 owner_id uuid:=gen_random_uuid(); reader_id uuid:=gen_random_uuid(); outsider_id uuid:=gen_random_uuid();
 w uuid:=gen_random_uuid(); hq uuid:='8ac08858-038c-41df-90a8-4a84f25cb400';
 job uuid; direct_job uuid; acct uuid; blocked boolean; stamp timestamptz; item uuid; draft jsonb; pipeline uuid;
begin
 insert into auth.users(id,email,email_confirmed_at) values(owner_id,'pipeline-owner@example.test',now()),(reader_id,'pipeline-reader@example.test',now()),(outsider_id,'pipeline-outsider@example.test',now());
 insert into public.workspaces(id,name,model,is_demo) values(w,'Pipeline test','field',true);
 insert into public.workspace_memberships(workspace_id,user_id,role) values(w,owner_id,'owner'),(w,reader_id,'read_only'),(hq,owner_id,'owner'),(hq,reader_id,'read_only');
 perform set_config('request.jwt.claims',json_build_object('sub',owner_id)::text,true);
 set local role authenticated;
 job:=public.create_field_lead(w,'Contacted customer','','','','Outreach only','Initial scope');
 perform public.advance_field_order(w,job,'lead','contacted');
 perform public.advance_field_order(w,job,'lead','contacted'); -- repeated delivery is idempotent
 if not exists(select 1 from public.work_orders where id=job and stage='contacted') or exists(select 1 from public.appointments where work_order_id=job) then raise exception 'Contacted must work without a booking';end if;
 if (select count(*) from public.audit_events where work_order_id=job and action='Moved to contacted')<>1 then raise exception 'Contacted transition audit must be idempotent';end if;
 blocked:=false;begin perform public.advance_field_order(w,job,'lead','appointment');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Stale Field stage was accepted';end if;
 blocked:=false;begin perform public.advance_field_order(w,job,'contacted','appointment');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Contacted bypassed consultation booking';end if;
 blocked:=false;begin perform public.advance_field_order(w,job,'contacted','estimated');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Contacted skipped consultation';end if;
 perform public.save_field_budget(w,job,100,200,40,'Draft scope while awaiting response');
 select updated_at into stamp from public.work_orders where id=job;
 perform public.save_field_estimate(w,job,stamp,'[{"id":"test","name":"Draft service","description":"Draft","quantity":1,"unit":"job","material_cents":100,"labor_cents":100,"unit_price_cents":400,"taxable":false}]','Draft scope',40,0,0,0,'Draft terms',null);
 insert into public.field_profiles(workspace_id,work_order_id,sales_status,lost_reason) values(w,job,'lost','No response');
 blocked:=false;begin perform public.advance_field_order(w,job,'contacted','appointment');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Lost contacted lead advanced';end if;
 update public.field_profiles set sales_status='open' where work_order_id=job;
 insert into public.pricebook_items(workspace_id,name,material_cents,labor_cents) values(w,'Test service',100,100) returning id into item;
 draft:=public.reserve_field_ai(w,job,'estimate','openai/gpt-5.6-luna');
 reset role;
 update public.ai_drafts set status='ready' where id=(draft->>'id')::uuid;
 set local role authenticated;
 perform public.apply_field_ai((draft->>'id')::uuid,jsonb_build_object('scope','Reviewed draft','items',jsonb_build_array(jsonb_build_object('product_id',item,'quantity',1,'description','Reviewed item'))));
 if not exists(select 1 from public.work_orders where id=job and stage='contacted' and description='Reviewed draft') then raise exception 'Contacted draft workflow failed';end if;
 insert into public.appointments(workspace_id,work_order_id,title,starts_at,ends_at) values(w,job,'Consultation',now(),now()+interval '1 hour');
 perform public.advance_field_order(w,job,'contacted','appointment');
 direct_job:=public.create_field_lead(w,'Direct booking','','','','Booked lead','Scope');
 insert into public.appointments(workspace_id,work_order_id,title,starts_at,ends_at) values(w,direct_job,'Consultation',now(),now()+interval '1 hour');
 perform public.advance_field_order(w,direct_job,'lead','appointment');
 insert into public.hq_accounts(workspace_id,company,contact_name,email,owner,next_action,due_on) values(hq,'Pipeline QA','QA contact','qa@example.test','Shawn','Await reply',current_date+2) returning id into acct;
 perform public.hq_set_stage(acct,'new','contacted');
 perform public.hq_set_stage(acct,'new','contacted');
 if not exists(select 1 from public.hq_accounts where id=acct and stage='contacted') or exists(select 1 from public.hq_events where hq_events.account_id=acct) then raise exception 'HQ Contacted needs no booking';end if;
 blocked:=false;begin perform public.hq_set_stage(acct,'new','discovery');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Stale HQ stage was accepted';end if;
 perform public.hq_set_stage(acct,'contacted','discovery');
 perform public.hq_set_stage(acct,'discovery','contacted');
 blocked:=false;begin perform public.hq_set_stage(acct,'contacted','won');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Contacted bypassed HQ agreement acceptance';end if;
 perform public.hq_set_stage(acct,'contacted','lost','No response');
 perform public.hq_set_stage(acct,'lost','contacted');
 perform set_config('request.jwt.claims',json_build_object('sub',reader_id)::text,true);
 blocked:=false;begin perform public.hq_set_stage(acct,'contacted','new');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Read-only HQ stage change';end if;
 blocked:=false;begin perform public.advance_field_order(w,direct_job,'appointment','estimated');exception when others then blocked:=true;end;
 if not blocked then raise exception 'Read-only Field stage change';end if;
 perform set_config('request.jwt.claims',json_build_object('sub',outsider_id)::text,true);
 if exists(select 1 from public.hq_accounts where id=acct) or exists(select 1 from public.work_orders where id=job) then raise exception 'Cross-workspace data exposed';end if;
 reset role;
end $test$;
rollback;
