import { notFound } from 'next/navigation';
import { session } from '@/lib/data';
import { lineAmount, money } from '@/lib/field';
import type { Estimate } from '@/lib/core';
import PrintButton from './print-button';
export const dynamic='force-dynamic';
export default async function Proposal({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const {db}=await session();
 const {data,error}=await db.from('estimate_versions').select('*').eq('id',id).maybeSingle();if(error||!data)notFound();
 const q=data as Estimate;const c=q.customer_snapshot;const {data:workspace}=await db.from('workspaces').select('name,is_demo').eq('id',data.workspace_id).single();
 return <main className="proposal-page"><div className="proposal-actions"><a href={`/?workspace=${data.workspace_id}`}>Back to WorkForge</a><PrintButton/></div><article className="proposal"><header><div><p className="eyebrow">PROJECT PROPOSAL</p><h1>{c.company||workspace?.name||'WorkForge Field'}</h1><p>Revision {q.version} · {q.status==='approved'?'Approved':'Draft'}</p></div><div className="proposal-brand">WORKFORGE<span>FIELD OS</span></div></header>{workspace?.is_demo&&<p className="proposal-demo">Fictional demonstration proposal · {q.status==='approved'?'simulated approval':'not a customer contract'}</p>}<section className="proposal-recipient"><div><small>PREPARED FOR</small><h2>{c.name||'Customer'}</h2><p>{c.address}</p><p>{c.email}</p></div><div><small>VALID THROUGH</small><strong>{q.valid_until||'Not specified'}</strong></div></section><section><h2>Scope of work</h2><p className="preserve-lines">{q.scope}</p></section><table><thead><tr><th>Service / material</th><th>Quantity</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>{q.line_items.length?q.line_items.map((l,i)=><tr key={i}><td><strong>{l.name}</strong><p className="preserve-lines">{l.description}</p></td><td>{l.quantity} {l.unit}</td><td>{money(l.unit_price_cents)}</td><td>{money(lineAmount(l.quantity,l.unit_price_cents))}</td></tr>):<tr><td>Project scope as described</td><td>1 job</td><td>{money(q.price_cents)}</td><td>{money(q.price_cents)}</td></tr>}</tbody></table><dl className="proposal-totals"><div><dt>Subtotal</dt><dd>{money(q.subtotal_cents||q.price_cents)}</dd></div><div><dt>Discount</dt><dd>−{money(q.discount_cents)}</dd></div><div><dt>Tax</dt><dd>{money(q.tax_cents)}</dd></div><div className="total"><dt>Total</dt><dd>{money(q.price_cents)}</dd></div><div><dt>Requested deposit</dt><dd>{money(q.deposit_cents)}</dd></div></dl>{q.terms&&<section><h2>Terms</h2><p className="preserve-lines">{q.terms}</p></section>}{q.status==='approved'&&<p className="proposal-approval">{workspace?.is_demo?'Demonstration approval':'Approval'} recorded for {q.approved_by}. This revision is locked.</p>}<footer>Prepared with WorkForge Field OS</footer></article></main>;
}
