'use client';
import { useState } from 'react';
import { ArrowRight, Check, CheckCircle2, Circle, Clock3, Download, FileText, Mail, Phone, Plus } from 'lucide-react';
import type { Activity, CRMData, Deal } from '@/lib/crm/types';
import { currency } from '@/lib/core';
import { followupState } from '@/lib/crm/logic';
import { daysInStage, isStalled, qualificationScore, stepKey } from '@/lib/crm/workflow';
import { Modal, type Edit, type Save } from './forms';
type Tab='overview'|'qualification'|'proposal'|'timeline';
export function DealWorkspace({deal,d,save,onClose,onEdit,onLost,busy,error,activityRow}:{deal:Deal;d:CRMData;save:Save;onClose:()=>void;onEdit:(e:Edit)=>void;onLost:(deal:Deal)=>void;busy:boolean;error:string;activityRow:(a:Activity)=>React.ReactNode}) {
 const [tab,setTab]=useState<Tab>('overview'),[logging,setLogging]=useState(false);
 const writable=d.role!=='read_only',person=d.contacts.find(c=>c.id===deal.contact_id),stages=d.stages.filter(s=>s.pipeline_id===deal.pipeline_id).sort((a,b)=>a.position-b.position),stage=stages.find(s=>s.id===deal.stage_id),nextStage=stages[stages.findIndex(s=>s.id===deal.stage_id)+1];
 const now=Date.parse(d.loadedAt),next=followupState(deal,d.activities,now),score=qualificationScore(deal),activities=d.activities.filter(a=>a.deal_id===deal.id),notes=d.notes.filter(n=>n.deal_id===deal.id);
 const completed=stage?.checklist.filter(s=>deal.completed_steps.includes(stepKey(stage,s))).length||0;
 const date=(v:string|null,full=false)=>v?new Intl.DateTimeFormat('en-US',{timeZone:d.workspace.timezone,month:'short',day:'numeric',year:'numeric',...(full?{hour:'numeric',minute:'2-digit'}:{})}).format(new Date(v.length===10?v+'T12:00:00Z':v)):'Not set';
 const owner=(id:string|null)=>d.team.find(t=>t.user_id===id)?.email.split('@')[0]||'Unassigned';
 const schedule=(title?:string,kind:Activity['kind']='call')=>onEdit({kind:'activity',dealId:deal.id,contactId:deal.contact_id,title,activityKind:kind});
 const submit=(operation:string,e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();save(operation,{...Object.fromEntries(new FormData(e.currentTarget)),id:deal.id,version:deal.updated_at});};
 function exportProposal(){const text=[`PROPOSAL — ${deal.title}`,`Prepared for: ${person?.name||''}`,`Company: ${d.companies.find(c=>c.id===person?.company_id)?.name||''}`,`Value: ${currency(deal.value_cents)}`,`Status: ${deal.proposal_status}`,`Valid until: ${date(deal.proposal_valid_until)}`,'',deal.proposal_summary,'',deal.proposal_url].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='workforge-proposal.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const timeline=[...notes.map(n=>({id:n.id,at:n.created_at,label:'Note',body:n.body,by:owner(n.author_id)})),...activities.filter(a=>a.completed_at).map(a=>({id:a.id,at:a.completed_at!,label:`${a.kind} · ${a.title}`,body:a.outcome||'Activity completed',by:owner(a.owner_id)})),...d.history.filter(h=>h.record_id===deal.id).map(h=>({id:h.id,at:h.created_at,label:h.description,body:'',by:owner(h.actor_id)}))].sort((a,b)=>b.at.localeCompare(a.at));
 return <Modal title="Opportunity workspace" onClose={onClose} wide><div className="crm-opportunity">
  <div className="crm-opportunity-head"><div><span className={`crm-outcome ${deal.status}`}>{deal.status==='open'?'Open opportunity':deal.status==='won'?'Won':'Lost'}</span><h2>{deal.title}</h2><p>{person?.name} {person?.company_id&&<>· {d.companies.find(c=>c.id===person.company_id)?.name}</>}</p></div><div><strong>{currency(deal.value_cents)}</strong>{writable&&<button className="crm-btn" onClick={()=>onEdit({kind:'deal',item:deal})}>Edit opportunity</button>}</div></div>
  <div className="crm-deal-controls"><label>Pipeline stage<select aria-label="Pipeline stage" value={deal.stage_id} disabled={!writable||busy||deal.status!=='open'} onChange={e=>save('move',{id:deal.id,pipeline_id:deal.pipeline_id,stage_id:e.target.value,version:deal.updated_at})}>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{writable&&<div>{deal.status==='open'?<><button className="crm-btn crm-success" disabled={busy} onClick={()=>save('status',{id:deal.id,status:'won',lost_reason:'',version:deal.updated_at})}><Check size={15}/>Mark won</button><button className="crm-btn" disabled={busy} onClick={()=>onLost(deal)}>Mark lost</button></>:<button className="crm-btn" disabled={busy} onClick={()=>save('status',{id:deal.id,status:'open',lost_reason:'',version:deal.updated_at})}>Reopen opportunity</button>}</div>}</div>
  <div className="crm-detail-facts"><span>Owner<strong>{owner(deal.owner_id)}</strong></span><span>Expected close<strong>{date(deal.expected_close)}</strong></span><span>Priority<strong>{deal.priority}</strong></span><span>Source<strong>{deal.source}</strong></span></div>
  {deal.lost_reason&&<p className="crm-loss-reason">Loss reason: {deal.lost_reason}</p>}
  {person?.do_not_contact&&<p className="crm-loss-reason">Do not contact. Keep any next steps internal.</p>}
  <div className="crm-tabs crm-workspace-tabs">{([['overview','Sales playbook'],['qualification',`Qualification · ${score}/4`],['proposal','Proposal'],['timeline','Activity & notes']] as [Tab,string][]).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==='overview'&&<div className="crm-opportunity-grid"><section>
   <div className="crm-playbook"><span className="crm-eyebrow">{deal.status==='open'?'CURRENT STAGE':'LAST ACTIVE STAGE'}</span><h3>{stage?.name}</h3><p>{stage?.purpose||'Use your team’s sales process to move this opportunity forward.'}</p><div className="crm-playbook-progress"><span>{completed}/{stage?.checklist.length||0} steps complete</span><span className={isStalled(deal,stage,now)?'crm-danger':''}>{daysInStage(deal,now)} days in stage{isStalled(deal,stage,now)?' · Stalled':''}</span></div>
   {stage?.checklist.map(step=>{const key=stepKey(stage,step),done=deal.completed_steps.includes(key);return <label className="crm-playbook-check" key={key}><input type="checkbox" checked={done} disabled={!writable||busy} onChange={()=>save('checklist',{id:deal.id,version:deal.updated_at,completed_steps:done?deal.completed_steps.filter(s=>s!==key):[...deal.completed_steps,key]})}/><span>{step}</span></label>;})}
   {writable&&deal.status==='open'&&nextStage&&<button className="crm-btn crm-primary" disabled={busy} onClick={()=>save('move',{id:deal.id,pipeline_id:deal.pipeline_id,stage_id:nextStage.id,version:deal.updated_at})}>Move to {nextStage.name}<ArrowRight size={16}/></button>}
   <small className="crm-help">Checklists guide your process. Move stages when the buyer is ready.</small></div>
   <div className="crm-section-tools"><h3>Scheduled activities</h3>{writable&&<button className="crm-link" onClick={()=>schedule()}>Schedule<Plus size={15}/></button>}</div>{activities.filter(a=>!a.completed_at).sort((a,b)=>a.due_at.localeCompare(b.due_at)).map(activityRow)}{!activities.some(a=>!a.completed_at)&&<p className="crm-help">No scheduled activity. Choose a next step to keep this opportunity moving.</p>}
  </section><aside className="crm-next-panel"><span className="crm-eyebrow">NEXT BEST ACTION</span><h3>{next.next?.title||'Plan the next conversation'}</h3><p className={next.state==='overdue'?'crm-danger':''}>{next.next?`${next.state==='overdue'?'Overdue · ':''}${date(next.next.due_at,true)}`:'Assign a date and an owner for the next step.'}</p>{writable&&<><button className="crm-btn crm-primary" onClick={()=>setLogging(true)}><Phone size={16}/>Log activity & next step</button><button className="crm-btn" onClick={()=>schedule('Discovery conversation','meeting')}>Schedule discovery</button></>}
   <hr/><h4>Qualification</h4><p>{score===4?'Needs, budget, decision maker, and timing captured.':`${4-score} details still need to be captured.`}</p><button className="crm-link" onClick={()=>setTab('qualification')}>Review qualification<ArrowRight size={14}/></button><hr/><h4>Proposal</h4><p>{deal.proposal_status==='draft'?'Prepare the scope and proposal when the opportunity is qualified.':`${deal.proposal_status[0].toUpperCase()+deal.proposal_status.slice(1)} · ${date(deal.proposal_sent_on)}`}</p><button className="crm-link" onClick={()=>setTab('proposal')}>Open proposal<ArrowRight size={14}/></button>
   {person&&!person.do_not_contact&&<><hr/><h4>Contact shortcuts</h4><div className="crm-actions">{person.email&&<a className="crm-btn" href={`mailto:${person.email}`}><Mail size={15}/>Email</a>}{person.phone&&<a className="crm-btn" href={`tel:${person.phone.replace(/[^\d+]/g,'')}`}><Phone size={15}/>Call</a>}</div><small className="crm-help">Opens your email or phone app. Log the outcome afterward.</small></>}
  </aside></div>}
  {tab==='qualification'&&<form key={'qualification'+deal.updated_at} onSubmit={e=>submit('qualification',e)}><div className="crm-form-intro"><h3>Understand the buying decision</h3><p>Capture the basics before investing time in a proposal. {score} of 4 areas documented.</p></div><fieldset disabled={!writable||busy}><div className="crm-form-grid"><label className="crm-field crm-wide"><span>Need & desired outcome</span><textarea name="need" rows={4} maxLength={5000} defaultValue={deal.need} placeholder="What problem are they solving? What would success look like?"/></label><label className="crm-field"><span>Budget & commercial fit</span><textarea name="budget" rows={3} maxLength={1000} defaultValue={deal.budget} placeholder="Budget range, funding, and fit"/></label><label className="crm-field"><span>Decision maker & buying process</span><textarea name="decision_maker" rows={3} maxLength={1000} defaultValue={deal.decision_maker} placeholder="Who approves, and who else needs to be involved?"/></label><label className="crm-field crm-wide"><span>Buying timeline</span><textarea name="buying_timeline" rows={2} maxLength={1000} defaultValue={deal.buying_timeline} placeholder="Target start date, decision date, and timing constraints"/></label></div></fieldset>{writable&&<footer><button className="crm-btn crm-primary" disabled={busy}>Save qualification</button></footer>}</form>}
  {tab==='proposal'&&<form key={'proposal'+deal.updated_at} onSubmit={e=>submit('proposal',e)}><div className="crm-form-intro"><div><h3>Proposal & decision</h3><p>Keep the scope, proposal link, and decision status with the opportunity.</p></div><button type="button" className="crm-btn" onClick={exportProposal}><Download size={16}/>Export summary</button></div><fieldset disabled={!writable||busy}><div className="crm-form-grid"><label className="crm-field crm-wide"><span>Proposal scope & terms</span><textarea name="proposal_summary" rows={6} maxLength={10000} defaultValue={deal.proposal_summary} placeholder="Describe the offer, deliverables, exclusions, and agreed commercial terms."/></label><label className="crm-field crm-wide"><span>Proposal document link</span><input name="proposal_url" type="url" maxLength={1000} defaultValue={deal.proposal_url} placeholder="https://"/></label><label className="crm-field"><span>Proposal status</span><select name="proposal_status" defaultValue={deal.proposal_status}>{['draft','shared','accepted','declined'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label><div className="crm-field"><span>Opportunity value</span><strong>{currency(deal.value_cents)}</strong><small>Change the value in Edit opportunity.</small></div><label className="crm-field"><span>Date shared</span><input type="date" name="proposal_sent_on" defaultValue={deal.proposal_sent_on||''}/></label><label className="crm-field"><span>Valid until</span><input type="date" name="proposal_valid_until" defaultValue={deal.proposal_valid_until||''}/></label></div></fieldset><p className="crm-help">Tracking a proposal does not send it or collect a signature. Mark the deal won when the sale is confirmed.</p><footer>{deal.proposal_url&&/^https?:\/\//i.test(deal.proposal_url)&&<a className="crm-btn" href={deal.proposal_url} target="_blank" rel="noreferrer"><FileText size={15}/>Open document</a>}{writable&&<><button type="button" className="crm-btn" onClick={()=>schedule('Review proposal with buyer','meeting')}>Schedule review</button><button className="crm-btn crm-primary" disabled={busy}>Save proposal</button></>}</footer></form>}
  {tab==='timeline'&&<><div className="crm-section-tools"><h3>Relationship history</h3>{writable&&<button className="crm-btn" onClick={()=>setLogging(true)}>Log activity & next step</button>}</div>{writable&&<form className="crm-note-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;save('note',{deal_id:deal.id,contact_id:deal.contact_id,body:String(new FormData(form).get('body')||'')},()=>form.reset());}}><textarea name="body" required rows={3} maxLength={10000} placeholder="Add context, objections, or a decision…" aria-label="New opportunity note"/><button className="crm-btn" disabled={busy}>Add note</button></form>}<div className="crm-timeline">{timeline.map(t=><article key={t.id}><span className="crm-timeline-dot"/><div><strong>{t.label}</strong>{t.body&&<p>{t.body}</p>}<small>{t.by} · {date(t.at,true)}</small></div></article>)}</div></>}
  {error&&<p className="crm-form-error" role="alert">{error}</p>}
 </div>{logging&&<TouchpointForm deal={deal} d={d} save={save} busy={busy} error={error} onClose={()=>setLogging(false)}/>}</Modal>;
}
function TouchpointForm({deal,d,save,busy,error,onClose}:{deal:Deal;d:CRMData;save:Save;busy:boolean;error:string;onClose:()=>void}) {
 const person=d.contacts.find(c=>c.id===deal.contact_id),stage=d.stages.find(s=>s.id===deal.stage_id),pending=d.activities.filter(a=>a.deal_id===deal.id&&!a.completed_at).sort((a,b)=>a.due_at.localeCompare(b.due_at));
 const local=(value:number)=>{const dt=new Date(value);return new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 return <Modal title="Log activity & plan the next step" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));save('touchpoint',{...f,id:deal.id,version:deal.updated_at,title:`${f.kind}: ${f.result}`,outcome:`${f.result}${f.notes?' — '+f.notes:''}`,next_at:new Date(String(f.next_at)).toISOString(),advance_contacted:f.advance_contacted==='on'},onClose);}}><fieldset disabled={busy}><div className="crm-form-grid"><label className="crm-field"><span>Activity type</span><select name="kind"><option value="call">Call</option><option value="email">Email</option><option value="meeting">Meeting</option><option value="task">Task</option></select></label><label className="crm-field"><span>Outcome</span><select name="result"><option>No answer / awaiting reply</option><option>Connected — follow-up needed</option><option>Discovery booked</option><option>Discovery completed</option><option>Proposal reviewed</option><option>Decision pending</option><option>Not interested</option><option>Other</option></select></label><label className="crm-field crm-wide"><span>Complete a scheduled activity</span><select name="activity_id" defaultValue={pending[0]?.id||''}><option value="">Log a separate activity</option>{pending.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="crm-field crm-wide"><span>Conversation notes</span><textarea name="notes" rows={3} maxLength={2700} placeholder="What happened, what did you learn, and what was agreed?"/></label>{stage?.name==='New lead'&&deal.status==='open'&&<label className="crm-check crm-wide"><input type="checkbox" name="advance_contacted" defaultChecked/>Move this opportunity to Contacted</label>}<h3 className="crm-wide">What happens next?</h3><label className="crm-field crm-wide"><span>Next activity</span><input name="next_title" required maxLength={300} defaultValue={person?.do_not_contact?'Review this opportunity internally':`Follow up with ${person?.name||'the buyer'}`}/></label><label className="crm-field"><span>Next activity type</span><select name="next_kind" defaultValue={person?.do_not_contact?'task':'call'}><option value="call">Call</option><option value="email">Email reminder</option><option value="meeting">Meeting</option><option value="task">Task</option></select></label><label className="crm-field"><span>Next due (your device timezone)</span><input name="next_at" required type="datetime-local" defaultValue={local(Date.now()+2*86400000)}/></label></div></fieldset><p className="crm-help">Saves the outcome and next activity together. No email or SMS is sent.</p>{error&&<p className="crm-form-error" role="alert">{error}</p>}<footer><button type="button" className="crm-btn" onClick={onClose}>Cancel</button><button className="crm-btn crm-primary" disabled={busy}>{busy?'Saving…':'Save activity & next step'}</button></footer></form></Modal>;
}
