'use client';
import { useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { X, Upload } from 'lucide-react';
import type { CRMData, Person, Company, Deal, Activity, Stage } from '@/lib/crm/types';
import { SOURCES, parseCSV } from '@/lib/crm/logic';
export type Edit = {kind:'contact';item?:Person}|{kind:'company';item?:Company}|{kind:'deal';item?:Deal;contactId?:string}|{kind:'activity';item?:Activity;dealId?:string;contactId?:string;title?:string;activityKind?:Activity['kind']}|{kind:'stage';item?:Stage;pipelineId:string}|{kind:'pipeline'}|{kind:'import'}|{kind:'member'};
export type Save=(operation:string,input:Record<string,unknown>,close?:()=>void)=>void;
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);
 return <dialog className={`crm-modal ${wide?'crm-modal-wide':''}`} ref={ref} onCancel={onClose}><header><h2>{title}</h2><button type="button" className="crm-icon" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></header>{children}</dialog>;
}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}) {return <label className={wide?'crm-field crm-wide':'crm-field'}><span>{label}</span>{children}</label>;}
function inputData(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));}
function Owner({d,value}:{d:CRMData;value?:string|null}) {return <Field label="Owner"><select name="owner_id" defaultValue={value===undefined?d.userId:value||''}><option value="">Unassigned</option>{d.team.filter(t=>t.is_active&&t.role!=='read_only').map(t=><option key={t.user_id} value={t.user_id}>{t.email}</option>)}</select></Field>;}
function Source({value}:{value?:string}) {return <Field label="Lead source"><input name="source" list="crm-sources" defaultValue={value||'Manual'} maxLength={100}/><datalist id="crm-sources">{SOURCES.map(s=><option key={s} value={s}/>)}</datalist></Field>;}
export function EditForm({edit,d,save,onClose,busy,error}:{edit:Edit;d:CRMData;save:Save;onClose:()=>void;busy:boolean;error:string}) {
 const item='item' in edit?edit.item:undefined;
 const [pipeline,setPipeline]=useState(edit.kind==='deal'?(edit.item?.pipeline_id||d.pipelines[0]?.id||''):'');
 const [newContact,setNewContact]=useState(false);
 const [csv,setCSV]=useState('');const [preview,setPreview]=useState('');
 const [selectedDeal,setSelectedDeal]=useState(edit.kind==='activity'?edit.item?.deal_id||edit.dealId||'':'');
 const title=edit.kind==='import'?'Import contacts':edit.kind==='member'?'Add team access':`${item?'Edit':'New'} ${edit.kind==='deal'?'opportunity':edit.kind}`;
 function submit(e:FormEvent<HTMLFormElement>){const f=inputData(e);let payload:Record<string,unknown>={...f,id:item?.id};
  if(edit.kind==='contact')payload={...payload,tags:String(f.tags||'').split(',').map(s=>s.trim()).filter(Boolean),do_not_contact:f.do_not_contact==='on'};
  if(edit.kind==='deal')payload={...payload,version:edit.item?.updated_at,...(!edit.item?{contact_id:newContact?'':f.contact_id,next_at:new Date(String(f.next_at)).toISOString()}:{} )};
  if(edit.kind==='activity'){const date=new Date(String(f.due_at));if(!Number.isFinite(date.getTime()))return;payload={...payload,due_at:date.toISOString(),duration_minutes:Number(f.duration_minutes)};}
  if(edit.kind==='stage')payload={...payload,pipeline_id:edit.pipelineId,position:edit.item?.position??Math.max(-1,...d.stages.filter(s=>s.pipeline_id===edit.pipelineId).map(s=>s.position))+1,probability:Number(f.probability),followup_days:f.followup_days===''?null:Number(f.followup_days),stale_days:Number(f.stale_days),checklist:String(f.checklist||'').split('\n').map(s=>s.trim()).filter(Boolean)};
  if(edit.kind==='import')payload={csv};
  save(edit.kind,payload,onClose);
 }
 const person=edit.kind==='contact'?edit.item:undefined,company=edit.kind==='company'?edit.item:undefined,deal=edit.kind==='deal'?edit.item:undefined,activity=edit.kind==='activity'?edit.item:undefined;
 const localDate=(value:string)=>{const dt=new Date(value);return new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 return <Modal title={title} onClose={onClose}><form onSubmit={submit}><fieldset disabled={busy}><div className="crm-form-grid">
 {edit.kind==='contact'&&<><Field label="Full name"><input autoFocus name="name" required maxLength={200} defaultValue={person?.name}/></Field><Field label="Email"><input name="email" type="email" maxLength={254} defaultValue={person?.email}/></Field><Field label="Phone"><input name="phone" type="tel" maxLength={40} defaultValue={person?.phone}/></Field><Field label="Job title"><input name="job_title" maxLength={150} defaultValue={person?.job_title}/></Field><Field label="Company"><select name="company_id" defaultValue={person?.company_id||''}><option value="">No company</option>{d.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Owner d={d} value={person?.owner_id}/><Source value={person?.source}/><Field label="Lifecycle"><select name="lifecycle" defaultValue={person?.lifecycle||'lead'}>{['lead','qualified','customer','archived'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Tags (comma separated)" wide><input name="tags" defaultValue={person?.tags.join(', ')} placeholder="Priority, commercial, referral"/></Field><label className="crm-check crm-wide"><input name="do_not_contact" type="checkbox" defaultChecked={person?.do_not_contact}/>Do not contact</label></>}
 {edit.kind==='company'&&<><Field label="Company name" wide><input autoFocus name="name" required maxLength={200} defaultValue={company?.name}/></Field><Field label="Website"><input name="website" type="url" placeholder="https://" defaultValue={company?.website}/></Field><Field label="Phone"><input name="phone" maxLength={40} defaultValue={company?.phone}/></Field><Field label="Industry"><input name="industry" maxLength={100} defaultValue={company?.industry}/></Field><Field label="Address" wide><input name="address" maxLength={500} defaultValue={company?.address}/></Field></>}
 {edit.kind==='deal'&&<><Field label="Deal title" wide><input autoFocus name="title" required maxLength={200} defaultValue={deal?.title} placeholder="What are we helping them buy?"/></Field>{!deal&&<label className="crm-check crm-wide"><input type="checkbox" checked={newContact} onChange={e=>setNewContact(e.target.checked)}/>Create a new contact with this opportunity</label>}{newContact?<><Field label="Contact name"><input name="contact_name" required maxLength={200}/></Field><Field label="Contact email"><input name="contact_email" type="email"/></Field><Field label="Contact phone"><input name="contact_phone" type="tel" maxLength={40}/></Field></>:<Field label="Contact"><select name="contact_id" required defaultValue={deal?.contact_id||edit.contactId||''}><option value="">Select a contact</option>{d.contacts.filter(c=>c.lifecycle!=='archived'||c.id===deal?.contact_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>}<Field label="Deal value (USD)"><input name="value" type="number" min="0" step="0.01" required defaultValue={deal?deal.value_cents/100:0}/></Field><Field label="Pipeline"><select name="pipeline_id" required value={pipeline} onChange={e=>setPipeline(e.target.value)}>{d.pipelines.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Stage"><select name="stage_id" key={pipeline} defaultValue={deal?.pipeline_id===pipeline?deal.stage_id:undefined} required>{d.stages.filter(s=>s.pipeline_id===pipeline).sort((a,b)=>a.position-b.position).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Owner d={d} value={deal?.owner_id}/><Source value={deal?.source}/><Field label="Expected close date"><input name="expected_close" type="date" defaultValue={deal?.expected_close||''}/></Field><Field label="Priority"><select name="priority" defaultValue={deal?.priority||'normal'}><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></Field>{!deal&&<><h3 className="crm-wide">Plan the first activity</h3><Field label="Next activity"><input name="next_title" required maxLength={300} defaultValue="Make the first contact"/></Field><Field label="First activity due (your device timezone)"><input name="next_at" type="datetime-local" required defaultValue={localDate(new Date(Date.now()+3600000).toISOString())}/></Field></>}</>}
 {edit.kind==='activity'&&<><Field label="Activity title" wide><input autoFocus name="title" required maxLength={300} defaultValue={activity?.title||edit.title} placeholder="Call to discuss their goals"/></Field><Field label="Type"><select name="kind" defaultValue={activity?.kind||edit.activityKind||'call'}>{['call','email','meeting','task'].map(x=><option key={x}>{x}</option>)}</select></Field><Owner d={d} value={activity?.owner_id}/><Field label="Due date & time (your device timezone)"><input name="due_at" type="datetime-local" required defaultValue={localDate(activity?.due_at||new Date(Date.now()+3600000).toISOString())}/></Field><Field label="Duration (minutes)"><input name="duration_minutes" type="number" min="5" max="1440" step="5" defaultValue={activity?.duration_minutes||30}/></Field><Field label="Related deal"><select name="deal_id" value={selectedDeal} onChange={e=>setSelectedDeal(e.target.value)}><option value="">No deal</option>{d.deals.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></Field><Field label="Contact"><select key={selectedDeal} name="contact_id" defaultValue={d.deals.find(x=>x.id===selectedDeal)?.contact_id||activity?.contact_id||edit.contactId||''}><option value="">No contact</option>{d.contacts.filter(c=>!selectedDeal||d.deals.find(x=>x.id===selectedDeal)?.contact_id===c.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Notes / outcome" wide><textarea name="outcome" rows={3} maxLength={3000} defaultValue={activity?.outcome}/></Field></>}
 {edit.kind==='pipeline'&&<><Field label="Pipeline name" wide><input autoFocus name="name" required maxLength={100} placeholder="New business"/></Field><p className="crm-help crm-wide">Starts with New lead, Contacted, Discovery, Qualified, Proposal sent, and Negotiation, with a playbook for each stage and separate Won / Lost outcomes. Customize stages after creating it.</p></>}
 {edit.kind==='stage'&&<><Field label="Stage name" wide><input autoFocus name="name" required maxLength={100} defaultValue={edit.item?.name}/></Field><Field label="Win probability (%)"><input name="probability" type="number" min="0" max="100" required defaultValue={edit.item?.probability??20}/></Field><Field label="Automatic follow-up after (days)"><input name="followup_days" type="number" min="0" max="365" defaultValue={edit.item?.followup_days??''} placeholder="Leave blank to disable"/></Field><Field label="Flag as stalled after (days)"><input name="stale_days" type="number" min="1" max="365" required defaultValue={edit.item?.stale_days||7}/></Field><Field label="Stage purpose" wide><textarea name="purpose" rows={2} maxLength={1000} defaultValue={edit.item?.purpose}/></Field><Field label="Stage checklist (one item per line, up to 12)" wide><textarea name="checklist" rows={4} defaultValue={edit.item?.checklist?.join('\n')}/></Field><p className="crm-help crm-wide">Creates one follow-up call when a deal enters this stage, unless another activity is already open. Zero means due immediately. It creates a task; it does not contact the customer.</p></>}
 {edit.kind==='member'&&<><Field label="Email" wide><input autoFocus name="email" type="email" required/></Field><Field label="Access"><select name="role"><option value="member">Member — edit CRM records</option><option value="read_only">Read only</option>{d.role==='owner'&&<option value="administrator">Administrator — configure and add users</option>}</select></Field><p className="crm-help crm-wide">Team members can see this CRM workspace. This reserves access without sending an email. They sign in using the same WorkForge login.</p></>}
 {edit.kind==='import'&&<><p className="crm-help crm-wide">CSV headers: <strong>name</strong>, email, phone, source, job_title, tags. Separate tags with semicolons. Matching emails are skipped; existing contacts are preserved. Up to 500 rows.</p><Field label="Choose CSV file" wide><input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>500000){setPreview('Use a file smaller than 500 KB.');setCSV('');return;}const text=await file.text();try{const rows=parseCSV(text);setCSV(text);setPreview(`${rows.length} contacts ready for validation. First: ${rows.slice(0,3).map(r=>r.name).join(', ')}`);}catch(err){setCSV('');setPreview(err instanceof Error?err.message:'Unable to read CSV.');}}}/></Field><p className="crm-help crm-wide">{preview}</p></>}
 </div></fieldset>{error&&<p className="crm-form-error" role="alert">{error}</p>}<footer><button type="button" className="crm-btn" onClick={onClose}>Cancel</button><button className="crm-btn crm-primary" disabled={busy||(edit.kind==='import'&&!csv)}>{busy?'Saving…':edit.kind==='import'?<><Upload size={16}/>Import contacts</>:'Save'}</button></footer></form></Modal>;
}
