'use client';
import { useState } from 'react';
import { ArrowRight, CheckCircle2, Clock3, Download, Flag, Plus, Settings2, Target, TrendingUp, XCircle } from 'lucide-react';
import { currency } from '@/lib/core';
import type { CRMData, Deal } from '@/lib/crm/types';
import { followupState, summarize } from '@/lib/crm/logic';
import { attentionMatches, daysInStage, isStalled, type Attention } from '@/lib/crm/workflow';
export function PipelineView({d,deals,pipeline,onPipeline,status,onStatus,onOpen,onNew,onSettings,onExport,onMove,busy}:{d:CRMData;deals:Deal[];pipeline:string;onPipeline:(id:string)=>void;status:string;onStatus:(s:string)=>void;onOpen:(id:string)=>void;onNew:()=>void;onSettings:()=>void;onExport:()=>void;onMove:(id:string,stage:string)=>void;busy:boolean}) {
 const [attention,setAttention]=useState<Attention>('all'),[list,setList]=useState(false),[focus,setFocus]=useState('');
 const now=Date.parse(d.loadedAt),writable=d.role!=='read_only',stages=d.stages.filter(s=>s.pipeline_id===pipeline).sort((a,b)=>a.position-b.position);
 const all=deals.filter(x=>x.pipeline_id===pipeline),stats=summarize(all,stages);
 const filtered=all.filter(x=>(status==='all'||x.status===status)&&attentionMatches(x,attention,d.activities,stages,now));
 const selectedStage=stages.find(s=>s.id===focus);
 const owner=(id:string|null)=>d.team.find(t=>t.user_id===id)?.email.split('@')[0]||'Unassigned';
 const date=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:d.workspace.timezone}).format(new Date(value.length===10?value+'T12:00:00Z':value));
 function card(deal:Deal) {
  const person=d.contacts.find(c=>c.id===deal.contact_id),next=followupState(deal,d.activities,now),stage=stages.find(s=>s.id===deal.stage_id),stalled=isStalled(deal,stage,now);
  return <button key={deal.id} className={`crm-deal-card ${deal.priority==='high'?'is-priority':''}`} disabled={busy} draggable={writable&&!busy&&deal.status==='open'} onDragStart={e=>e.dataTransfer.setData('text/plain',deal.id)} onClick={()=>onOpen(deal.id)}>
   <span className="crm-card-source">{deal.priority==='high'?<span className="crm-priority"><Flag size={12}/> High priority</span>:deal.source}<span title={owner(deal.owner_id)}>{owner(deal.owner_id).slice(0,2).toUpperCase()}</span></span>
   <strong>{deal.title}</strong><span className="crm-card-contact">{person?.name}{person?.company_id&&<> · {d.companies.find(c=>c.id===person.company_id)?.name}</>}</span><b>{currency(deal.value_cents)}</b>
   {deal.status==='open'?<><span className={`crm-next ${next.state}`}><Clock3 size={14}/>{next.next?next.next.title:'Schedule a next activity'}</span><span className="crm-card-meta">{next.next?`${next.state==='overdue'?'Overdue · ':''}${date(next.next.due_at)}`:'No next step'}<span className={stalled?'crm-danger':''}>{daysInStage(deal,now)}d in stage{stalled?' · Stalled':''}</span></span>{deal.expected_close&&<small>Expected close {date(deal.expected_close)}</small>}</>:<span className={`crm-next ${deal.status==='won'?'scheduled':'overdue'}`}>{deal.status==='won'?'Won':'Lost'} · {deal.closed_at?date(deal.closed_at):''}</span>}
  </button>;
 }
 return <>
  <div className="crm-pipeline-metrics">
   <div><Target size={18}/><span>Open pipeline<strong>{currency(stats.value)}</strong><small>{stats.open} opportunities</small></span></div>
   <div><TrendingUp size={18}/><span>Weighted forecast<strong>{currency(stats.weighted)}</strong><small>Value × stage probability</small></span></div>
   <button onClick={()=>{onStatus('won');setAttention('all');}}><CheckCircle2 size={18}/><span>Won<strong>{currency(stats.won)}</strong><small>{all.filter(x=>x.status==='won').length} closed wins · all time</small></span><ArrowRight size={16}/></button>
   <button onClick={()=>{onStatus('lost');setAttention('all');}}><XCircle size={18}/><span>Lost<strong>{all.filter(x=>x.status==='lost').length} deals</strong><small>{stats.winRate===null?'No closed deals':`${stats.winRate}% win rate`}</small></span><ArrowRight size={16}/></button>
  </div>
  <div className="crm-section-tools"><div><select aria-label="Sales pipeline" value={pipeline} onChange={e=>{onPipeline(e.target.value);setFocus('');}}>{d.pipelines.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><div className="crm-tabs">{['open','won','lost','all'].map(s=><button key={s} className={status===s?'active':''} onClick={()=>{onStatus(s);setAttention('all');}}>{s==='all'?'All outcomes':s[0].toUpperCase()+s.slice(1)}</button>)}</div></div><div><button className="crm-btn" onClick={()=>setList(!list)}>{list?'Board view':'List view'}</button><button className="crm-btn" onClick={onExport} aria-label="Export pipeline"><Download size={16}/></button><button className="crm-btn" onClick={onSettings}><Settings2 size={16}/>Manage stages</button></div></div>
  <div className="crm-stage-map" aria-label="Sales workflow stages">{stages.map((s,i)=><button key={s.id} className={focus===s.id?'active':''} onClick={()=>setFocus(focus===s.id?'':s.id)}><span>{i+1}</span><strong>{s.name}</strong><small>{all.filter(x=>x.stage_id===s.id&&x.status==='open').length} open · {s.probability}%</small></button>)}<div className="crm-stage-outcomes"><span><CheckCircle2 size={15}/>Won</span><span><XCircle size={15}/>Lost</span></div></div>
  {selectedStage?<section className="crm-stage-guide"><div><span className="crm-eyebrow">STAGE PLAYBOOK</span><h3>{selectedStage.name}</h3><p>{selectedStage.purpose||'Define the purpose and checklist in Manage stages.'}</p></div><ul>{selectedStage.checklist.map(item=><li key={item}>{item}</li>)}</ul><small>Follow-up: {selectedStage.followup_days===null?'manual':`${selectedStage.followup_days} days`} · Stalled after {selectedStage.stale_days} days</small></section>:<p className="crm-board-help">Click a stage above to see its playbook. Open an opportunity to work its checklist, record conversations, and plan the next step.</p>}
  <div className="crm-attention-filters">{([['all','All opportunities'],['overdue','Overdue follow-up'],['missing','No next activity'],['stalled','Stalled'],['high','High priority']] as [Attention,string][]).map(([key,label])=><button key={key} className={attention===key?'active':''} onClick={()=>{setAttention(key);if(key!=='all')onStatus('open');}}>{label}{key!=='all'&&<span>{all.filter(x=>attentionMatches(x,key,d.activities,stages,now)).length}</span>}</button>)}<small>{filtered.length} shown</small></div>
  {list?<section className="crm-panel crm-table-wrap"><table><thead><tr><th>Opportunity</th><th>Contact</th><th>Stage / outcome</th><th>Value</th><th>Owner</th><th>Next activity</th><th>Close date</th></tr></thead><tbody>{filtered.map(x=>{const next=followupState(x,d.activities,now);return <tr key={x.id}><td><button className="crm-table-link" onClick={()=>onOpen(x.id)}>{x.title}</button></td><td>{d.contacts.find(c=>c.id===x.contact_id)?.name}</td><td>{x.status==='open'?stages.find(s=>s.id===x.stage_id)?.name:x.status}</td><td>{currency(x.value_cents)}</td><td>{owner(x.owner_id)}</td><td className={next.state==='overdue'?'crm-danger':''}>{next.next?`${next.next.title} · ${date(next.next.due_at)}`:x.status==='open'?'Missing next step':'Closed'}</td><td>{x.expected_close?date(x.expected_close):'—'}</td></tr>;})}</tbody></table>{!filtered.length&&<p className="crm-column-empty">No opportunities match these filters.</p>}</section>:<div className="crm-board">{(status==='open'||status==='all')&&stages.map((s,i)=>{const items=filtered.filter(x=>x.stage_id===s.id&&x.status==='open');return <section className="crm-column" key={s.id} onDragOver={e=>{if(writable)e.preventDefault();}} onDrop={e=>{e.preventDefault();onMove(e.dataTransfer.getData('text/plain'),s.id);}}><header><div><span className="crm-stage-number">{i+1}</span><h2>{s.name}</h2><span>{items.length}</span></div><p>{currency(items.reduce((n,x)=>n+Number(x.value_cents),0))}<small>{s.probability}% probability</small></p><p className="crm-column-purpose">{s.purpose}</p></header><div>{items.map(card)}{!items.length&&<p className="crm-column-empty">{attention==='all'?'Drag an opportunity here':'No matching opportunities'}</p>}</div>{writable&&i===0&&<button className="crm-add-in-stage" onClick={onNew}><Plus size={15}/>Add opportunity</button>}</section>;})}{['won','lost'].filter(s=>status===s||status==='all').map(s=><section className={`crm-column is-${s}`} key={s}><header><div><h2>{s==='won'?'Won':'Lost'}</h2><span>{filtered.filter(x=>x.status===s).length}</span></div><p>{s==='won'?'Successful sales, ready for your next relationship.':'Keep the reason and learn from each outcome.'}</p></header><div>{filtered.filter(x=>x.status===s).map(card)}</div></section>)}</div>}
 </>;
}
