'use client';
import { useState } from 'react';
import type { CRMData, Deal } from '@/lib/crm/types';
import { currency } from '@/lib/core';
import { summarize } from '@/lib/crm/logic';
import { dateKey, daysInStage, isStalled } from '@/lib/crm/workflow';
export function SalesReports({d,deals,onOpen}:{d:CRMData;deals:Deal[];onOpen:(id:string)=>void}) {
 const today=dateKey(d.loadedAt,d.workspace.timezone),[from,setFrom]=useState(today.slice(0,8)+'01'),[to,setTo]=useState(today);
 const inRange=(value:string)=>{const day=dateKey(value,d.workspace.timezone);return (!from||day>=from)&&(!to||day<=to);};
 const valid=!from||!to||from<=to,closed=valid?deals.filter(x=>x.closed_at&&x.status!=='open'&&inRange(x.closed_at)):[],won=closed.filter(x=>x.status==='won'),stats=summarize(deals,d.stages),loss=closed.filter(x=>x.status==='lost');
 const cycles=won.map(x=>Math.max(0,(Date.parse(x.closed_at!)-Date.parse(x.created_at))/86400000));
 const avg=cycles.length?Math.round(cycles.reduce((a,b)=>a+b,0)/cycles.length):null;
 const now=Date.parse(d.loadedAt),stalled=deals.filter(x=>isStalled(x,d.stages.find(s=>s.id===x.stage_id),now));
 const groups=Array.from(new Set(closed.map(x=>x.source))).sort();
 return <>
  <div className="crm-section-tools"><form key={from+':'+to} className="crm-report-range" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setFrom(String(f.get('from')||''));setTo(String(f.get('to')||''));}}><label className="crm-inline-date">Closed from<input aria-label="Closed from" type="date" name="from" defaultValue={from}/></label><label className="crm-inline-date">Through<input aria-label="Closed through" type="date" name="to" defaultValue={to}/></label><button className="crm-btn crm-primary" type="submit">Apply dates</button><button className="crm-btn" type="button" onClick={()=>{setFrom('');setTo('');}}>All time</button></form><small>Uses workspace timezone · USD</small></div>
  {!valid&&<p role="alert" className="crm-form-error">The start date must be on or before the end date.</p>}
  <div className="crm-metrics">{[['Won value',currency(won.reduce((n,x)=>n+Number(x.value_cents),0)),`${won.length} won opportunities`],['Win rate',closed.length?`${Math.round(won.length/closed.length*100)}%`:'—','Won ÷ closed opportunities'],['Average sale',won.length?currency(won.reduce((n,x)=>n+Number(x.value_cents),0)/won.length):'—','Average won opportunity'],['Sales cycle',avg===null?'—':`${avg} days`,'Created to won']].map(([label,value,detail])=><section className="crm-metric" key={label}><div>{label}</div><strong>{value}</strong><small>{detail} · selected period</small></section>)}</div>
  <div className="crm-today-grid"><section className="crm-panel"><header><div><h2>Current pipeline health</h2><p>{currency(stats.value)} open · {currency(stats.weighted)} weighted forecast</p></div></header><div className="crm-bars">{[...d.stages].sort((a,b)=>a.pipeline_id.localeCompare(b.pipeline_id)||a.position-b.position).map(s=>{const items=deals.filter(x=>x.status==='open'&&x.stage_id===s.id),amount=items.reduce((n,x)=>n+Number(x.value_cents),0);return <div key={s.id}><div><span>{d.pipelines.length>1?d.pipelines.find(p=>p.id===s.pipeline_id)?.name+' / ':''}{s.name} · {items.length}</span><strong>{currency(amount)}</strong></div><span><i style={{width:`${stats.value?amount/stats.value*100:0}%`}}/></span></div>;})}</div><p className="crm-report-note">Current open opportunities, regardless of the closed-date range. Stage totals show today’s distribution, not historical conversion.</p></section><section className="crm-panel"><header><div><h2>Source performance</h2><p>Outcomes closed in the selected period</p></div></header><div className="crm-table-wrap"><table><thead><tr><th>Source</th><th>Won / closed</th><th>Won value</th></tr></thead><tbody>{groups.map(s=>{const rows=closed.filter(x=>x.source===s),wins=rows.filter(x=>x.status==='won');return <tr key={s}><td>{s}</td><td>{wins.length} / {rows.length}</td><td>{currency(wins.reduce((n,x)=>n+Number(x.value_cents),0))}</td></tr>;})}</tbody></table>{!groups.length&&<p className="crm-column-empty">No closed opportunities in this period.</p>}</div><header><h2>Loss reasons · {loss.length}</h2></header>{loss.map(x=><button className="crm-attention" key={x.id} onClick={()=>onOpen(x.id)}><span><strong>{x.title}</strong><small>{x.lost_reason}</small></span></button>)}</section></div>
  <section className="crm-panel crm-report-stalled"><header><div><h2>Stalled opportunities</h2><p>At or beyond the stage’s configured age limit</p></div><span className="crm-pill">{stalled.length}</span></header>{stalled.map(x=><button className="crm-attention" key={x.id} onClick={()=>onOpen(x.id)}><span><strong>{x.title}</strong><small>{d.stages.find(s=>s.id===x.stage_id)?.name} · {daysInStage(x,now)} days</small></span><strong>{currency(x.value_cents)}</strong></button>)}{!stalled.length&&<p className="crm-column-empty">No stalled opportunities.</p>}</section>
 </>;
}
