'use client';
import { useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, BarChart3, Building2, CalendarDays, Check, CheckCircle2, ChevronRight, Circle, Clock3, Download, Inbox, LayoutDashboard, ListTodo, Mail, Menu, Phone, Plus, Search, Settings2, Target, TrendingUp, Users, X } from 'lucide-react';
import BrandLogo from '@/components/brand-logo';
import { mutateCRM } from '@/app/crm/actions';
import { signOut } from '@/app/actions';
import { currency } from '@/lib/core';
import type { Activity, CRMData, Deal, Person } from '@/lib/crm/types';
import { calendarFile, csvCell, followupState, summarize } from '@/lib/crm/logic';
import { EditForm, Modal, type Edit, type Save } from './forms';
type View='today'|'leads'|'pipeline'|'contacts'|'companies'|'activities'|'reports'|'settings';
const navigation=[{id:'today',label:'Today',icon:LayoutDashboard},{id:'leads',label:'Lead inbox',icon:Inbox},{id:'pipeline',label:'Deals',icon:Target},{id:'contacts',label:'Contacts',icon:Users},{id:'companies',label:'Companies',icon:Building2},{id:'activities',label:'Activities',icon:CalendarDays},{id:'reports',label:'Reports',icon:BarChart3},{id:'settings',label:'Settings',icon:Settings2}] as const;
const subtitles:Record<View,string>={today:'A clear next step for every opportunity.',leads:'Turn new interest into a real conversation.',pipeline:'Your sales process. Your momentum.',contacts:'The people behind your business.',companies:'Keep every business relationship in view.',activities:'Make room for the conversations that move deals forward.',reports:'Understand what is moving, what is working, and what needs attention.',settings:'Shape the CRM around the way your team sells.'};
function download(name:string,body:string,type='text/csv;charset=utf-8') {const url=URL.createObjectURL(new Blob([body],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Empty({title,body}:{title:string;body:string}) {return <div className="crm-empty"><Target size={25}/><h3>{title}</h3><p>{body}</p></div>;}
export default function CRMWorkbench({data:d}:{data:CRMData}) {
 const router=useRouter(),[pending,startTransition]=useTransition();
 const [view,setView]=useState<View>('today'),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[owner,setOwner]=useState('all'),[source,setSource]=useState('all'),[pipeline,setPipeline]=useState(d.pipelines[0]?.id||''),[dealStatus,setDealStatus]=useState('open'),[activityFilter,setActivityFilter]=useState('open'),[contactStatus,setContactStatus]=useState('active'),[edit,setEdit]=useState<Edit|null>(null),[selected,setSelected]=useState<{kind:'deal'|'contact';id:string}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[lost,setLost]=useState<Deal|null>(null),[boardMode,setBoardMode]=useState(true);
 const writable=d.role!=='read_only',admin=['owner','administrator'].includes(d.role),now=new Date(d.loadedAt).getTime();
 const personMap=useMemo(()=>new Map(d.contacts.map(c=>[c.id,c])),[d.contacts]);
 const companies=useMemo(()=>new Map(d.companies.map(c=>[c.id,c])),[d.companies]);
 const stages=d.stages.filter(s=>s.pipeline_id===pipeline).sort((a,b)=>a.position-b.position);
 const fmtDate=(s:string|null,full=false)=>s?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',...(full?{hour:'numeric',minute:'2-digit'}:{}),timeZone:d.workspace.timezone}).format(new Date(s.length===10?s+'T12:00:00Z':s)):'No date';
 const ownerName=(id:string|null)=>d.team.find(t=>t.user_id===id)?.email.split('@')[0]||'Unassigned';
 const ownerMatches=(id:string|null)=>owner==='all'||(owner==='unassigned'?id===null:id===owner);
 const matches=(value:string)=>value.toLowerCase().includes(query.toLowerCase());
 const people=d.contacts.filter(c=>(view==='leads'?c.lifecycle==='lead':contactStatus==='active'?c.lifecycle!=='archived':contactStatus==='all'||c.lifecycle===contactStatus)&&ownerMatches(c.owner_id)&&(source==='all'||c.source===source)&&matches(`${c.name} ${c.email} ${c.phone} ${companies.get(c.company_id||'')?.name||''} ${c.tags.join(' ')}`));
 const filteredDeals=d.deals.filter(x=>ownerMatches(x.owner_id)&&(source==='all'||x.source===source)&&matches(`${x.title} ${personMap.get(x.contact_id)?.name||''} ${personMap.get(x.contact_id)?.email||''}`));
 const pipelineDeals=filteredDeals.filter(x=>x.pipeline_id===pipeline&&(dealStatus==='all'||x.status===dealStatus));
 const filteredActivities=d.activities.filter(x=>ownerMatches(x.owner_id)&&matches(`${x.title} ${personMap.get(x.contact_id||'')?.name||''}`));
 const activities=filteredActivities.filter(a=>activityFilter==='done'?!!a.completed_at:!a.completed_at&&(activityFilter!=='overdue'||new Date(a.due_at).getTime()<now)).sort((a,b)=>a.due_at.localeCompare(b.due_at));
 const stats=summarize(filteredDeals,d.stages);
 const overdue=filteredActivities.filter(a=>!a.completed_at&&new Date(a.due_at).getTime()<now);
 const missing=filteredDeals.filter(x=>x.status==='open'&&followupState(x,d.activities,now).state==='missing');
 const chosenDeal=selected?.kind==='deal'?d.deals.find(x=>x.id===selected.id):undefined;
 const chosenPerson=chosenDeal?personMap.get(chosenDeal.contact_id):selected?.kind==='contact'?personMap.get(selected.id):undefined;
 const selectedActivities=d.activities.filter(a=>chosenDeal?a.deal_id===chosenDeal.id:chosenPerson?a.contact_id===chosenPerson.id:false).sort((a,b)=>a.due_at.localeCompare(b.due_at));
 const selectedNotes=d.notes.filter(n=>chosenDeal?n.deal_id===chosenDeal.id:chosenPerson?n.contact_id===chosenPerson.id:false).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const save:Save=(operation,input,close)=>{setError('');setNotice('');startTransition(async()=>{try{const result=await mutateCRM(d.workspace.id,operation,input);if(!result.ok){setError(result.message);return;}setNotice(result.message);close?.();router.refresh();}catch{setError('Unable to save. Check your connection and try again.');}});};
 const open=(e:Edit)=>{setError('');setEdit(e);};
 const navigate=(v:View)=>{setView(v);setQuery('');setMobile(false);setSelected(null);};
 const exportContacts=()=>{const columns=['name','email','phone','source','job_title','tags'];download('workforge-contacts.csv',[columns.join(','),...people.map(c=>columns.map(k=>csvCell(c[k as keyof Person])).join(','))].join('\r\n'));};
 const exportDeals=()=>{const rows=[['Deal','Contact','Value USD','Status','Stage','Owner','Source','Expected close'],...pipelineDeals.map(x=>[x.title,personMap.get(x.contact_id)?.name,x.value_cents/100,x.status,d.stages.find(s=>s.id===x.stage_id)?.name,ownerName(x.owner_id),x.source,x.expected_close])];download('workforge-deals.csv',rows.map(r=>r.map(csvCell).join(',')).join('\r\n'));};
 function moveDeal(id:string,stageId:string){const deal=d.deals.find(x=>x.id===id);if(!deal||!writable||pending||deal.stage_id===stageId)return;save('move',{id:deal.id,stage_id:stageId,pipeline_id:pipeline,version:deal.updated_at});}
 function activityRow(a:Activity) {const late=!a.completed_at&&new Date(a.due_at).getTime()<now;return <div className="crm-activity-row" key={a.id}><button className="crm-complete" disabled={!writable||pending} aria-label={`${a.completed_at?'Reopen':'Complete'} ${a.title}`} onClick={()=>save('complete',{id:a.id,done:!a.completed_at})}>{a.completed_at?<CheckCircle2 size={22}/>:<Circle size={22}/>}</button><button className="crm-activity-title" onClick={()=>writable?open({kind:'activity',item:a}):a.deal_id?setSelected({kind:'deal',id:a.deal_id}):undefined}><strong>{a.title}</strong><span>{a.kind} · {personMap.get(a.contact_id||'')?.name||'General activity'} · {ownerName(a.owner_id)}{a.automatic?' · Automatic follow-up':''}</span>{a.outcome&&<small>{a.outcome}</small>}</button><div className="crm-activity-date"><span className={late?'crm-danger':''}>{fmtDate(a.due_at,true)}</span><button className="crm-icon" aria-label={`Download calendar event for ${a.title}`} onClick={()=>download('workforge-activity.ics',calendarFile(a),'text/calendar;charset=utf-8')}><Download size={15}/></button></div></div>;}
 function dealCard(x:Deal){const contact=personMap.get(x.contact_id),state=followupState(x,d.activities,now);return <button key={x.id} className="crm-deal-card" disabled={pending} draggable={writable&&!pending} onDragStart={e=>e.dataTransfer.setData('text/plain',x.id)} onClick={()=>setSelected({kind:'deal',id:x.id})}><span className="crm-card-source">{x.source}<span>{ownerName(x.owner_id).slice(0,2).toUpperCase()}</span></span><strong>{x.title}</strong><span className="crm-card-contact">{contact?.name||'Contact'}{contact?.company_id&&<> · {companies.get(contact.company_id)?.name}</>}</span><b>{currency(x.value_cents)}</b><span className={`crm-next ${state.state}`}><Clock3 size={14}/>{state.state==='closed'?x.status==='won'?'Won':'Lost':state.next?`${state.state==='overdue'?'Overdue · ':''}${fmtDate(state.next.due_at)}`:'No next activity'}</span></button>;}
 return <div className="crm-app">
 {mobile&&<button className="crm-scrim" aria-label="Close menu" onClick={()=>setMobile(false)}/>}
 <aside className={`crm-sidebar ${mobile?'is-open':''}`}><BrandLogo/><div className="crm-product">CRM <span>BETA</span></div><div className="crm-workspace"><span>WORKSPACE</span><select aria-label="CRM workspace" value={d.workspace.id} onChange={e=>router.push('/crm?workspace='+encodeURIComponent(e.target.value))}>{d.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><nav>{navigation.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>navigate(n.id)}><n.icon size={19}/>{n.label}{n.id==='leads'&&d.contacts.some(c=>c.lifecycle==='lead')&&<span className="crm-nav-count">{d.contacts.filter(c=>c.lifecycle==='lead').length}</span>}</button>)}</nav><div className="crm-sidebar-foot"><div><span className="crm-avatar">{ownerName(d.userId).slice(0,2).toUpperCase()}</span><span><strong>{ownerName(d.userId)}</strong><small>{d.role.replace('_',' ')} access</small></span></div><button onClick={async()=>{await signOut();router.push('/login');}}>Sign out</button></div></aside>
 <div className="crm-main"><header className="crm-topbar"><button className="crm-mobile-toggle crm-icon" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={21}/></button><span>WorkForge <ChevronRight size={14}/> <strong>CRM</strong></span><div><span className="crm-cloud-dot"/>Cloud saved{d.workspace.is_demo&&<span className="crm-demo-label">Demo workspace · sample data</span>}</div></header>
 <main className="crm-content"><div className="crm-heading"><div><div className="crm-eyebrow">{view==='today'?'YOUR SALES WORKSPACE':'WORKFORGE CRM'}</div><h1>{navigation.find(n=>n.id===view)?.label}</h1><p>{subtitles[view]}</p></div><div className="crm-actions">{writable&&<><button className="crm-btn" onClick={()=>open({kind:'activity'})}><Plus size={16}/>Activity</button><button className="crm-btn crm-primary" onClick={()=>open(view==='companies'?{kind:'company'}:view==='contacts'||view==='leads'?{kind:'contact'}:{kind:'deal'})}><Plus size={17}/>{view==='companies'?'Company':view==='contacts'||view==='leads'?'Contact':'Deal'}</button></>}</div></div>
 {(notice||error)&&<div className={`crm-banner ${error?'is-error':''}`} role={error?'alert':'status'}><span>{error||notice}</span><button className="crm-icon" aria-label="Dismiss message" onClick={()=>{setNotice('');setError('');}}><X size={16}/></button></div>}
 {view!=='settings'&&<div className="crm-toolbar"><label className="crm-search"><Search size={17}/><input aria-label="Search current view" placeholder="Search names, deals, companies…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by owner" value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All owners</option><option value="unassigned">Unassigned</option><option value={d.userId}>Assigned to me</option>{d.team.filter(t=>t.user_id!==d.userId&&t.is_active).map(t=><option key={t.user_id} value={t.user_id}>{ownerName(t.user_id)}</option>)}</select>{view!=='activities'&&view!=='companies'&&<select aria-label="Filter by source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{Array.from(new Set([...d.contacts.map(c=>c.source),...d.deals.map(x=>x.source)])).sort().map(s=><option key={s}>{s}</option>)}</select>}<span className="crm-timezone">Times: {d.workspace.timezone}</span></div>}
 {view==='today'&&<><div className="crm-metrics"><Metric label="Open pipeline" value={currency(stats.value)} detail={`${stats.open} active deals`} icon={<Target size={19}/>}/><Metric label="Weighted forecast" value={currency(stats.weighted)} detail="Based on stage probabilities" icon={<TrendingUp size={19}/>}/><Metric label="Overdue activities" value={String(overdue.length)} detail="Ready for your attention" icon={<Clock3 size={19}/>}/><Metric label="Missing next step" value={String(missing.length)} detail="Open deals without an activity" icon={<ListTodo size={19}/>}/></div><div className="crm-today-grid"><section className="crm-panel"><header><div><h2>Make your next move</h2><p>Upcoming and overdue activities</p></div><button className="crm-link" onClick={()=>navigate('activities')}>View all <ArrowRight size={15}/></button></header>{filteredActivities.filter(a=>!a.completed_at).sort((a,b)=>a.due_at.localeCompare(b.due_at)).slice(0,7).map(activityRow)}{!filteredActivities.some(a=>!a.completed_at)&&<Empty title="Your follow-ups are clear" body="Add an activity to plan your next conversation."/>}</section><section className="crm-panel"><header><div><h2>Keep deals moving</h2><p>Open deals without a next activity</p></div><span className="crm-pill">{missing.length}</span></header>{missing.slice(0,5).map(x=><button className="crm-attention" key={x.id} onClick={()=>setSelected({kind:'deal',id:x.id})}><span><strong>{x.title}</strong><small>{personMap.get(x.contact_id)?.name} · {currency(x.value_cents)}</small></span><ArrowRight size={17}/></button>)}{!missing.length&&<Empty title="Every deal has a next step" body="Keep the momentum going."/>}<div className="crm-tip"><span>THE WORKFORGE WAY</span><h3>A pipeline is only as good as its next conversation.</h3><p>Give every open deal an owner and a scheduled follow-up.</p></div></section></div></>}
 {view==='pipeline'&&<><div className="crm-section-tools"><div><select aria-label="Sales pipeline" value={pipeline} onChange={e=>setPipeline(e.target.value)}>{d.pipelines.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Deal status" value={dealStatus} onChange={e=>setDealStatus(e.target.value)}>{['open','won','lost','all'].map(s=><option key={s} value={s}>{s==='all'?'All deals':s[0].toUpperCase()+s.slice(1)+' deals'}</option>)}</select><span>{pipelineDeals.length} deals · <strong>{currency(pipelineDeals.reduce((n,x)=>n+Number(x.value_cents),0))}</strong></span></div><div><button className="crm-btn" onClick={()=>setBoardMode(!boardMode)}>{boardMode?'List view':'Board view'}</button><button className="crm-btn" onClick={exportDeals}><Download size={15}/>Export</button></div></div>{boardMode?<div className="crm-board">{stages.map((s,i)=>{const deals=pipelineDeals.filter(x=>x.stage_id===s.id);return <section className="crm-column" key={s.id} onDragOver={e=>{if(writable)e.preventDefault();}} onDrop={e=>{e.preventDefault();moveDeal(e.dataTransfer.getData('text/plain'),s.id);}}><header><div><span className="crm-stage-dot" style={{opacity:.45+i*.12}}/><h2>{s.name}</h2><span>{deals.length}</span></div><p>{currency(deals.reduce((n,x)=>n+Number(x.value_cents),0))}<small>{s.probability}% probability</small></p></header><div>{deals.map(dealCard)}{!deals.length&&<p className="crm-column-empty">No deals in this stage</p>}</div></section>;})}</div>:<div className="crm-panel crm-table-wrap"><table><thead><tr><th>Deal</th><th>Contact</th><th>Value</th><th>Stage</th><th>Status</th><th>Expected close</th></tr></thead><tbody>{pipelineDeals.map(x=><tr key={x.id}><td><button className="crm-table-link" onClick={()=>setSelected({kind:'deal',id:x.id})}>{x.title}</button></td><td>{personMap.get(x.contact_id)?.name}</td><td>{currency(x.value_cents)}</td><td>{d.stages.find(s=>s.id===x.stage_id)?.name}</td><td>{x.status}</td><td>{fmtDate(x.expected_close)}</td></tr>)}</tbody></table>{!pipelineDeals.length&&<Empty title="No matching deals" body="Adjust your filters or add your first opportunity."/>}</div>}</>}
 {(view==='contacts'||view==='leads')&&<><div className="crm-section-tools"><div><span>{people.length} {view==='leads'?'new leads':'contacts'}</span>{view==='contacts'&&<select aria-label="Contact lifecycle" value={contactStatus} onChange={e=>setContactStatus(e.target.value)}><option value="active">Active contacts</option><option value="lead">Leads</option><option value="qualified">Qualified</option><option value="customer">Customers</option><option value="archived">Archived</option><option value="all">All contacts</option></select>}</div><div>{writable&&<button className="crm-btn" onClick={()=>open({kind:'import'})}>Import CSV</button>}<button className="crm-btn" onClick={exportContacts}><Download size={15}/>Export</button></div></div><div className="crm-panel crm-table-wrap"><table><thead><tr><th>Contact</th><th>Company</th><th>Email / phone</th><th>Source</th><th>Owner</th><th>Status</th></tr></thead><tbody>{people.map(c=><tr key={c.id}><td><button className="crm-person" onClick={()=>setSelected({kind:'contact',id:c.id})}><span className="crm-person-avatar">{c.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span><strong>{c.name}</strong><small>{c.tags.join(' · ')||c.job_title||'Contact'}</small></span></button></td><td>{companies.get(c.company_id||'')?.name||'—'}</td><td><span className="crm-stack">{c.email||'No email'}<small>{c.phone||'No phone'}</small></span></td><td><span className="crm-pill">{c.source}</span></td><td>{ownerName(c.owner_id)}</td><td>{c.do_not_contact?<span className="crm-danger">Do not contact</span>:c.lifecycle}</td></tr>)}</tbody></table>{!people.length&&<Empty title="No matching contacts" body="Add a contact or import your existing relationships."/>}</div></>}
 {view==='companies'&&<div className="crm-company-grid">{d.companies.filter(c=>matches(`${c.name} ${c.industry} ${c.address}`)).map(c=><section className="crm-panel crm-company" key={c.id}><div className="crm-company-top"><span><Building2 size={23}/></span>{writable&&<button className="crm-link" onClick={()=>open({kind:'company',item:c})}>Edit</button>}</div><h2>{c.name}</h2><p>{c.industry||'Company'}</p><div>{c.phone&&<a href={`tel:${c.phone.replace(/[^\d+]/g,'')}`}>{c.phone}</a>}{c.website&&/^https?:\/\//i.test(c.website)&&<a href={c.website} target="_blank" rel="noreferrer">{c.website.replace(/^https?:\/\//,'')}</a>}<span>{c.address}</span></div><footer><strong>{d.contacts.filter(p=>p.company_id===c.id).length} contacts</strong><button className="crm-link" onClick={()=>{navigate('contacts');setOwner('all');setSource('all');setQuery(c.name);}}>View contacts <ArrowRight size={14}/></button></footer></section>)}{!d.companies.length&&<Empty title="Add your first company" body="Link contacts to a company for a complete relationship view."/>}</div>}
 {view==='activities'&&<><div className="crm-section-tools"><div className="crm-tabs">{[['open','Upcoming & overdue'],['overdue','Overdue'],['done','Completed']].map(([key,label])=><button key={key} className={activityFilter===key?'active':''} onClick={()=>setActivityFilter(key)}>{label}</button>)}</div><span>{activities.length} activities</span></div><section className="crm-panel">{activities.map(activityRow)}{!activities.length&&<Empty title="Nothing on this list" body="Schedule a call, task, email follow-up, or meeting."/>}</section></>}
 {view==='reports'&&<><div className="crm-report-note">All-time results for the selected owner, source, and search. Deal values use USD. Weighted pipeline is a forecast, not booked revenue.</div><div className="crm-metrics"><Metric label="Open pipeline" value={currency(stats.value)} detail={`${stats.open} deals`} icon={<Target size={19}/>}/><Metric label="Weighted pipeline" value={currency(stats.weighted)} detail="Value × stage probability" icon={<TrendingUp size={19}/>}/><Metric label="Won deal value" value={currency(stats.won)} detail={`${filteredDeals.filter(x=>x.status==='won').length} wins`} icon={<CheckCircle2 size={19}/>}/><Metric label="Win rate" value={stats.winRate===null?'—':`${stats.winRate}%`} detail="Won ÷ (won + lost)" icon={<BarChart3 size={19}/>}/></div><div className="crm-today-grid"><section className="crm-panel"><header><div><h2>Pipeline by stage</h2><p>Open deal value across all pipelines</p></div></header><div className="crm-bars">{d.stages.map(s=>{const amount=filteredDeals.filter(x=>x.status==='open'&&x.stage_id===s.id).reduce((n,x)=>n+Number(x.value_cents),0);return <div key={s.id}><div><span>{d.pipelines.find(p=>p.id===s.pipeline_id)?.name} / {s.name}</span><strong>{currency(amount)}</strong></div><span><i style={{width:`${stats.value?amount/stats.value*100:0}%`}}/></span></div>;})}</div></section><section className="crm-panel"><header><div><h2>Lead source performance</h2><p>Deal results by original source</p></div></header><div className="crm-table-wrap"><table><thead><tr><th>Source</th><th>Deals</th><th>Won value</th></tr></thead><tbody>{Array.from(new Set(filteredDeals.map(x=>x.source))).map(s=><tr key={s}><td>{s}</td><td>{filteredDeals.filter(x=>x.source===s).length}</td><td>{currency(filteredDeals.filter(x=>x.source===s&&x.status==='won').reduce((n,x)=>n+Number(x.value_cents),0))}</td></tr>)}</tbody></table></div><header><h2>Loss reasons</h2></header>{filteredDeals.filter(x=>x.status==='lost').map(x=><div className="crm-report-loss" key={x.id}><strong>{x.title}</strong><p>{x.lost_reason}</p></div>)}</section></div></>}
 {view==='settings'&&<div className="crm-settings"><section className="crm-panel"><header><div><h2>Pipelines & follow-up rules</h2><p>Customize your stages and default win probabilities.</p></div>{admin&&<button className="crm-btn" onClick={()=>open({kind:'pipeline'})}><Plus size={15}/>Pipeline</button>}</header>{d.pipelines.map(p=><div className="crm-pipeline-settings" key={p.id}><h3>{p.name}</h3>{d.stages.filter(s=>s.pipeline_id===p.id).sort((a,b)=>a.position-b.position).map(s=><div key={s.id}><strong>{s.position+1}. {s.name}</strong><span>{s.probability}% win probability</span><span>{s.followup_days===null?'Automatic follow-up off':`Follow-up in ${s.followup_days} days`}</span>{admin&&<button className="crm-link" onClick={()=>open({kind:'stage',pipelineId:p.id,item:s})}>Edit</button>}</div>)}{admin&&<button className="crm-link" onClick={()=>open({kind:'stage',pipelineId:p.id})}><Plus size={15}/>Add stage</button>}</div>)}</section><section className="crm-panel"><header><div><h2>Team access</h2><p>Members share this workspace; read-only users cannot change records.</p></div>{admin&&<button className="crm-btn" onClick={()=>open({kind:'member'})}>Add user</button>}</header>{d.team.map(t=><div className="crm-team-row" key={t.user_id}><span>{t.email}</span><span className="crm-pill">{t.role.replace('_',' ')}{!t.is_active?' · inactive':''}</span></div>)}</section><section className="crm-panel"><header><div><h2>Connections</h2><p>This standalone CRM currently uses manual entry and CSV import.</p></div></header><div className="crm-connections">{[['Google / Meta leads','Not connected to this CRM workspace. HQ lead routing remains separate.'],['Email & SMS','Not connected. Contact shortcuts open your email or phone app. CRM email activities are reminders, not sent messages.'],['Calendar','Download any activity as a calendar event. Two-way calendar sync is not connected.']].map(([title,text])=><div key={title}><strong>{title}</strong><p>{text}</p><span className="crm-pill">Setup required</span></div>)}</div></section></div>}
 <footer className="crm-footer"><span>WorkForge CRM</span><span>Your relationships. Your process. Your growth.</span></footer></main></div>
 {selected&&(chosenDeal||chosenPerson)&&<Modal title={chosenDeal?'Deal details':'Contact details'} onClose={()=>setSelected(null)}><div className="crm-detail"><div className="crm-detail-heading"><div><span className="crm-eyebrow">{chosenDeal?chosenDeal.status:'RELATIONSHIP'}</span><h2>{chosenDeal?.title||chosenPerson?.name}</h2><p>{chosenDeal?currency(chosenDeal.value_cents):chosenPerson?.job_title||chosenPerson?.source}</p></div>{writable&&<button className="crm-btn" onClick={()=>open(chosenDeal?{kind:'deal',item:chosenDeal}:{kind:'contact',item:chosenPerson})}>Edit details</button>}</div>
 {chosenDeal&&<><div className="crm-deal-controls"><label>Pipeline stage<select value={chosenDeal.stage_id} disabled={!writable||pending} onChange={e=>save('move',{id:chosenDeal.id,pipeline_id:chosenDeal.pipeline_id,stage_id:e.target.value,version:chosenDeal.updated_at})}>{d.stages.filter(s=>s.pipeline_id===chosenDeal.pipeline_id).sort((a,b)=>a.position-b.position).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>{writable&&<div>{chosenDeal.status!=='won'&&<button className="crm-btn crm-success" disabled={pending} onClick={()=>save('status',{id:chosenDeal.id,status:'won',lost_reason:'',version:chosenDeal.updated_at})}><Check size={15}/>Mark won</button>}{chosenDeal.status!=='lost'&&<button className="crm-btn" disabled={pending} onClick={()=>setLost(chosenDeal)}>Mark lost</button>}{chosenDeal.status!=='open'&&<button className="crm-btn" disabled={pending} onClick={()=>save('status',{id:chosenDeal.id,status:'open',lost_reason:'',version:chosenDeal.updated_at})}>Reopen</button>}</div>}</div>{chosenDeal.lost_reason&&<p className="crm-loss-reason">Loss reason: {chosenDeal.lost_reason}</p>}<div className="crm-detail-facts"><span>Owner<strong>{ownerName(chosenDeal.owner_id)}</strong></span><span>Expected close<strong>{fmtDate(chosenDeal.expected_close)}</strong></span><span>Source<strong>{chosenDeal.source}</strong></span></div></>}
 {chosenPerson&&<div className="crm-contact-summary"><div><strong>{chosenPerson.name}</strong><span>{companies.get(chosenPerson.company_id||'')?.name||'Individual contact'}</span></div>{chosenPerson.do_not_contact?<span className="crm-danger">Do not contact</span>:<div>{chosenPerson.email&&<a className="crm-btn" href={`mailto:${chosenPerson.email}`}><Mail size={15}/>Email</a>}{chosenPerson.phone&&<a className="crm-btn" href={`tel:${chosenPerson.phone.replace(/[^\d+]/g,'')}`}><Phone size={15}/>Call</a>}</div>}</div>}
 {!chosenDeal&&chosenPerson&&<><div className="crm-section-tools"><h3>Deals</h3>{writable&&<button className="crm-link" onClick={()=>open({kind:'deal',contactId:chosenPerson.id})}><Plus size={15}/>Create deal</button>}</div>{d.deals.filter(x=>x.contact_id===chosenPerson.id).map(x=><button className="crm-attention" key={x.id} onClick={()=>setSelected({kind:'deal',id:x.id})}><span><strong>{x.title}</strong><small>{x.status} · {currency(x.value_cents)}</small></span><ChevronRight size={16}/></button>)}</>}
 <div className="crm-section-tools"><h3>Activities</h3>{writable&&<button className="crm-link" onClick={()=>open({kind:'activity',dealId:chosenDeal?.id,contactId:chosenPerson?.id})}><Plus size={15}/>Schedule</button>}</div>{selectedActivities.map(activityRow)}{!selectedActivities.length&&<p className="crm-help">No activities yet. Schedule the next conversation.</p>}
 <h3 className="crm-detail-subtitle">Notes</h3>{writable&&<form className="crm-note-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const body=String(new FormData(form).get('body')||'');save('note',{body,contact_id:chosenPerson?.id||null,deal_id:chosenDeal?.id||null},()=>form.reset());}}><textarea name="body" required maxLength={10000} rows={3} placeholder="What did you learn? What happens next?" aria-label="New note"/><button disabled={pending} className="crm-btn">Add note</button></form>}{selectedNotes.map(n=><article className="crm-note" key={n.id}><p>{n.body}</p><small>{ownerName(n.author_id)} · {fmtDate(n.created_at,true)}</small></article>)}
 <h3 className="crm-detail-subtitle">History</h3>{d.history.filter(h=>h.record_id===selected.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,20).map(h=><div className="crm-history" key={h.id}><span>{h.description}</span><small>{fmtDate(h.created_at,true)}</small></div>)}{error&&<p className="crm-form-error" role="alert">{error}</p>}
 </div></Modal>}
 {edit&&<EditForm key={edit.kind+('item'in edit?edit.item?.id||'':'')} edit={edit} d={d} save={save} onClose={()=>setEdit(null)} busy={pending} error={error}/>}
 {lost&&<Modal title="Record a lost deal" onClose={()=>setLost(null)}><form onSubmit={e=>{e.preventDefault();save('status',{id:lost.id,status:'lost',lost_reason:String(new FormData(e.currentTarget).get('reason')),version:lost.updated_at},()=>setLost(null));}}><label className="crm-field"><span>Why was this deal lost?</span><textarea autoFocus name="reason" required rows={3} maxLength={1000}/></label>{error&&<p className="crm-form-error">{error}</p>}<footer><button className="crm-btn" type="button" onClick={()=>setLost(null)}>Cancel</button><button className="crm-btn crm-primary" disabled={pending}>Mark lost</button></footer></form></Modal>}
 </div>;
}
function Metric({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <section className="crm-metric"><div><span>{label}</span>{icon}</div><strong>{value}</strong><small>{detail}</small></section>;}
