'use client';
import BrandLogo from '@/components/brand-logo';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowDownToLine, ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, Hammer, LayoutDashboard, Menu, Plus, Search, Settings2, ShieldCheck, ShoppingCart, Users, X, LogOut, CircleCheck, Clock3 } from 'lucide-react';
import { FieldBoard, Pricebook, Customers, Partners, FieldReports } from './field/views';
import { JobWorkspace } from './field/job-workspace';
import { mutate, signOut } from '@/app/actions';
import { canWrite, currency, dateLabel, MODEL_PROFILES, nextStage, priceForMargin, STAGES, STAGE_LABELS, type DataSet, type Stage, type Workspace, type WorkOrder } from '@/lib/core';
type View='overview'|'pipeline'|'production'|'schedule'|'contacts'|'partners'|'purchases'|'pricebook'|'reports'|'models';
type FormKind='lead'|'contact'|'partner'|'task'|'appointment'|'purchase'|'costs'|'schedule'|'approval';
const NAV=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'pipeline',label:'Sales pipeline',icon:ClipboardList},{id:'production',label:'Production',icon:Hammer},{id:'schedule',label:'Schedule',icon:CalendarDays},{id:'contacts',label:'Customers',icon:Users},{id:'partners',label:'Crews & vendors',icon:Hammer},{id:'purchases',label:'Purchasing',icon:ShoppingCart},{id:'pricebook',label:'Pricebook',icon:ClipboardList},{id:'reports',label:'Reports',icon:LayoutDashboard},{id:'models',label:'Platform models',icon:Settings2}] as const;
const TODAY=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current;if(d&&!d.open)d.showModal();return()=>{if(d?.open)d.close();};},[]);
  return <dialog ref={ref} className={wide?'modal wide-modal':'modal'} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header>{children}</dialog>;
}
export default function Workbench({data:d,workspaces}:{data:DataSet;workspaces:Workspace[]}){
  const router=useRouter();const [view,setView]=useState<View>('overview');const [search,setSearch]=useState('');const [selected,setSelected]=useState<string|null>(null);const [form,setForm]=useState<FormKind|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [mobile,setMobile]=useState(false);const [stageFilter,setStageFilter]=useState('all');
  const [purchaseKind,setPurchaseKind]=useState('materials');
  const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7));
  const writable=canWrite(d.role);const current=d.orders.find(o=>o.id===selected);const customer=(o:WorkOrder)=>d.contacts.find(c=>c.id===o.contact_id);const quote=(o:WorkOrder)=>d.estimates.filter(e=>e.work_order_id===o.id).sort((a,b)=>b.version-a.version)[0];
  const approved=d.estimates.filter(e=>e.status==='approved');const active=d.orders.filter(o=>['approved','scheduled','in_progress'].includes(o.stage));const pending=d.orders.filter(o=>o.stage==='estimated');
  const filtered=d.orders.filter(o=>(stageFilter==='all'||o.stage===stageFilter)&&`${o.title} ${customer(o)?.name} WF-${o.number}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.number-a.number);
  const openTasks=d.tasks.filter(t=>!t.completed);const selectedEstimate=current?quote(current):undefined;
  const events=[...d.appointments.map(a=>({id:a.id,date:a.starts_at,title:a.title,orderId:a.work_order_id,type:'Consultation'})),...d.orders.filter(o=>o.scheduled_at).map(o=>({id:o.id,date:o.scheduled_at!,title:o.title,orderId:o.id,type:'Production'}))].sort((a,b)=>a.date.localeCompare(b.date));
  const dateKey=(date:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:d.workspace.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date));
  const upcoming=events.filter(e=>e.date>=new Date().toISOString()).slice(0,4);
  function show(kind:FormKind){setError('');setForm(kind);}
  async function run(action:string,fd:FormData,close=true){setSaving(true);setError('');setMessage('');try{const result=await mutate(d.workspace.id,action,fd);if(!result.ok){setError(result.error??'Unable to save.');return;}setMessage('Changes saved.');if(close)setForm(null);if(result.id)setSelected(result.id);router.refresh();}catch{setError('The connection was interrupted. Please retry.');}finally{setSaving(false);}}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);for(const key of ['starts_at','ends_at','scheduled_at']){const v=fd.get(key);if(v)fd.set(key,new Date(String(v)).toISOString());}const kind=form==='approval'?'advance':form!;await run(kind,fd);}
  function advance(o:WorkOrder){const next=nextStage(o.stage);if(!next)return;if(next==='approved'){show('approval');return;}const fd=new FormData();fd.set('work_order_id',o.id);fd.set('expected_stage',o.stage);fd.set('next_stage',next);void run('advance',fd,false);}
  function toggleTask(id:string,completed:boolean){const fd=new FormData();fd.set('id',id);fd.set('completed',String(completed));void run('toggle_task',fd,false);}
  function changeMonth(n:number){const [y,m]=month.split('-').map(Number);setMonth(new Date(Date.UTC(y,m-1+n,1)).toISOString().slice(0,7));}
  function orderTable(orders:WorkOrder[]){return <div className="table-wrap"><table><thead><tr><th>Work order</th><th>Customer</th><th>Status</th><th>Estimate</th><th>Schedule</th><th aria-label="Open"/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><button className="record-link" onClick={()=>{setSelected(o.id);setError('');}}><small>WF-{o.number}</small>{o.title}</button></td><td>{customer(o)?.name??'—'}</td><td><span className={`status ${o.stage}`}>{STAGE_LABELS[o.stage]}</span></td><td className="amount">{quote(o)?currency(quote(o)!.price_cents):'Not priced'}</td><td>{o.scheduled_at?dateLabel(o.scheduled_at,d.workspace.timezone):'Unscheduled'}</td><td><button className="icon-button" aria-label={`Open ${o.title}`} onClick={()=>setSelected(o.id)}><ArrowRight size={17}/></button></td></tr>)}</tbody></table>{!orders.length&&<div className="empty"><ClipboardList/><h3>No work orders here yet.</h3><p>Add a lead to start the workflow.</p></div>}</div>;}
  return <div className="app-shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="sidebar-brand"><BrandLogo/><button className="icon-button mobile-close" aria-label="Close navigation" onClick={()=>setMobile(false)}><X/></button></div><div className="workspace-switch"><span>WORKSPACE</span><select aria-label="Workspace" value={d.workspace.id} onChange={e=>router.push(`/?workspace=${e.target.value}`)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><small>WorkForge {MODEL_PROFILES[d.workspace.model].name}</small></div><nav>{NAV.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>{setView(n.id);setMobile(false);setSearch('');setStageFilter('all');}}><n.icon size={19}/>{n.label}{n.id==='pipeline'&&<span>{d.orders.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="core-label"><ShieldCheck size={17}/><div>Dedicated workspace<small>Field 0.2 · {d.role.replace('_',' ')}</small></div></div><button className="logout" onClick={async()=>{await signOut();router.push('/login');}}><LogOut size={17}/>Sign out</button></div></aside>{mobile&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu/></button><span>Operations</span><ChevronRight size={14}/><strong>WorkForge Field</strong></div><div className="topbar-right">{d.workspace.is_demo&&<span className="demo-badge">Demonstration · sample data</span>}<div className="avatar">WF</div></div></header><main className="main"><div className="page-heading"><div><p className="eyebrow">{view==='overview'?'YOUR BUSINESS, IN VIEW':d.workspace.name.toUpperCase()}</p><h1>{NAV.find(n=>n.id===view)?.label}</h1><p>{({overview:'See what needs attention. Keep the next step moving.',pipeline:'Qualified leads, next actions and proposals ready to win.',production:'Approved work, people and materials moving together.',pricebook:'Reusable services, material costs and margin-based pricing.',reports:'Sales performance, job costs and recorded collections.',schedule:'Consultations and production, connected to the work.',contacts:'The people and businesses behind your work.',partners:'Your crews, subcontractors and material suppliers.',purchases:'Track the materials each job needs.',models:'One reusable foundation. Five configurable starting points.'})[view]}</p></div><div className="heading-actions">{view==='pipeline'&&<a className="button secondary" href={`/api/export?workspace=${d.workspace.id}`}><ArrowDownToLine size={17}/>Export</a>}{writable&&!['models','pricebook','reports','production'].includes(view)&&<button className="primary" onClick={()=>{if(view!=='purchases')setSelected(null);show(view==='contacts'?'contact':view==='partners'?'partner':view==='purchases'?'purchase':view==='schedule'?'appointment':'lead');}}><Plus size={18}/>{view==='contacts'?'Add contact':view==='partners'?'Add partner':view==='purchases'?'Add purchase':view==='schedule'?'Add consultation':'New lead'}</button>}</div></div>
  {message&&<div className="toast" role="status"><CircleCheck size={17}/>{message}<button className="icon-button" aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}{error&&!form&&!current&&<p className="error" role="alert">{error}</p>}
  {view==='overview'&&<><section className="metrics"><div className="metric"><span>Approved work</span><strong>{currency(approved.reduce((s,q)=>s+q.price_cents,0))}</strong><small>Accepted estimate value · all time</small></div><div className="metric"><span>Active jobs</span><strong>{active.length.toString().padStart(2,'0')}</strong><small>Approved, scheduled or in progress</small></div><div className="metric"><span>Awaiting approval</span><strong>{pending.length.toString().padStart(2,'0')}</strong><small>{currency(pending.reduce((s,o)=>s+(quote(o)?.price_cents??0),0))} in estimates</small></div><div className="metric"><span>Open tasks</span><strong>{openTasks.length.toString().padStart(2,'0')}</strong><small>Across your workspace</small></div></section><div className="overview-grid"><section className="panel attention"><div className="section-heading"><div><span className="eyebrow">KEEP WORK MOVING</span><h2>Your next steps</h2></div><span className="count">{openTasks.length}</span></div><div className="task-list">{d.tasks.slice().sort((a,b)=>Number(a.completed)-Number(b.completed)).slice(0,7).map(t=><div className={`task ${t.completed?'done':''}`} key={t.id}><input type="checkbox" aria-label={`Complete ${t.title}`} checked={t.completed} disabled={!writable||saving} onChange={e=>toggleTask(t.id,e.target.checked)}/><div><button className="text-button" disabled={!t.work_order_id} onClick={()=>setSelected(t.work_order_id)}>{t.title}</button><small>{t.due_on?`Due ${t.due_on}`:'No due date'}{t.work_order_id?' · Linked job':''}</small></div></div>)}{!d.tasks.length&&<p className="empty-note">No tasks yet. Add the next action your team needs to take.</p>}</div>{writable&&<button className="quiet" onClick={()=>{setSelected(null);show('task');}}><Plus size={16}/>Add a task</button>}</section><section className="panel schedule-preview"><div className="section-heading"><div><span className="eyebrow">ON THE CALENDAR</span><h2>Coming up</h2></div><button className="icon-button" aria-label="Open schedule" onClick={()=>setView('schedule')}><ArrowRight/></button></div>{upcoming.map(e=><button className="event-preview" key={e.id} onClick={()=>setSelected(e.orderId)}><div className="event-icon"><CalendarDays size={19}/></div><div><small>{dateLabel(e.date,d.workspace.timezone)}</small><strong>{e.title}</strong><span>{e.type}</span></div></button>)}{!upcoming.length&&<p className="empty-note">No upcoming appointments. Open a lead to schedule a consultation.</p>}</section></div><section className="panel"><div className="section-heading"><div><span className="eyebrow">FROM LEAD TO DELIVERY</span><h2>Work in motion</h2></div><button className="quiet" onClick={()=>setView('pipeline')}>View all work<ArrowRight size={16}/></button></div>{orderTable(d.orders.filter(o=>o.stage!=='invoice_ready').slice(0,6))}</section></>}
  {view==='pipeline'&&<FieldBoard data={d} mode="sales" onOpen={setSelected}/>}
  {view==='production'&&<FieldBoard data={d} mode="operations" onOpen={setSelected}/>}
  {view==='pricebook'&&<Pricebook data={d}/>}
  {view==='reports'&&<FieldReports data={d} onOpen={setSelected}/>}
  {view==='schedule'&&<section className="panel calendar-panel"><div className="section-heading"><div><h2>{new Date(month+'-01T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</h2><small>Times shown in {d.workspace.timezone}</small></div><div className="button-row"><button className="icon-button" aria-label="Previous month" onClick={()=>changeMonth(-1)}><ChevronLeft/></button><button className="secondary" onClick={()=>setMonth(new Date().toISOString().slice(0,7))}>Today</button><button className="icon-button" aria-label="Next month" onClick={()=>changeMonth(1)}><ChevronRight/></button></div></div><div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><div className="day-heading" key={day}>{day}</div>)}{Array.from({length:42},(_,i)=>{const first=new Date(month+'-01T12:00:00Z');const day=new Date(first);day.setUTCDate(i-first.getUTCDay()+1);const key=day.toISOString().slice(0,10);const dayEvents=events.filter(e=>dateKey(e.date)===key);return <div key={key} className={`calendar-cell ${key.slice(0,7)!==month?'other-month':''} ${key===TODAY()?'today':''}`}><span className="day-number">{day.getUTCDate()}</span>{dayEvents.map(e=><button className={`calendar-event ${e.type==='Production'?'production':''}`} key={e.id} onClick={()=>setSelected(e.orderId)}><small>{new Date(e.date).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:d.workspace.timezone})}</small>{e.title}</button>)}</div>;})}</div><div className="calendar-mobile-list">{events.filter(e=>dateKey(e.date).startsWith(month)).map(e=><button className="event-preview" key={e.id} onClick={()=>setSelected(e.orderId)}><CalendarDays/><div><small>{dateLabel(e.date,d.workspace.timezone)}</small><strong>{e.title}</strong><span>{e.type}</span></div></button>)}</div></section>}
  {view==='contacts'&&<Customers data={d} onOpen={setSelected}/>}
  {view==='partners'&&<Partners data={d}/>}
  {view==='purchases'&&<section className="panel"><div className="section-heading"><h2>Job purchases</h2><span className="muted">{currency(d.purchases.reduce((s,p)=>s+p.cost_cents,0))} planned + ordered + received</span></div><div className="table-wrap"><table><thead><tr><th>Order / scope</th><th>Job</th><th>Vendor</th><th>Cost</th><th>Status</th></tr></thead><tbody>{d.purchases.map(p=><tr key={p.id}><td><small>PO-{p.po_number} · {p.order_kind}</small><br/>{p.description}</td><td><button className="text-button inline-link" onClick={()=>setSelected(p.work_order_id)}>{d.orders.find(o=>o.id===p.work_order_id)?.title}</button></td><td>{d.partners.find(v=>v.id===p.partner_id)?.name}</td><td className="amount">{currency(p.cost_cents)}</td><td><select aria-label={`Status of ${p.description}`} value={p.status} disabled={!writable||saving} onChange={e=>{const fd=new FormData();fd.set('id',p.id);fd.set('status',e.target.value);void run('purchase_status',fd,false);}}>{['planned','ordered','received'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table>{!d.purchases.length&&<div className="empty">No purchases yet.</div>}</div></section>}
  {view==='models'&&<><div className="notice"><ShieldCheck size={20}/><div><strong>Shared Core · dedicated client environments</strong><p>The Field demonstration is the first working model. The other profiles define the next reusable modules; their workflows are not enabled yet.</p></div></div><div className="model-grid">{Object.entries(MODEL_PROFILES).map(([key,m])=><section key={key} className={`panel model-card ${key==='field'?'current':''}`}><span className="chip">{key==='field'?'Available in this build':'Planned accelerator'}</span><h2>WorkForge {m.name}</h2><p>{m.audience}</p><div className="module-tags">{m.modules.map(n=><span key={n}>{n.replaceAll('_',' ')}</span>)}</div></section>)}</div><section className="panel setup-panel"><h2>Connections</h2><div><span>Database and workspace records</span><strong>Connected</strong></div><div><span>Accounting handoff</span><span>CSV preparation · connector pending</span></div><div><span>Google Calendar, email and SMS workflows</span><span>Not connected</span></div><div><span>Customer e-signature</span><span>Demo approval only</span></div></section></>}
  <footer className="page-footer"><span>WorkForge OS · built around the way you work</span><span>{d.workspace.is_demo?'Fictional demonstration company':'Dedicated workspace'}</span></footer></main></div>
  {current&&!form&&<Modal wide title={`WF-${current.number} · ${current.title}`} onClose={()=>{setSelected(null);setError('');}}><JobWorkspace key={current.id} data={d} order={current} onAdvance={()=>advance(current)} onShow={show} onToggle={toggleTask} saving={saving} error={error}/></Modal>}
  {form&&<Modal title={({'lead':'New lead','contact':'Add contact','partner':'Add crew or vendor','task':'Add a task','appointment':'Schedule a consultation','purchase':'Add a job purchase','costs':'Estimate budget','schedule':'Schedule production','approval':'Record demonstration approval'})[form]} onClose={()=>{if(!saving){setForm(null);setError('');}}}><form className="data-form" onSubmit={submit}>{current&&<input type="hidden" name="work_order_id" value={current.id}/>}{error&&<p className="error" role="alert">{error}</p>}
  {form==='lead'&&<><label>Job name<input name="title" placeholder="e.g. Exterior repaint" required maxLength={200}/></label><label>Customer name<input name="contact_name" required maxLength={200}/></label><div className="form-grid"><label>Email<input name="email" type="email" maxLength={254}/></label><label>Phone<input name="phone" type="tel" maxLength={40}/></label></div><label>Job address<input name="address" maxLength={400}/></label><label>Scope / notes<textarea name="description" rows={3}/></label></>}
  {form==='contact'&&<><label>Name<input name="name" required maxLength={200}/></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone" type="tel"/></label><label>Address<input name="address"/></label></>}
  {form==='partner'&&<><label>Name<input name="name" required maxLength={200}/></label><label>Type<select name="kind"><option value="crew">Employee crew</option><option value="subcontractor">Subcontractor</option><option value="vendor">Material vendor</option></select></label><label>Phone<input name="phone" type="tel"/></label></>}
  {form==='task'&&<><label>Next action<input name="title" required maxLength={300}/></label><label>Due date<input type="date" name="due_on"/></label>{current&&<p className="muted">Linked to WF-{current.number}</p>}</>}
  {(form==='appointment'||form==='purchase')&&!current&&<label>Work order<select name="work_order_id" required><option value="">Select a job</option>{d.orders.map(o=><option key={o.id} value={o.id}>WF-{o.number} · {o.title}</option>)}</select></label>}
  {form==='appointment'&&<><label>Appointment title<input name="title" defaultValue={current?`Consultation · ${current.title}`:'Consultation'} required/></label><div className="form-grid"><label>Start<input type="datetime-local" name="starts_at" required/></label><label>End<input type="datetime-local" name="ends_at" required/></label></div><p className="muted small">Enter local time on this device.</p></>}
  {form==='purchase'&&<><label>Order type<select name="order_kind" value={purchaseKind} onChange={e=>setPurchaseKind(e.target.value)}><option value="materials">Materials purchase</option><option value="subcontract">Subcontract work order</option></select></label><label>Vendor / crew<select name="partner_id" required><option value="">Select a vendor</option>{d.partners.filter(p=>purchaseKind==='materials'?p.kind==='vendor':p.kind!=='vendor').map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Materials / scope<input name="description" required maxLength={500}/></label><label>Cost ($)<input name="cost" type="number" min="0.01" step="0.01" required/></label><label>Delivery / work date<input name="delivery_on" type="date"/></label><label>Reference<input name="reference" maxLength={200}/></label><label>Delivery instructions / scope notes<textarea name="notes" rows={3} maxLength={5000}/></label></>}
  {form==='costs'&&current&&<><label>Scope of work<textarea name="description" rows={4} defaultValue={current.description}/></label><div className="form-grid"><label>Labor cost ($)<input name="labor_cost" type="number" min="0" step="0.01" defaultValue={current.labor_cost_cents/100} required/></label><label>Material cost ($)<input name="material_cost" type="number" min="0" step="0.01" defaultValue={current.material_cost_cents/100} required/></label></div><label>Target gross margin (%)<input name="target_margin" type="number" min="0" max="99.99" step="0.01" defaultValue={current.target_margin} required/></label><div className="notice small">Price = total cost ÷ (1 − margin). An accepted estimate cannot be edited.</div></>}
  {form==='schedule'&&<><label>Production start<input name="scheduled_at" type="datetime-local" required/></label><label>Crew / subcontractor<select name="partner_id" defaultValue={current?.assigned_partner_id??''} required><option value="">Select a crew</option>{d.partners.filter(p=>p.kind!=='vendor').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="muted small">Enter local time on this device. Save the assignment, then confirm the schedule on the job.</p></>}
  {form==='approval'&&current&&<><div className="notice"><ShieldCheck/><p>This simulates customer approval for the demonstration. No approval request will be sent and no electronic signature will be collected.</p></div><input type="hidden" name="expected_stage" value={current.stage}/><input type="hidden" name="next_stage" value="approved"/><label>Simulated approving customer<input name="approver" defaultValue={customer(current)?.name} required minLength={2}/></label><p>Estimate amount: <strong>{currency(selectedEstimate?.price_cents??0)}</strong></p></>}
  <div className="form-footer"><button type="button" className="secondary" disabled={saving} onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':form==='approval'?'Record demo approval':'Save'}</button></div></form></Modal>}
  </div>;
}
