'use client';
import { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { canWrite, priceForMargin, type DataSet, type WorkOrder } from '@/lib/core';
import { latestEstimate, lineAmount, money, quoteTotals, type EstimateLine } from '@/lib/field';
import { SaveForm } from './forms';
const blank=():EstimateLine=>({id:crypto.randomUUID(),product_id:null,name:'',description:'',quantity:1,unit:'each',material_cents:0,labor_cents:0,unit_price_cents:0,taxable:false});

export function EstimateEditor({data:d,order:o}:{data:DataSet;order:WorkOrder}){
 const initial:EstimateLine[]=o.estimate_lines?.length?o.estimate_lines:[{id:'legacy-budget',product_id:null,name:o.title,description:o.description,quantity:1,unit:'job',material_cents:o.material_cost_cents,labor_cents:o.labor_cost_cents,unit_price_cents:priceForMargin(o.labor_cost_cents+o.material_cost_cents,Number(o.target_margin)),taxable:false}];
 const [lines,setLines]=useState(initial);const [margin,setMargin]=useState(Number(o.target_margin));const [discount,setDiscount]=useState(Number(o.discount_percent??0));const [tax,setTax]=useState(Number(o.tax_rate??0));const [deposit,setDeposit]=useState(Number(o.deposit_percent??0));const [calculationError,setCalculationError]=useState('');
 const editable=canWrite(d.role)&&['lead','appointment','estimated'].includes(o.stage);const latest=latestEstimate(d,o.id);
 let totals:ReturnType<typeof quoteTotals>|null=null,validation='';try{totals=quoteTotals(lines,discount,tax,deposit);}catch(e){validation=e instanceof Error?e.message:'Check the estimate items.';}
 function patch(id:string,value:Partial<EstimateLine>){setLines(old=>old.map(l=>l.id===id?{...l,...value}:l));}
 function addProduct(id:string){const p=d.pricebook.find(p=>p.id===id);if(!p)return;setLines(old=>[...old,{id:crypto.randomUUID(),product_id:p.id,name:p.name,description:p.description,unit:p.unit,quantity:1,material_cents:p.material_cents,labor_cents:p.labor_cents,unit_price_cents:priceForMargin(p.material_cents+p.labor_cents,Number(p.target_margin)),taxable:p.taxable}]);}
 return <div className="estimate-workspace"><div className="section-heading flush"><div><p className="eyebrow">SCOPE, COST & CUSTOMER PRICE</p><h3>Estimate builder</h3></div>{latest&&<a className="button secondary" href={`/estimates/${latest.id}`} target="_blank" rel="noreferrer">Preview proposal · r{latest.version}</a>}</div>
 {!editable&&<div className="notice">The accepted estimate is locked. Its saved proposal and revisions remain available below.</div>}
 <SaveForm workspaceId={d.workspace.id} orderId={o.id} action="field_estimate" writable={editable} label={o.stage==='estimated'?'Save new revision':'Save estimate items'} extra={{lines:JSON.stringify(lines),expected_updated_at:o.updated_at}}>
 <label>Scope of work<textarea name="description" rows={4} defaultValue={o.description} maxLength={10000}/></label>
 <div className="estimate-toolbar"><label>Add from pricebook<select aria-label="Add pricebook product" value="" onChange={e=>addProduct(e.target.value)}><option value="">Select a service or material…</option>{d.pricebook.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.category} · {p.name}</option>)}</select></label><button type="button" className="secondary" onClick={()=>setLines(old=>[...old,blank()])}><Plus size={16}/>Custom item</button></div>
 <div className="estimate-items">{lines.map((l,index)=><section className="estimate-item" key={l.id}><div className="item-title"><span className="item-number">{index+1}</span><label>Service / product<input aria-label={`Item ${index+1} name`} required maxLength={200} value={l.name} onChange={e=>patch(l.id,{name:e.target.value})}/></label><button type="button" className="icon-button" aria-label={`Remove item ${index+1}`} onClick={()=>setLines(old=>old.filter(x=>x.id!==l.id))}><Trash2 size={17}/></button></div><label>Customer description<textarea rows={2} value={l.description} maxLength={3000} onChange={e=>patch(l.id,{description:e.target.value})}/></label><div className="item-numbers"><label>Quantity<input aria-label={`Item ${index+1} quantity`} type="number" min="0.001" max="100000" step="0.001" required value={l.quantity} onChange={e=>patch(l.id,{quantity:Number(e.target.value)})}/></label><label>Unit<input required maxLength={30} value={l.unit} onChange={e=>patch(l.id,{unit:e.target.value})}/></label><label>Material / unit ($)<input type="number" min="0" max="10000000" step="0.01" required value={l.material_cents/100} onChange={e=>patch(l.id,{material_cents:Math.round(Number(e.target.value)*100)})}/></label><label>Labor / unit ($)<input type="number" min="0" max="10000000" step="0.01" required value={l.labor_cents/100} onChange={e=>patch(l.id,{labor_cents:Math.round(Number(e.target.value)*100)})}/></label><label>Sell / unit ($)<input aria-label={`Item ${index+1} unit price`} type="number" min="0" max="10000000" step="0.01" required value={l.unit_price_cents/100} onChange={e=>patch(l.id,{unit_price_cents:Math.round(Number(e.target.value)*100)})}/></label></div><div className="item-bottom"><label className="check-field"><input type="checkbox" checked={l.taxable} onChange={e=>patch(l.id,{taxable:e.target.checked})}/>Taxable</label><span>Line total <strong>{money(lineAmount(l.quantity,l.unit_price_cents))}</strong></span></div></section>)}</div>
 <div className="form-grid"><label>Target gross margin (%)<input name="target_margin" type="number" min="0" max="99.99" step="0.01" required value={margin} onChange={e=>setMargin(Number(e.target.value))}/></label><div className="align-bottom"><button type="button" className="secondary" onClick={()=>{try{setLines(old=>old.map(l=>({...l,unit_price_cents:priceForMargin(l.material_cents+l.labor_cents,margin)})));setCalculationError('');}catch(e){setCalculationError((e as Error).message);}}}>Apply margin to every item</button></div></div><p className="muted small">Margin pricing uses cost ÷ (1 − margin). Discounts reduce the achieved margin shown below.</p>
 <div className="form-grid three"><label>Discount (%)<input name="discount_percent" type="number" min="0" max="99.99" step="0.01" required value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><label>Tax on taxable items (%)<input name="tax_rate" type="number" min="0" max="30" step="0.01" required value={tax} onChange={e=>setTax(Number(e.target.value))}/></label><label>Deposit (%)<input name="deposit_percent" type="number" min="0" max="100" step="0.01" required value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/></label></div>
 <label>Valid through<input name="valid_until" type="date" defaultValue={o.valid_until??''}/></label><label>Proposal terms<textarea name="terms" maxLength={10000} rows={4} defaultValue={o.terms??''}/></label>
 </SaveForm>
 {(validation||calculationError)&&<p className="error" role="alert">{validation||calculationError}</p>}
 {totals&&<div className="quote-total-grid"><section className="cost-summary"><h4>Internal estimate</h4><dl><div><dt>Materials</dt><dd>{money(totals.material_cost_cents)}</dd></div><div><dt>Labor</dt><dd>{money(totals.labor_cost_cents)}</dd></div><div><dt>Gross profit before tax</dt><dd>{money(totals.profit_cents)}</dd></div><div><dt>Achieved gross margin</dt><dd className={totals.margin_percent<margin?'attention-text':''}>{totals.margin_percent.toFixed(1)}%</dd></div></dl></section><section className="price-summary"><h4>Customer price</h4><dl><div><dt>Subtotal</dt><dd>{money(totals.subtotal_cents)}</dd></div><div><dt>Discount</dt><dd>−{money(totals.discount_cents)}</dd></div><div><dt>Tax</dt><dd>{money(totals.tax_cents)}</dd></div><div className="total"><dt>Total</dt><dd>{money(totals.price_cents)}</dd></div><div><dt>Deposit requested</dt><dd>{money(totals.deposit_cents)}</dd></div></dl></section></div>}
 <section className="revision-history"><h3>Saved proposal revisions</h3><p className="muted small">Save items, then use “Create estimate” on the job to create the first proposal. Later estimate saves create a new revision.</p>{d.estimates.filter(e=>e.work_order_id===o.id).sort((a,b)=>b.version-a.version).map(e=><a key={e.id} href={`/estimates/${e.id}`} target="_blank" rel="noreferrer"><span>Revision {e.version} · {e.status==='approved'?'Approved & locked':'Draft proposal'}</span><strong>{money(e.price_cents)}</strong></a>)}</section>
 </div>;
}
