'use client';
import { useState } from 'react';
import { ArrowRight, CalendarDays, Check, Plus, FileText } from 'lucide-react';
import { canWrite, dateLabel, nextStage, STAGES, STAGE_LABELS, type DataSet, type WorkOrder } from '@/lib/core';
import { closeoutChecks, jobFinancials, money, profileFor } from '@/lib/field';
import { CheckField, Empty, SaveForm } from './forms';
import { LEAD_SOURCES, DEMO_OPERATIONS_OWNERS, withCurrentOption, ORDER_LABELS, partnerLabel, purchaseStatusLabel } from '@/lib/field-options';
import { EstimateEditor } from './estimate-editor';
import { AIAssistant } from './ai-assistant';

type JobTab='overview'|'consultation'|'estimate'|'production'|'financials'|'files'|'activity'|'closeout';
export function JobWorkspace({data:d,order:o,onAdvance,onShow,onToggle,onCopyDemo,saving,error}:{data:DataSet;order:WorkOrder;onAdvance:()=>void;onCopyDemo:()=>void;onShow:(kind:'appointment'|'schedule'|'task'|'purchase')=>void;onToggle:(id:string,checked:boolean)=>void;saving:boolean;error:string}){
 const [tab,setTab]=useState<JobTab>(o.stage==='appointment'?'consultation':o.stage==='estimated'?'estimate':['approved','scheduled','in_progress','completed'].includes(o.stage)?'production':o.stage==='invoice_ready'?'closeout':'overview');const p=profileFor(d,o);const c=d.contacts.find(c=>c.id===o.contact_id);const writable=canWrite(d.role);const f=jobFinancials(d,o);const checks=closeoutChecks(d,o);
 const labels:Record<JobTab,string>={overview:'Customer & opportunity',consultation:'Consultation',estimate:'Estimate',production:'Production',financials:'Job financials',files:'Files & photos',activity:'Activity',closeout:'Closeout'};
 return <div className="job-workspace"><div className="job-top"><div><span className={`status ${o.stage}`}>{STAGE_LABELS[o.stage]}</span><h3>{c?.name}</h3><p>{p.job_address||c?.address||'Add the job address'}</p></div>{writable&&nextStage(o.stage)&&<button className="primary" disabled={saving} onClick={()=>{if(o.stage==='lead'&&!d.appointments.some(a=>a.work_order_id===o.id)){onShow('appointment');}else if(o.stage==='appointment'){setTab(p.consultation_complete?'estimate':'consultation');}else if(o.stage==='approved'&&(!o.scheduled_at||!o.assigned_partner_id)){onShow('schedule');}else{onAdvance();}}}>{saving?'Saving…':({lead:'Move to consultation',appointment:'Create estimate',estimated:'Record demo approval',approved:'Confirm schedule',scheduled:'Start job',in_progress:'Complete job',completed:'Prepare invoice',invoice_ready:''})[o.stage]}<ArrowRight size={17}/></button>}</div>
 {error&&<p className="error" role="alert">{error}</p>}<div className="stage-track">{STAGES.map((s,i)=><span title={STAGE_LABELS[s]} key={s} className={i<=STAGES.indexOf(o.stage)?'reached':''}>{i<STAGES.indexOf(o.stage)?<Check size={12}/>:i+1}</span>)}</div>
 <nav className="job-tabs" aria-label="Job sections">{Object.entries(labels).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key as JobTab)}>{label}</button>)}</nav><div className="job-tab-content">
 {tab==='overview'&&<><div className="contact-summary"><div><span className="eyebrow">CUSTOMER CONTACT</span><strong>{c?.name}</strong><p>{c?.email||'Email not recorded'}</p><p>{c?.phone||'Phone not recorded'}</p></div><div><span className="eyebrow">WORK RECORD</span><strong>WF-{o.number}</strong><p>{o.title}</p><p>{p.sales_status==='lost'?`Lost · ${p.lost_reason}`:'Open opportunity / active work'}</p></div></div>
 <SaveForm workspaceId={d.workspace.id} orderId={o.id} action="qualification" writable={writable}><div className="form-grid"><label>Primary service<input name="service" defaultValue={p.service} maxLength={200} placeholder="e.g. Landscape installation"/></label><label>Lead source<select name="source" defaultValue={p.source}>{withCurrentOption(LEAD_SOURCES,p.source).map(source=><option key={source} value={source}>{source}</option>)}</select></label><label>Sales owner<input name="sales_owner" defaultValue={p.sales_owner} maxLength={200}/></label><label>Priority<select name="priority" defaultValue={p.priority}><option value="normal">Normal</option><option value="high">High priority</option></select></label><label>Next follow-up<input name="follow_up_on" type="date" defaultValue={p.follow_up_on??''}/></label><label>Opportunity status<select name="sales_status" defaultValue={p.sales_status}><option value="open">Open / won</option><option value="lost">Lost</option></select></label></div><label>Lost reason, if applicable<input name="lost_reason" maxLength={1000} defaultValue={p.lost_reason}/></label><label>Job / property address<input name="job_address" maxLength={400} defaultValue={p.job_address}/></label></SaveForm></>}
 {tab==='consultation'&&<><AIAssistant workspaceId={d.workspace.id} orderId={o.id} kind="consultation" writable={writable}/><div className="section-heading flush"><div><p className="eyebrow">CAPTURE THE SITE BEFORE PRICING</p><h3>Field consultation</h3></div>{writable&&<button className="secondary" onClick={()=>onShow('appointment')}><Plus size={16}/>Appointment</button>}</div><div className="consultation-events">{d.appointments.filter(a=>a.work_order_id===o.id).map(a=><div key={a.id}><CalendarDays size={18}/><span><strong>{a.title}</strong><small>{dateLabel(a.starts_at,d.workspace.timezone)} – {dateLabel(a.ends_at,d.workspace.timezone)}</small></span></div>)}</div><SaveForm workspaceId={d.workspace.id} orderId={o.id} action="consultation" writable={writable} key={p.consultation_summary}><label>Reviewed consultation summary<textarea name="consultation_summary" rows={4} maxLength={5000} defaultValue={p.consultation_summary??''}/></label><label>Customer goals, timing & budget<textarea name="goals" rows={4} maxLength={5000} defaultValue={p.goals}/></label><label>Measurements & quantities<textarea name="measurements" rows={4} maxLength={5000} placeholder="Area / feature, quantity, unit, how measured" defaultValue={p.measurements}/></label><div className="form-grid"><label>Access & site logistics<textarea name="access_notes" rows={4} maxLength={5000} placeholder="Gates, equipment access, parking, staging" defaultValue={p.access_notes}/></label><label>Site conditions & risks<textarea name="site_conditions" rows={4} maxLength={5000} placeholder="Drainage, utilities, existing surfaces, demolition" defaultValue={p.site_conditions}/></label></div><CheckField name="consultation_complete" label="Consultation reviewed and ready for estimating" checked={p.consultation_complete}/></SaveForm><div className="button-row"><button className="secondary" onClick={()=>setTab('files')}>Add site photos</button><button className="primary" onClick={()=>setTab('estimate')}>Open estimate builder<ArrowRight size={17}/></button></div></>}
 {tab==='estimate'&&<><AIAssistant workspaceId={d.workspace.id} orderId={o.id} kind="estimate" writable={writable&&['lead','appointment','estimated'].includes(o.stage)}/><EstimateEditor key={o.updated_at} data={d} order={o} onCopyDemo={onCopyDemo} copying={saving}/></>}
 {tab==='production'&&<><div className="section-heading flush"><div><p className="eyebrow">DELIVER THE ACCEPTED SCOPE</p><h3>Production readiness</h3></div>{writable&&['approved','scheduled'].includes(o.stage)&&<button className="primary" onClick={()=>onShow('schedule')}>Assign date & crew</button>}</div><div className="readiness-grid"><div className={f.estimate?'ready':''}><strong>{f.estimate?'Estimate approved':'Approval pending'}</strong><small>Customer authorization</small></div><div className={o.assigned_partner_id&&o.scheduled_at?'ready':''}><strong>{d.partners.find(x=>x.id===o.assigned_partner_id)?.name||'Crew unassigned'}</strong><small>{dateLabel(o.scheduled_at,d.workspace.timezone)}</small></div><div className={f.estimate&&f.depositReceived>=f.estimate.deposit_cents?'ready':''}><strong>{money(f.depositReceived)} recorded</strong><small>Deposit requested {money(f.estimate?.deposit_cents??0)}</small></div><div className={p.walkthrough_complete?'ready':''}><strong>{p.walkthrough_complete?'Walkthrough complete':'Walkthrough pending'}</strong><small>Required before job completion</small></div></div>
 <div className="section-heading flush"><h3>Purchasing & Production Assignments</h3>{writable&&<button className="quiet" onClick={()=>onShow('purchase')}><Plus size={16}/>Add order</button>}</div>{d.purchases.filter(x=>x.work_order_id===o.id).map(x=><div className="commitment-row" key={x.id}><div><strong>PO-{x.po_number} · {x.description}</strong><small>{d.partners.find(v=>v.id===x.partner_id)&&partnerLabel(d.partners.find(v=>v.id===x.partner_id)!)} · {ORDER_LABELS[x.order_kind]}</small></div><strong>{money(x.cost_cents)}</strong><SaveForm workspaceId={d.workspace.id} action="purchase_status" label="Update" writable={writable} extra={{id:x.id}}><label>Status · PO-{x.po_number}<select name="status" defaultValue={x.status}>{(['planned','ordered','received'] as const).map(status=><option key={status} value={status}>{purchaseStatusLabel(x.order_kind,status)}</option>)}</select></label></SaveForm></div>)}<p className="muted small">Draft purchases and assignments here. An approved estimate is required before ordering materials or assigning production work.</p>{!d.purchases.some(x=>x.work_order_id===o.id)&&<Empty>Add materials, internal crew work or subcontract assignments for this job.</Empty>}
 <AIAssistant workspaceId={d.workspace.id} orderId={o.id} kind="handoff" writable={writable&&['approved','scheduled','in_progress'].includes(o.stage)}/><SaveForm workspaceId={d.workspace.id} orderId={o.id} action="operations" writable={writable} key={p.operations_notes}><div className="form-grid"><label>Operations owner{d.workspace.is_demo?<select name="operations_owner" defaultValue={p.operations_owner}><option value="">Select an operations owner</option>{withCurrentOption(DEMO_OPERATIONS_OWNERS,p.operations_owner).map(owner=><option key={owner} value={owner}>{owner}</option>)}</select>:<input name="operations_owner" defaultValue={p.operations_owner} maxLength={200}/>}</label><label>Materials readiness<select name="materials_status" defaultValue={p.materials_status}><option value="not_ordered">Not ordered</option><option value="ordered">Ordered</option><option value="staged">Staged</option><option value="delivered">Delivered</option></select></label></div><label>Production, access & closeout notes<textarea name="operations_notes" rows={4} maxLength={5000} defaultValue={p.operations_notes}/></label><CheckField name="walkthrough_complete" label="Customer walkthrough completed; punch-list items resolved" checked={p.walkthrough_complete}/><CheckField name="costs_reviewed" label="All job costs entered and reviewed for reporting" checked={p.costs_reviewed}/></SaveForm>
 <div className="section-heading flush"><h3>Job tasks & punch list</h3>{writable&&<button className="quiet" onClick={()=>onShow('task')}><Plus size={16}/>Add task</button>}</div>{d.tasks.filter(t=>t.work_order_id===o.id).map(t=><label className="job-task" key={t.id}><input type="checkbox" checked={t.completed} disabled={!writable||saving} onChange={e=>onToggle(t.id,e.target.checked)}/><span>{t.title}{t.due_on&&<small>Due {t.due_on}</small>}</span></label>)}

 {o.stage==='invoice_ready'&&<a className="button secondary" href={`/api/export?workspace=${d.workspace.id}&kind=invoices&order=${o.id}`}>Download invoice handoff CSV</a>}</>}
 {tab==='closeout'&&<><div className="section-heading flush"><div><p className="eyebrow">FROM FINISHED WORK TO A CLOSED JOB</p><h3>{checks.every(c=>c.done)?'Closeout complete':'Closeout checklist'}</h3></div></div><p className="muted small">Complete production, record costs and customer payments, and prepare the invoice handoff. This demo records receipts manually; it does not charge customers or send invoices.</p><div className="closeout-checks">{checks.map(check=><button className={check.done?'complete':''} key={check.label} onClick={()=>setTab(check.tab)}><span>{check.done?<Check size={18}/>:<span className="check-pending"/>}</span>{check.label}<ArrowRight size={16}/></button>)}</div>{o.stage==='invoice_ready'&&<a className="button secondary" href={`/api/export?workspace=${d.workspace.id}&kind=invoices&order=${o.id}`}>Download invoice handoff CSV</a>}</>}
 {tab==='financials'&&<JobFinancials data={d} order={o}/>}
 {tab==='files'&&<><div className="section-heading flush"><h3>Private job files & photos</h3></div>{d.files.filter(x=>x.work_order_id===o.id).map(x=><a className="file-link" key={x.id} href={`/api/files/${x.id}`} target="_blank" rel="noreferrer"><FileText size={18}/><span>{x.name}</span><small>{Math.ceil(x.size_bytes/1024)} KB</small></a>)}{!d.files.some(x=>x.work_order_id===o.id)&&<Empty>Add site photos, scope documents and completion records.</Empty>}<SaveForm workspaceId={d.workspace.id} orderId={o.id} action="upload" label="Upload file" writable={writable}><label>JPEG, PNG, WebP or PDF · up to 3 MB<input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></label></SaveForm></>}
 {tab==='activity'&&<div className="activity-timeline">{d.activity.filter(a=>a.work_order_id===o.id).map(a=><div key={a.id}><span className="timeline-dot"/><div><strong>{a.action}</strong><small>{dateLabel(a.created_at,d.workspace.timezone)}</small></div></div>)}</div>}
 </div></div>;
}
function JobFinancials({data:d,order:o}:{data:DataSet;order:WorkOrder}){
 const [kind,setKind]=useState<'expense'|'receipt'>('expense');const [show,setShow]=useState(false);const f=jobFinancials(d,o);const writable=canWrite(d.role);const records=d.financials.filter(r=>r.work_order_id===o.id).sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on));
 return <><div className="section-heading flush"><div><p className="eyebrow">BUDGET, COSTS & COLLECTIONS</p><h3>Job financials</h3></div>{writable&&<button className="primary" onClick={()=>setShow(!show)}><Plus size={16}/>Record transaction</button>}</div><div className="readiness-grid financial-metrics"><div><small>Budgeted labor + material</small><strong>{money(o.labor_cost_cents+o.material_cost_cents)}</strong></div><div><small>Recorded expense</small><strong>{money(f.expenses)}</strong></div><div><small>Customer balance</small><strong>{f.balance===null?'No contract yet':money(f.balance)}</strong></div><div><small>Gross profit · excluding tax</small><strong>{f.profit===null?'Costs incomplete':money(f.profit)}</strong></div></div><p className="muted small">These are manually recorded costs and receipts. They are not bank reconciliation or a live accounting feed. Review complete costs in Production before reporting gross profit.</p>
 {show&&<SaveForm workspaceId={d.workspace.id} orderId={o.id} action="financial" label="Record transaction" onSaved={()=>setShow(false)}><div className="form-grid"><label>Record type<select name="kind" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="expense">Job expense</option><option value="receipt">Customer payment received</option></select></label><label>Category<select name="category" key={kind}>{(kind==='expense'?['labor','materials','other']:['deposit','progress','final']).map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Amount ($)<input type="number" name="amount" min="0.01" step="0.01" required/></label><label>Date<input type="date" name="occurred_on" required/></label></div><label>Unique bill / receipt reference<input name="reference" required maxLength={200}/></label><label>Notes<textarea name="notes" rows={2} maxLength={5000}/></label></SaveForm>}
 <div className="financial-ledger">{records.map(r=><div key={r.id} className={r.voided?'voided':''}><div><small>{r.occurred_on} · {r.kind} · {r.category}{r.voided?' · VOID':''}</small><strong>{r.reference}</strong><p>{r.notes}</p></div><strong>{money(r.amount_cents)}</strong>{writable&&!r.voided&&<details className="void-confirm"><summary>Correct entry</summary><p>Void this entry, then record its replacement with a distinct reference.</p><SaveForm workspaceId={d.workspace.id} action="void_financial" extra={{id:r.id}} label="Void entry"><span className="small">{r.reference}</span></SaveForm></details>}</div>)}{!records.length&&<Empty>No expenses or customer receipts have been recorded for this job.</Empty>}</div></>;
}
