'use client';
import { useState } from 'react';
import { ArrowRight, Plus, Search, BookOpen, AlertCircle } from 'lucide-react';
import { canWrite, priceForMargin, STAGE_LABELS, type DataSet, type Contact } from '@/lib/core';
import { jobFinancials, latestEstimate, money, profileFor, type PricebookItem } from '@/lib/field';
import { CheckField, Empty, SaveForm } from './forms';

export function FieldBoard({data:d,mode,onOpen}:{data:DataSet;mode:'sales'|'operations';onOpen:(id:string)=>void}){
 const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:d.workspace.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const columns=mode==='sales'?['lead','appointment','estimated','approved'] as const:['approved','scheduled','in_progress','completed','invoice_ready'] as const;
 const orders=d.orders.filter(o=>{const p=profileFor(d,o);const c=d.contacts.find(c=>c.id===o.contact_id);return (columns as readonly string[]).includes(o.stage)&&`${o.title} ${c?.name} ${p.service} ${p.sales_owner} WF-${o.number}`.toLowerCase().includes(search.toLowerCase())&&(mode!=='sales'||(filter==='lost'?p.sales_status==='lost':p.sales_status!=='lost'))&&(filter!=='followup'||(p.follow_up_on!==null&&p.follow_up_on<=today))&&(filter!=='high'||p.priority==='high');});
 return <><div className="field-toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, job, service or owner"/></div>{mode==='sales'&&<select aria-label="Opportunity filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Open opportunities</option><option value="followup">Follow-up due</option><option value="high">High priority</option><option value="lost">Lost opportunities</option></select>}<span className="muted small">{orders.length} records</span></div>
 <div className={`field-board ${mode==='operations'?'production-board':''}`}>{columns.map(stage=>{const group=orders.filter(o=>o.stage===stage);return <section className="board-column" key={stage}><header><div><span className={`stage-dot ${stage}`}/><h3>{STAGE_LABELS[stage]}</h3><span className="count">{group.length}</span></div><small>{money(group.reduce((sum,o)=>sum+(latestEstimate(d,o.id)?.price_cents??0),0))}</small></header><div className="board-cards">{group.map(o=>{const p=profileFor(d,o);const c=d.contacts.find(c=>c.id===o.contact_id);const q=latestEstimate(d,o.id);const f=jobFinancials(d,o);return <button className="opportunity-card" key={o.id} onClick={()=>onOpen(o.id)}><div className="card-meta"><span>WF-{o.number}</span>{p.priority==='high'&&<span className="priority-tag">High priority</span>}</div><h4>{o.title}</h4><p>{c?.name}</p><span className="service-tag">{p.service||'Service not classified'}</span><div className="card-value">{q?money(q.price_cents):'Estimate not prepared'}<ArrowRight size={17}/></div>{mode==='sales'?<div className="card-foot"><span>{p.sales_owner||'Unassigned'} · {p.source}</span>{p.follow_up_on&&<strong className={p.follow_up_on<=today?'attention-text':''}>Follow up {p.follow_up_on}</strong>}{p.sales_status==='lost'&&<span>Lost: {p.lost_reason}</span>}</div>:<div className="card-foot"><span>{p.operations_owner||'Operations owner unassigned'}</span><span>{d.partners.find(x=>x.id===o.assigned_partner_id)?.name||'Crew not scheduled'}</span><span>Materials: {p.materials_status.replaceAll('_',' ')}</span>{f.estimate&&f.depositReceived<f.estimate.deposit_cents&&<strong className="attention-text">Deposit remaining: {money(f.estimate.deposit_cents-f.depositReceived)}</strong>}</div>}</button>;})}{!group.length&&<p className="column-empty">No work at this stage</p>}</div></section>;})}</div></>;
}

export function Pricebook({data:d}:{data:DataSet}){
 const [search,setSearch]=useState('');const [editing,setEditing]=useState<PricebookItem|'new'|null>(null);const item=editing==='new'?null:editing;const writable=canWrite(d.role);
 return <><div className="field-toolbar"><div className="search"><Search size={18}/><input placeholder="Search service, category or unit" value={search} onChange={e=>setSearch(e.target.value)}/></div>{writable&&<button className="primary" onClick={()=>setEditing('new')}><Plus size={17}/>Add pricebook item</button>}</div>
 {editing&&<section className="panel inline-editor"><div className="section-heading flush"><h2>{item?'Edit item':'New service or material'}</h2><button className="quiet" onClick={()=>setEditing(null)}>Close</button></div><SaveForm key={item?.id??'new'} workspaceId={d.workspace.id} action="pricebook" extra={item?{id:item.id}:undefined} onSaved={()=>setEditing(null)}><div className="form-grid"><label>Name<input name="name" required maxLength={200} defaultValue={item?.name}/></label><label>Category<input name="category" required maxLength={100} defaultValue={item?.category??'General'}/></label></div><label>Customer description<textarea name="description" maxLength={3000} defaultValue={item?.description} rows={3}/></label><div className="form-grid"><label>Unit<input name="unit" required maxLength={30} defaultValue={item?.unit??'each'} list="field-units"/></label><label>Target gross margin (%)<input name="target_margin" type="number" min="0" max="99.99" step="0.01" defaultValue={item?.target_margin??40} required/></label><label>Material cost per unit ($)<input name="material_cost" type="number" min="0" step="0.01" defaultValue={(item?.material_cents??0)/100} required/></label><label>Labor cost per unit ($)<input name="labor_cost" type="number" min="0" step="0.01" defaultValue={(item?.labor_cents??0)/100} required/></label></div><datalist id="field-units">{['sq ft','linear ft','cu yd','ton','hour','each','job'].map(x=><option key={x}>{x}</option>)}</datalist><div className="check-row"><CheckField name="taxable" label="Taxable" checked={item?.taxable}/><CheckField name="active" label="Available for new estimates" checked={item?.active??true}/></div></SaveForm></section>}
 <div className="pricebook-grid">{d.pricebook.filter(p=>`${p.name} ${p.category} ${p.unit}`.toLowerCase().includes(search.toLowerCase())).map(p=><section key={p.id} className={`panel pricebook-card ${!p.active?'archived':''}`}><div className="card-meta"><span className="service-tag">{p.category}</span><BookOpen size={19}/></div><h3>{p.name}</h3><p>{p.description||'No description yet.'}</p><div className="catalog-price">{money(priceForMargin(p.material_cents+p.labor_cents,Number(p.target_margin)))}<small> / {p.unit}</small></div><div className="catalog-costs"><span>Material {money(p.material_cents)}</span><span>Labor {money(p.labor_cents)}</span><span>Margin {p.target_margin}%</span></div><div className="card-bottom"><small>{p.active?'Active':'Archived'} · {p.taxable?'Taxable':'Non-taxable'}</small>{writable&&<button className="quiet" onClick={()=>setEditing(p)}>Edit item</button>}</div></section>)}</div>{!d.pricebook.length&&<Empty>Add your services and unit costs. Estimate items preserve their own copy when catalog prices change.</Empty>}</>;
}

export function Customers({data:d,onOpen}:{data:DataSet;onOpen:(id:string)=>void}){
 const [search,setSearch]=useState('');const [selected,setSelected]=useState<string|null>(null);const [newJob,setNewJob]=useState(false);const c=d.contacts.find(c=>c.id===selected);const writable=canWrite(d.role);
 return <div className="customer-workspace"><section className="panel"><div className="table-toolbar"><div className="search"><Search size={18}/><input placeholder="Search customer, email, phone or address" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="customer-list">{d.contacts.filter(c=>`${c.name} ${c.email} ${c.phone} ${c.address}`.toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.id} className={c.id===selected?'selected':''} onClick={()=>{setSelected(c.id);setNewJob(false);}}><span className="customer-initial">{c.name.slice(0,1)}</span><span><strong>{c.name}</strong><small>{c.customer_type} · {c.phone||c.email||'No contact details'}</small><small>{c.address}</small></span><ArrowRight size={16}/></button>)}</div></section>
 <section className="panel customer-detail">{c?<><div className="section-heading flush"><div><span className="eyebrow">CUSTOMER RECORD</span><h2>{c.name}</h2></div>{writable&&<button className="secondary" onClick={()=>setNewJob(!newJob)}><Plus size={16}/>New job</button>}</div>{newJob&&<SaveForm workspaceId={d.workspace.id} action="customer_job" extra={{contact_id:c.id}} label="Create job for this customer" onSaved={id=>{setNewJob(false);if(id)onOpen(id);}}><label>Job name<input name="title" maxLength={200} required/></label><label>Initial scope<textarea name="description" rows={3}/></label></SaveForm>}
 <CustomerForm key={c.id} contact={c} workspaceId={d.workspace.id} writable={writable}/><h3 className="subheading">Jobs & property history</h3><div className="related-jobs">{d.orders.filter(o=>o.contact_id===c.id).map(o=><button key={o.id} onClick={()=>onOpen(o.id)}><div><small>WF-{o.number} · {STAGE_LABELS[o.stage]}</small><strong>{o.title}</strong><span>{profileFor(d,o).job_address||c.address}</span></div><ArrowRight size={18}/></button>)}</div></>:<Empty>Select a customer to view their contact information, notes and complete job history.</Empty>}</section></div>;
}
function CustomerForm({contact:c,workspaceId,writable}:{contact:Contact;workspaceId:string;writable:boolean}){return <SaveForm workspaceId={workspaceId} action="edit_contact" writable={writable} extra={{id:c.id}}><div className="form-grid"><label>Customer / company name<input name="name" defaultValue={c.name} required maxLength={200}/></label><label>Customer type<input name="customer_type" defaultValue={c.customer_type} required maxLength={100} list="customer-types"/></label><label>Email<input name="email" type="email" defaultValue={c.email}/></label><label>Phone<input name="phone" type="tel" defaultValue={c.phone}/></label></div><datalist id="customer-types">{['Residential','Commercial','HOA / Property management','Government'].map(x=><option key={x}>{x}</option>)}</datalist><label>Primary address<input name="address" defaultValue={c.address} maxLength={400}/></label><label>Customer notes<textarea name="notes" rows={3} defaultValue={c.notes}/></label></SaveForm>;}

export function FieldReports({data:d,onOpen}:{data:DataSet;onOpen:(id:string)=>void}){
 const jobs=d.orders.map(o=>({o,p:profileFor(d,o),f:jobFinancials(d,o)}));const contracted=jobs.filter(j=>j.f.estimate);const totalContract=contracted.reduce((s,j)=>s+j.f.estimate!.price_cents,0);const totalReceived=jobs.reduce((s,j)=>s+j.f.receipts,0);const unreviewed=contracted.filter(j=>!j.f.reviewed).length;
 const sources=Array.from(new Set(jobs.map(j=>j.p.source||'Unclassified')));
 return <><section className="metrics"><div className="metric"><span>Accepted contract value</span><strong>{money(totalContract)}</strong><small>Includes configured tax</small></div><div className="metric"><span>Receipts recorded</span><strong>{money(totalReceived)}</strong><small>Manual records · not bank reconciliation</small></div><div className="metric"><span>Actual costs recorded</span><strong>{money(jobs.reduce((s,j)=>s+j.f.expenses,0))}</strong><small>Expense entries, excluding voids</small></div><div className="metric"><span>Costs awaiting review</span><strong>{unreviewed}</strong><small>Jobs with an accepted estimate</small></div></section>
 <section className="panel"><div className="section-heading"><h2>Job profitability & collections</h2><span className="muted small">Revenue excludes tax for gross profit</span></div><div className="table-wrap"><table><thead><tr><th>Job</th><th>Net contract</th><th>Budgeted cost</th><th>Committed</th><th>Recorded cost</th><th>Gross profit</th><th>Balance</th></tr></thead><tbody>{contracted.map(({o,f})=><tr key={o.id}><td><button className="record-link" onClick={()=>onOpen(o.id)}><small>WF-{o.number}</small>{o.title}</button></td><td>{money(f.net)}</td><td>{money(o.labor_cost_cents+o.material_cost_cents)}</td><td>{money(f.committed)}</td><td>{money(f.expenses)}</td><td>{f.profit===null?<span className="pending-cost"><AlertCircle size={14}/>Costs incomplete</span>:money(f.profit)}</td><td>{money(f.balance??0)}</td></tr>)}</tbody></table>{!contracted.length&&<Empty>Accepted estimates will appear here with their job costs and recorded payments.</Empty>}</div></section>
 <section className="panel report-section"><div className="section-heading"><h2>Lead source performance</h2><span className="muted small">Based on recorded source; no attribution assumptions</span></div><div className="table-wrap"><table><thead><tr><th>Source</th><th>Opportunities</th><th>Won</th><th>Lost</th><th>Accepted value</th></tr></thead><tbody>{sources.map(source=>{const group=jobs.filter(j=>(j.p.source||'Unclassified')===source);return <tr key={source}><td>{source}</td><td>{group.length}</td><td>{group.filter(j=>j.f.estimate).length}</td><td>{group.filter(j=>j.p.sales_status==='lost').length}</td><td>{money(group.reduce((s,j)=>s+(j.f.estimate?.price_cents??0),0))}</td></tr>;})}</tbody></table></div></section></>;
}
